const fs = require('fs');

const questions = [
  // LOTS (1-15) - HTTP Methods, Status Codes, REST API Architecture, Node.js/Express basics, JSON
  { cat: "Web Dev Lanjutan", q: "Metode HTTP yang digunakan untuk MEMINTA (mengambil) data dari server tanpa mengubah state data di server adalah...", o: ["POST", "GET", "PUT", "DELETE", "PATCH"], c: 1, exp: "GET digunakan khusus untuk murni membaca/mengambil data (safe & idempotent)." },
  { cat: "Web Dev Lanjutan", q: "Metode HTTP yang digunakan untuk MENGIRIM data baru ke server untuk membuat resource baru di database adalah...", o: ["GET", "POST", "PUT", "DELETE", "OPTIONS"], c: 1, exp: "POST digunakan untuk mengirimkan payload data baru ke server." },
  { cat: "Web Dev Lanjutan", q: "Metode HTTP yang digunakan untuk MEMPERBARUI (mengganti secara keseluruhan) suatu resource yang ada adalah...", o: ["GET", "POST", "PUT", "PATCH", "DELETE"], c: 2, exp: "PUT mengganti seluruh representasi resource target." },
  { cat: "Web Dev Lanjutan", q: "Metode HTTP yang digunakan untuk memperbarui data HANYA SEBAGIAN (partial update) atribut saja dinamakan...", o: ["PUT", "PATCH", "POST", "UPDATE", "MODIFY"], c: 1, exp: "PATCH diperuntukkan bagi pembaruan parsial pada atribut tertentu." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP (HTTP Status Code) `200 OK` menandakan bahwa...", o: ["Request berhasil dan server mengembalikan respon yang diminta", "Resource tidak ditemukan", "Server mengalami error internal", "Pengguna belum login", "Request dilarang"], c: 0, exp: "200 OK adalah status baku keberhasilan pemrosesan HTTP request." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP `201 Created` biasanya dikembalikan oleh REST API setelah sukses mengeksekusi metode...", o: ["GET", "POST (pembuatan data baru)", "DELETE", "OPTIONS", "HEAD"], c: 1, exp: "201 Created menandakan request berhasil dan pembuatan resource baru tuntas." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP `404 Not Found` menandakan bahwa...", o: ["Server down", "Resource URL yang diminta tidak ditemukan di server", "Password pengguna salah", "Format JSON salah", "Akses dilarang"], c: 1, exp: "404 Not Found berarti server tidak menemukan URI endpoint yang diminta client." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP `401 Unauthorized` menandakan bahwa...", o: ["Resource tidak ada", "Client belum melakukan autentikasi (belum login / token tidak valid)", "Server sedang maintenance", "Format data salah", "Metode HTTP tidak diizinkan"], c: 1, exp: "401 Unauthorized mengindikasikan kredensial autentikasi tidak ada atau tidak sah." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP `403 Forbidden` menandakan bahwa...", o: ["Client belum login", "Client sudah terautentikasi tetapi TIDAK MEMILIKI HAK AKSES (otorisasi) ke resource tersebut", "Server crash", "Koneksi terputus", "Data berhasil dihapus"], c: 1, exp: "403 Forbidden terjadi saat server mengenali user tetapi menolak memberikan akses." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP `500 Internal Server Error` mengindikasikan bahwa...", o: ["Kesalahan ada di sisi input client", "Terjadi crash/unhandled exception di sisi aplikasi server", "URL salah", "Database kosong", "Koneksi internet client putus"], c: 1, exp: "500 menandakan kegagalan pemrosesan tak terduga di server." },
  { cat: "Web Dev Lanjutan", q: "Format pertukaran data berbasis teks ringan yang paling populer digunakan dalam komunikasi REST API adalah...", o: ["XML", "JSON (JavaScript Object Notation)", "CSV", "YAML", "HTML"], c: 1, exp: "JSON adalah format standar industri komunikasi REST API." },
  { cat: "Web Dev Lanjutan", q: "Metode Fetch API browser JavaScript `fetch(url)` mengembalikan sebuah kembalian berupa...", o: ["String JSON langsung", "Promise yang menyelesaikan objek Response", "Array objek", "Boolean true/false", "XML Document"], c: 1, exp: "`fetch()` bersifat asynchronous dan me-return sebuah Promise." },
  { cat: "Web Dev Lanjutan", q: "Fungsi middleware pada framework Node.js (seperti Express.js) adalah...", o: ["Fungsi yang memiliki akses ke objek Request, Response, dan fungsi `next()` untuk memproses request di tengah jalan", "Fungsi untuk membuat tabel database", "Fungsi untuk merender HTML di browser", "Fungsi untuk mengacak password", "Fungsi untuk mengganti CSS"], c: 0, exp: "Middleware bertindak sebagai perantara pemroses request sebelum mencapai route handler akhir." },
  { cat: "Web Dev Lanjutan", q: "Header HTTP yang digunakan client untuk mengirimkan token autentikasi (misal Bearer Token) ke server adalah...", o: ["Content-Type", "Authorization", "Accept", "User-Agent", "Host"], c: 1, exp: "Header `Authorization: Bearer <token>` digunakan untuk otentikasi." },
  { cat: "Web Dev Lanjutan", q: "Header HTTP `Content-Type: application/json` memberitahu server bahwa...", o: ["Client meminta file gambar", "Body pesan yang dikirim berformat JSON", "Koneksi bersifat rahasia", "Response berukuran 100kb", "Client menggunakan browser Chrome"], c: 1, exp: "`Content-Type` memberitahukan media type dari body payload yang dikirim." },

  // MOTS (16-30) - JWT (JSON Web Token), OAuth2, Async/Await, Express Routing, CORS, Stateless REST
  { cat: "Web Dev Lanjutan", q: "Standar industri terbuka untuk representasi klaim keamanan secara aman antara dua pihak yang terdiri dari 3 bagian (Header, Payload, Signature) dinamakan...", o: ["JWT (JSON Web Token)", "API Key", "Session Cookie", "Basic Auth", "OAuth1"], c: 0, exp: "JWT terdiri dari 3 komponen terpisah titik: Header.Payload.Signature." },
  { cat: "Web Dev Lanjutan", q: "Tiga bagian pembentuk struktur JSON Web Token (JWT) secara berurutan adalah...", o: ["Header, Payload, Signature", "Title, Body, Footer", "User, Pass, Secret", "Algorithm, Data, Key", "Token, Hash, Salt"], c: 0, exp: "JWT = Header (algoritma) + Payload (data klaim) + Signature (verifikasi kunci rahasia)." },
  { cat: "Web Dev Lanjutan", q: "Apakah informasi (claims) di dalam bagian Payload JWT terenkripsi secara rahasia secara default?", o: ["Ya, sangat rahasia", "TIDAK terenkripsi, hanya di-encode dengan Base64Url sehingga BISA DIBACA oleh siapapun yang memiliki token!", "Hanya bisa dibaca oleh Google", "Hanya berupa angka", "Terdekripsi otomatis"], c: 1, exp: "Payload JWT di-encode Base64Url, bukan terenkripsi! Jangan menyimpan password/data sensitif di payload." },
  { cat: "Web Dev Lanjutan", q: "Mekanisme keamanan browser yang membatasi skrip web di satu origin untuk meminta resource dari origin (domain/port) lain dinamakan...", o: ["XSS", "CORS (Cross-Origin Resource Sharing)", "CSRF", "CSP", "SameSite"], c: 1, exp: "CORS adalah kebijakan keamanan browser untuk mengatur akses antar origin berbeda." },
  { cat: "Web Dev Lanjutan", q: "Jika frontend berjalan di `http://localhost:3000` dan memanggil backend di `http://localhost:5000`, browser akan memblokir request tersebut jika server tidak mengirimkan response header...", o: ["Access-Control-Allow-Origin: * (atau http://localhost:3000)", "Authorization: Bearer", "Content-Type: text/html", "Cache-Control: no-cache", "Set-Cookie: sessionid"], c: 0, exp: "Header `Access-Control-Allow-Origin` wajib diizinkan server agar browser meloloskan panggilan CORS." },
  { cat: "Web Dev Lanjutan", q: "Prinsip utama arsitektur RESTful yang menyatakan bahwa server TIDAK menyimpan status sesi client di memori server antara request dinamakan...", o: ["Stateful", "Statelessness", "Cacheable", "Layered System", "Code on Demand"], c: 1, exp: "Statelessness berarti setiap request dari client harus memuat seluruh informasi yang dibutuhkan server." },
  { cat: "Web Dev Lanjutan", q: "Keyword `async` sebelum deklarasi fungsi di JavaScript menandakan bahwa fungsi tersebut...", o: ["Berjalan secara synchronous", "SELALU mengembalikan sebuah Promise", "Tidak bisa memiliki parameter", "Berjalan di thread terpisah", "Otomatis di-loop"], c: 1, exp: "Fungsi `async` otomatis mengembalikan Promise yang membungkus nilai return-nya." },
  { cat: "Web Dev Lanjutan", q: "Keyword `await` HANYA dapat digunakan di dalam...", o: ["Fungsi biasa synchronous", "Fungsi yang dideklarasikan dengan keyword `async`", "Blok for loop biasa", "Di dalam file CSS", "Di dalam tag HTML nav"], c: 1, exp: "`await` menunda eksekusi dalam async function hingga Promise tuntas (resolved/rejected)." },
  { cat: "Web Dev Lanjutan", q: "Manakah penanganan error (error handling) yang tepat saat menggunakan `async/await` di JavaScript?", o: ["Menggunakan blok `try { ... } catch (error) { ... }`", "Menggunakan if(error)", "Menggunakan event.onerror", "Tidak perlu error handling", "Menggunakan return null"], c: 0, exp: "Blok `try...catch` adalah cara standar menangani rejeksi Promise pada `async/await`." },
  { cat: "Web Dev Lanjutan", q: "Di Express.js, bagaimana cara mengambil parameter URL dari route `/users/:id`?", o: ["req.body.id", "req.params.id", "req.query.id", "req.headers.id", "req.get('id')"], c: 1, exp: "`req.params` menampung parameter variabel path URL (`:id`)." },
  { cat: "Web Dev Lanjutan", q: "Bagaimana cara mengambil query string dari URL `/products?category=shoes` di Express.js?", o: ["req.params.category", "req.query.category", "req.body.category", "req.get('shoes')", "req.search"], c: 1, exp: "`req.query` menampung nilai query string URL setelah tanda tanya `?`." },
  { cat: "Web Dev Lanjutan", q: "Bagaimana cara mengambil data payload JSON yang dikirim client via method POST di Express.js?", o: ["req.params", "req.query", "req.body (dengan bantuan middleware `express.json()`)", "req.payload", "req.data"], c: 2, exp: "`req.body` berisi payload masukan POST/PUT setelah diparse oleh `express.json()`." },
  { cat: "Web Dev Lanjutan", q: "Protokol standar untuk otorisasi delegasi pihak ketiga (seperti 'Login dengan Google' atau 'Login dengan GitHub') dinamakan...", o: ["OAuth 2.0", "JWT", "Basic Auth", "SAML", "OpenID Connect"], c: 0, exp: "OAuth 2.0 adalah kerangka kerja otorisasi standar untuk akses delegasi." },
  { cat: "Web Dev Lanjutan", q: "Mekanisme pengamanan cookie dengan atribut `HttpOnly` berfungsi untuk...", o: ["Mencegah cookie dibaca/diakses oleh skrip JavaScript di browser (mencegah pencurian cookie via XSS)", "Mencegah cookie dikirim lewat HTTPS", "Membuat cookie bertahan 100 tahun", "Mengompres ukuran cookie", "Menyimpan cookie di server"], c: 0, exp: "Cookie `HttpOnly` ditutup dari akses `document.cookie` di JS, menangkal pencurian session token via XSS." },
  { cat: "Web Dev Lanjutan", q: "Atribut cookie `SameSite=Strict` berfungsi untuk...", o: ["Mencetak cookie di terminal", "Mencegah browser mengikutkan cookie pada cross-site request (mencegah serangan CSRF)", "Membuat cookie expired 1 jam", "Mengenkripsi isi cookie", "Mematikan CORS"], c: 1, exp: "`SameSite=Strict` menangkal serangan Cross-Site Request Forgery (CSRF)." },

  // MOTS+ (31-45) - Tracing Fetch Async/Await, Microservice Concepts, Rate Limiting, API Versioning
  { cat: "Web Dev Lanjutan", q: "Tracing Fetch API:\n`async function getData() {\n  const res = await fetch('/api/data');\n  const data = await res.json();\n  console.log(data);\n}`\nMengapa kita butuh `await` DUA KALI pada fungsi di atas?", o: ["Hanya syarat sintaks JS", "Pemanggilan `fetch()` mengembalikan Promise Objek Response, dan `res.json()` JUGA mengembalikan Promise hasil parse body JSON!", "Agar kode berjalan lebih lambat", "Untuk mencegah CORS", "Untuk membuat variabel const"], c: 1, exp: "Baik koneksi HTTP `fetch()` maupun pembacaan stream body `res.json()` keduanya bernilai asynchronous Promise." },
  { cat: "Web Dev Lanjutan", q: "Strategi API Versioning yang paling umum dan bersih direkomendasikan pada URL REST API adalah...", o: ["Menaruh versi di URL path (contoh: `/api/v1/users` dan `/api/v2/users`)", "Mengubah nama database", "Mengganti nama domain", "Menghapus API lama", "Menggunakan nama file berlainan"], c: 0, exp: "URI Versioning (`/api/v1/...`) menjaga backward-compatibility aplikasi lama tanpa mengganggu versi baru." },
  { cat: "Web Dev Lanjutan", q: "Teknik pembatasan jumlah request HTTP dari 1 IP address dalam rentang waktu tertentu pada server API dinamakan...", o: ["Rate Limiting", "Load Balancing", "API Gateway", "Caching", "Reverse Proxy"], c: 0, exp: "Rate Limiting melindungi API dari penyalahgunaan (DDoS/Spam request) dengan membatasi quota request." },
  { cat: "Web Dev Lanjutan", q: "Kode status HTTP yang dikembalikan server ketika client MELAMPAUI batas quota Rate Limiting adalah...", o: ["400 Bad Request", "401 Unauthorized", "429 Too Many Requests", "503 Service Unavailable", "408 Request Timeout"], c: 2, exp: "429 Too Many Requests dikembalikan saat client melebihi quota rate limit." },
  { cat: "Web Dev Lanjutan", q: "Dalam arsitektur Microservices, komponen tunggal yang bertindak sebagai pintu masuk terpusat untuk mengarahkan (routing) request client ke microservice yang sesuai dinamakan...", o: ["API Gateway", "Load Balancer", "Reverse Proxy", "Message Broker", "Database Cluster"], c: 0, exp: "API Gateway menangani routing, otentikasi, dan rate limiting terpusat bagi seluruh microservices." },
  { cat: "Web Dev Lanjutan", q: "Teknik menyimpan hasil query API yang sering diakses di memori cepat (seperti Redis) untuk mempercepat response time dinamakan...", o: ["API Caching", "Database Indexing", "Connection Pooling", "Load Balancing", "Sharding"], c: 0, exp: "API Caching menghindari pemrosesan/query berulang yang berat ke database utama." },
  { cat: "Web Dev Lanjutan", q: "Metode autentikasi API di mana client mengirimkan username dan password yang di-encode Base64 pada header `Authorization: Basic ...` dinamakan...", o: ["Bearer Auth", "Basic Authentication", "API Key Auth", "OAuth 2.0", "Digest Auth"], c: 1, exp: "Basic Auth mengirim kredensial Base64 `user:pass` pada header Authorization." },
  { cat: "Web Dev Lanjutan", q: "Manakah perbedaan utama arsitektur REST API dan GraphQL?", o: ["REST API memiliki multiple fixed endpoint untuk setiap resource, sedangkan GraphQL memiliki 1 single endpoint di mana client bisa meminta persis bidang data yang dibutuhkan", "GraphQL lebih lambat", "REST tidak didukung JSON", "GraphQL khusus PHP", "Keduanya persis sama"], c: 0, exp: "GraphQL mengeliminasi over-fetching dan under-fetching data dengan 1 single endpoint kustom query." },
  { cat: "Web Dev Lanjutan", q: "Istilah 'Over-fetching' dalam pengonsumsian REST API berarti...", o: ["Client menerima terlalu BANYAK data yang tidak dibutuhkan dari endpoint API", "Client kurang menerima data", "Request gagal karena timeout", "Server kehabisan memori", "Format JSON rusak"], c: 0, exp: "Over-fetching terjadi saat API mengembalikan objek raksasa padahal client hanya butuh 1 atribut nama." },
  { cat: "Web Dev Lanjutan", q: "Istilah 'Under-fetching' dalam pengonsumsian REST API berarti...", o: ["Satu request API tidak memberikan data yang cukup sehingga client terpaksa melakukan MULTIPLE REQUEST berulang ke beberapa endpoint berbeda", "Data yang dikirim terlalu besar", "Database crash", "Token kadaluwarsa", "Response berstatus 200"], c: 0, exp: "Under-fetching memaksa client memanggil endpoint `/users/1`, lalu `/users/1/posts`, lalu `/users/1/comments`." },
  { cat: "Web Dev Lanjutan", q: "Di Node.js Express, jika fungsi middleware tidak memanggil `next()` dan tidak mengembalikan `res.send()`, apa yang terjadi pada request client?", o: ["Request akan menggantung (hang / timeout) selamanya!", "Express otomatis me-return 200 OK", "Server akan crash", "Halaman otomatis dikosongkan", "Database terhapus"], c: 0, exp: "Tanpa `next()` atau pemutusan response, alur execution pipeline Express berhenti menggantung." },
  { cat: "Web Dev Lanjutan", q: "Apa kegunaan dari Refresh Token dalam sistem autentikasi berbasis JWT?", o: ["Memungkinkan client mendapatkan Access Token baru tanpa harus meminta pengguna memasukkan ulang password saat Access Token expired", "Mengganti password pengguna", "Menghapus cookie", "Membuat token berukuran 0", "Menyimpan data di server"], c: 0, exp: "Refresh Token berumur panjang digunakan untuk me-issue Access Token baru yang berumur pendek secara aman." },
  { cat: "Web Dev Lanjutan", q: "Serangan keamanan Cross-Site Request Forgery (CSRF) memanfaatkan fakta bahwa...", o: ["Browser otomatis menyertakan Cookie session domain target pada setiap request yang dipicu oleh situs jebakan pihak ketiga", "Password tersimpan polos", "Server tidak memiliki HTTPS", "Database menggunakan MySQL", "JSON berukuran besar"], c: 0, exp: "CSRF memanfaatkan kepercayaan server terhadap cookie yang dikirimkan otomatis oleh browser." },
  { cat: "Web Dev Lanjutan", q: "Untuk menangani operasi asynchronous dalam jumlah banyak secara SEJAJAR (paralel) dan menunggu semuanya tuntas di JS, kita menggunakan...", o: ["Promise.all([p1, p2, p3])", "Promise.race()", "for loop biasa", "setInterval()", "async step()"], c: 0, exp: "`Promise.all()` mengeksekusi sekumpulan Promise secara paralel dan me-resolve saat semuanya selesai." },
  { cat: "Web Dev Lanjutan", q: "Jika salah satu Promise di dalam `Promise.all()` mengalami rejection (error), apa yang terjadi?", o: ["`Promise.all()` langsung me-reject seketika dengan error dari Promise yang gagal tersebut (Short-circuit on failure)", "Promise lain tetap ditunggu sampai selesai", "Error diabaikan", "Me-return array kosong", "Program crash total"], c: 0, exp: "`Promise.all` menganut sifat fail-fast; jika 1 gagal, seluruh Promise.all ikut rejected." },

  // HOTS (46-60) - Security Best Practices, Scalability, Distributed Tracing, Edge Functions
  { cat: "Web Dev Lanjutan", q: "Mengapa menyimpan Access Token JWT di `localStorage` browser berisiko dari sudut pandang Keamanan Perangkat Lunak?", o: ["Skrip jahat yang berhasil disuntikkan via serangan XSS dapat dengan mudah membaca `localStorage.getItem('jwt')` dan mencuri akun pengguna!", "LocalStorage mudah penuh", "Token otomatis terhapus", "Server tidak bisa membaca LocalStorage", "LocalStorage membuat web lambat"], c: 0, exp: "LocalStorage rentan diakses oleh skrip XSS. Penyimpanan paling aman untuk token sensitive adalah `HttpOnly, Secure Cookie`." },
  { cat: "Web Dev Lanjutan", q: "Bagaimana cara kerja metode HTTP Preflight Request (`OPTIONS`) pada CORS?", o: ["Browser secara otomatis mengirimkan request `OPTIONS` ke server terlebih dahulu untuk memeriksa apakah domain client diizinkan sebelum mengirim request utama (seperti POST/DELETE dengan custom header)", "Server mematikan koneksi", "Client menghapus cache", "Browser mengompres data", "Database mengunci tabel"], c: 0, exp: "Browser mengirim Preflight OPTIONS untuk mengonfirmasi izin CORS sebelum mengeksekusi request berisiko." },
  { cat: "Web Dev Lanjutan", q: "Di Node.js, jika terjadi unhandled Promise rejection (`process.on('unhandledRejection')`), tindakan terbaik bagi server production adalah...", o: ["Mencatat log error dan melakukan Graceful Shutdown pada proses server agar tidak menyisakan state corrupt", "Mengabaikan error", "Mengirim email ke user", "Menghapus file database", "Me-restart server tanpa log"], c: 0, exp: "Unhandled rejection bisa membuat state aplikasi terdistorsi. Graceful shutdown + process manager (PM2/K8s) merekomendasikan restart bersih." },
  { cat: "Web Dev Lanjutan", q: "Tracing Express Middleware Chain:\n`app.use((req, res, next) => { req.user = 'Admin'; next(); });` \n`app.get('/dashboard', (req, res) => { res.send(req.user); });` \nHasil response saat GET `/dashboard` adalah...", o: ["\"Admin\"", "undefined", "Error req.user not found", "404 Not Found", "500 Server Error"], c: 0, exp: "Middleware menambah properti `user` pada objek `req`, yang lalu bisa dibaca oleh route handler berikutnya." },
  { cat: "Web Dev Lanjutan", q: "Dalam arsitektur Serverless (seperti Vercel Functions / AWS Lambda), tantangan utama 'Cold Start' terjadi karena...", o: ["Serverless container harus diinstansiasi dan dinyalakan dari awal saat ada request pertama setelah periode tidak aktif, menyebabkan latency ekstra pada request pertama", "Serverless memakan listrik mahal", "Serverless tidak mendukung JS", "Database terhapus saat idle", "Koneksi internet terputus"], c: 0, exp: "Cold start adalah waktu booting container baru saat menampung request pertama setelah idle." },
  { cat: "Web Dev Lanjutan", q: "Strategi penanganan masalah 'Cold Start' dan eksekusi jaringan ultra-cepat pada arsitektur web modern adalah dengan memanfaatkan...", o: ["Edge Network / Edge Functions (menjalankan skrip serverless di CDN node terdekat dengan lokasi fisik pengguna)", "Membuat server fisik sendiri", "Menggunakan HTTP/1.0", "Menghapus backend", "Menggunakan database MySQL lokal"], c: 0, exp: "Edge Runtime mengeksekusi kode di PoP CDN terdekat dari posisi geografis client untuk mengeliminasi latency." },
  { cat: "Web Dev Lanjutan", q: "Perbedaan utama `Promise.allSettled()` dibanding `Promise.all()` adalah...", o: ["`Promise.allSettled()` selalu menunggu SELURUH Promise tuntas (baik resolved maupun rejected) dan me-return status tiap promise tanpa short-circuit error", "allSettled lebih lambat", "allSettled khusus string", "allSettled otomatis me-retry error", "Keduanya persis sama"], c: 0, exp: "`Promise.allSettled` tidak membatalkan eksekusi jika ada Promise yang rejected." },
  { cat: "Web Dev Lanjutan", q: "Dalam enkripsi autentikasi password pengguna di database backend, penggunaan algoritma Hash bertipe 'Bcrypt' atau 'Argon2' lebih disarankan dibanding MD5/SHA256 karena...", o: ["Bcrypt menggunakan teknik Salting otomatis dan faktor kerja (Work Factor / Cost Factor) yang lambat secara sengaja untuk menahan serangan Brute-Force & Rainbow Table", "Bcrypt bisa didekripsi kembali", "MD5 terlalu panjang", "Bcrypt dibuat oleh Google", "Bcrypt tidak butuh memori"], c: 0, exp: "Bcrypt dirancang slow-hash + salt untuk mengamankan password dari cracking GPU modern." },
  { cat: "Web Dev Lanjutan", q: "Apa yang dimaksud dengan 'Idempotent' pada metode HTTP?", o: ["Panggilan metode tersebut berkali-kali dengan payload yang sama akan menghasilkan EFEK STATE SERVER YANG SAMA seperti dipanggil 1 kali", "Request yang sangat cepat", "Request yang dienkripsi", "Request tanpa header", "Request yang selalu me-return 404"], c: 0, exp: "GET, PUT, DELETE bersifat Idempotent (1x atau 100x dipanggil, efek akhir di server sama). POST TIDAK idempotent." },
  { cat: "Web Dev Lanjutan", q: "Mengapa metode HTTP POST dikatakan TIDAK Idempotent?", o: ["Memanggil POST 5 kali dengan data yang sama akan menghasilkan 5 record data baru yang berbeda di database!", "POST tidak mendukung JSON", "POST hanya untuk membaca data", "POST tidak punya header", "POST selalu error"], c: 0, exp: "Setiap eksekusi POST menciptakan resource baru secara independen." },
  { cat: "Web Dev Lanjutan", q: "Dalam arsitektur API, istilah 'Payload' merujuk pada...", o: ["Data murni yang dikirimkan di dalam body HTTP request atau response", "Header rahasia server", "Nama domain server", "Status code HTTP", "File gambar CSS"], c: 0, exp: "Payload adalah bagian data utama dari paket transaksi HTTP." },
  { cat: "Web Dev Lanjutan", q: "Untuk menangani beban trafik HTTP super besar pada backend, teknik 'Load Balancing' bertugas untuk...", o: ["Membagi dan mendistribusikan lalu lintas incoming request secara merata ke beberapa instance server backend", "Mempercepat koding JS", "Mengompres file HTML", "Menghapus database", "Mengacak IP user"], c: 0, exp: "Load Balancer membagikan lalu lintas ke kluster server agar tidak ada 1 server yang overload." },
  { cat: "Web Dev Lanjutan", q: "Tracing Async Error Handling:\n`async function test() {\n  try {\n    return await Promise.reject('Gagal');\n  } catch(e) {\n    return 'Ditangkap';\n  }\n}`\nHasil kembalian fungsi `test()` jika di-await adalah...", o: ["\"Ditangkap\"", "Uncaught Rejection \"Gagal\"", "undefined", "null", "Error"], c: 0, exp: "Karena `await` digunakan di dalam `try`, rejebakan rejection masuk ke blok `catch` dan me-return \"Ditangkap\"." },
  { cat: "Web Dev Lanjutan", q: "Atribut cookie `Secure` memberitahu browser untuk...", o: ["HANYA mengirimkan cookie jika koneksi menggunakan protokol terenkripsi HTTPS", "Menghapus cookie saat browser ditutup", "Menyimpan cookie di LocalStorage", "Mencegah XSS", "Mengompres isi cookie"], c: 0, exp: "Atribut `Secure` menjamin cookie tidak pernah terartikulasi lewat jalur HTTP plaintext." },
  { cat: "Web Dev Lanjutan", q: "Dalam standar REST API, URI endpoint yang baik harus menggunakan kata benda jamak (Plural Noun). Manakah contoh rancangan URI REST API yang PALING STANDAR?", o: ["GET /api/v1/get-all-users", "GET /api/v1/users", "POST /api/v1/createUserData", "FETCH /api/v1/userList", "GET /api/v1/getUserById?id=1"], c: 1, exp: "REST API baku menggunakan kata benda jamak (`GET /users`) tanpa kata kerja di URL path." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-06-web-backend.json', output);
console.log('Done generating 60 Pertemuan 6 (Web Development Lanjutan & REST API) questions with 5 options');
