const fs = require('fs');

const questions = [
  // LOTS (1-15) - SDLC Models (Waterfall, Agile, Scrum, Kanban), Testing types, Software Engineering Economics
  { cat: "SDLC & Manajemen Agile", q: "Siklus hidup pengembangan perangkat lunak yang terstruktur mulai dari analisis, desain, pengodean, pengujian, hingga pemeliharaan dinamakan...", o: ["SDLC (Software Development Life Cycle)", "Agile Manifesto", "UML Lifecycle", "DevOps Loop", "Scrum Framework"], c: 0, exp: "SDLC adalah kerangka kerja proses pengembangan perangkat lunak dari awal hingga akhir." },
  { cat: "SDLC & Manajemen Agile", q: "Model SDLC klasik sekuensial linier di mana setiap fase harus selesai 100% sebelum dapat berlanjut ke fase berikutnya dinamakan...", o: ["Waterfall Model", "Agile Model", "Scrum", "Kanban", "Extreme Programming (XP)"], c: 0, exp: "Waterfall adalah model SDLC linier sekuensial tradisional (seperti air terjun)." },
  { cat: "SDLC & Manajemen Agile", q: "Pendekatan pengembangan perangkat lunak yang berfokus pada iterasi cepat, adaptabilitas terhadap perubahan, dan kolaborasi dinamakan...", o: ["Agile Methodology", "Waterfall Model", "V-Model", "Spiral Model", "Big Bang Model"], c: 0, exp: "Agile menekankan fleksibilitas, pengiriman produk bertahap, dan kolaborasi erat." },
  { cat: "SDLC & Manajemen Agile", q: "Kerangka kerja Agile paling populer yang menggunakan siklus waktu kerja pendek (Sprint) berdurasi 1-4 minggu dinamakan...", o: ["Scrum", "Waterfall", "V-Model", "Spiral", "PRINCE2"], c: 0, exp: "Scrum adalah framework Agile iteratif berbasis time-boxed Sprint." },
  { cat: "SDLC & Manajemen Agile", q: "Metode manajemen visual Agile yang menggunakan papan kartu (Board) untuk membatasi Work In Progress (WIP) dinamakan...", o: ["Kanban", "Scrum", "Waterfall", "XP", "RAD"], c: 0, exp: "Kanban berfokus pada visualisasi aliran kerja papan kartu dan pembatasan WIP." },
  { cat: "SDLC & Manajemen Agile", q: "Di dalam tim Scrum, peran yang bertanggung jawab memaksimalkan nilai produk dan mengelola daftar keinginan fitur (Product Backlog) adalah...", o: ["Product Owner (PO)", "Scrum Master (SM)", "Development Team", "Project Manager", "QA Engineer"], c: 0, exp: "Product Owner memiliki visi produk dan mengelola skala prioritas Product Backlog." },
  { cat: "SDLC & Manajemen Agile", q: "Di dalam tim Scrum, peran yang bertindak sebagai fasilitator, pelatih proses, dan penghilang hambatan (impediments) bagi tim adalah...", o: ["Scrum Master (SM)", "Product Owner", "Software Architect", "Tech Lead", "Client"], c: 0, exp: "Scrum Master menjaga penerapan proses Scrum dan membantu tim mengatasi hambatan." },
  { cat: "SDLC & Manajemen Agile", q: "Rapat harian singkat (15 menit) dalam Scrum di mana anggota tim saling berbagi apa yang dikerjakan kemarin, hari ini, dan kendala dinamakan...", o: ["Daily Standup / Daily Scrum", "Sprint Planning", "Sprint Review", "Sprint Retrospective", "Backlog Refinement"], c: 0, exp: "Daily Standup adalah rapat sinkronisasi harian 15 menit." },
  { cat: "SDLC & Manajemen Agile", q: "Rapat di akhir Sprint di mana tim Scrum menunjukkan demo hasil fitur teruji (Increment) kepada pemangku kepentingan dinamakan...", o: ["Sprint Review", "Sprint Retrospective", "Sprint Planning", "Daily Scrum", "Refinement"], c: 0, exp: "Sprint Review menyajikan inspeksi demo hasil kerja Increment produk kepada stakeholder." },
  { cat: "SDLC & Manajemen Agile", q: "Rapat di akhir Sprint di mana internal tim Scrum melakukan refleksi terhadap proses kerja mereka untuk perbaikan berkelanjutan dinamakan...", o: ["Sprint Retrospective", "Sprint Review", "Sprint Planning", "Daily Standup", "Demo"], c: 0, exp: "Sprint Retrospective mengevaluasi proses, komunikasi, dan perbaikan tim untuk Sprint berikutnya." },
  { cat: "SDLC & Manajemen Agile", q: "Pengujian perangkat lunak yang berfokus pada pengujian komponen fungsi terkecil (seperti fungsi atau method) secara terisolasi dinamakan...", o: ["Unit Testing", "Integration Testing", "System Testing", "Acceptance Testing", "Regression Testing"], c: 0, exp: "Unit Testing menguji unit fungsi/class paling dasar terisolasi." },
  { cat: "SDLC & Manajemen Agile", q: "Pengujian untuk memverifikasi bahwa beberapa modul/komponen dapat bekerja sama dengan benar saat dihubungkan dinamakan...", o: ["Integration Testing", "Unit Testing", "Smoke Testing", "Usability Testing", "Alpha Testing"], c: 0, exp: "Integration Testing menguji antarmuka dan interaksi antar modul." },
  { cat: "SDLC & Manajemen Agile", q: "Pengujian akhir yang dilakukan oleh pengguna akhir (End-User) atau klien untuk memastikan aplikasi memenuhi kebutuhan bisnis dinamakan...", o: ["User Acceptance Testing (UAT)", "Unit Testing", "Integration Testing", "Performance Testing", "Static Testing"], c: 0, exp: "UAT menguji kesiapan aplikasi dari sudut pandang penerimaan pengguna bisnis." },
  { cat: "SDLC & Manajemen Agile", q: "Pengujian ulang yang dilakukan setelah adanya perbaikan bug atau penambahan fitur baru untuk memastikan kode baru tidak merusak fitur lama dinamakan...", o: ["Regression Testing", "Unit Testing", "Stress Testing", "Usability Testing", "Penetration Testing"], c: 0, exp: "Regression Testing mencegah munculnya efek samping (regresi) pada fitur yang sudah ada." },
  { cat: "SDLC & Manajemen Agile", q: "Dalam pengembangan Agile, dokumen cerita singkat yang menggambarkan kebutuhan fitur dari perspektif pengguna ('As a [role], I want [goal], so that [benefit]') dinamakan...", o: ["User Story", "Use Case", "SRS Document", "Test Case", "PRD"], c: 0, exp: "User Story mengekspresikan kebutuhan fitur dari sudut pandang pemakai." },

  // MOTS (16-30) - Agile Metrics (Velocity, Burndown Chart), TDD, Refactoring, Software Quality (ISO 25010)
  { cat: "SDLC & Manajemen Agile", q: "Grafik visual dalam Scrum yang menampilkan sisa jumlah pekerjaan (Story Points) terhadap sisa waktu dalam satu Sprint dinamakan...", o: ["Burndown Chart", "Burnup Chart", "Gantt Chart", "Control Chart", "Pareto Chart"], c: 0, exp: "Burndown Chart melacak penurunan sisa pekerjaan menuju angka nol di akhir Sprint." },
  { cat: "SDLC & Manajemen Agile", q: "Metrik dalam Scrum yang mengukur jumlah rata-rata unit pekerjaan (Story Points) yang berhasil diselesaikan oleh tim dalam satu Sprint dinamakan...", o: ["Team Velocity", "Cycle Time", "Lead Time", "Throughput", "Capacity"], c: 0, exp: "Velocity mengukur kecepatan rata-rata estimasi penyelesaian Story Points tim per Sprint." },
  { cat: "SDLC & Manajemen Agile", q: "Metodologi pengembangan di mana pengembang MENULIS TEST CASE TERLEBIH DAHULU sebelum menuliskan kode implementasi dinamakan...", o: ["Test-Driven Development (TDD)", "Behavior-Driven Development (BDD)", "Domain-Driven Design (DDD)", "Extreme Programming", "Waterfall"], c: 0, exp: "TDD mengikuti alur: Red (Tulis Test Gagal) -> Green (Tulis Kode Lolos Test) -> Refactor." },
  { cat: "SDLC & Manajemen Agile", q: "Siklus 3 langkah berulang dalam praktik Test-Driven Development (TDD) adalah...", o: ["Red -> Green -> Refactor", "Plan -> Code -> Test", "Design -> Build -> Deploy", "Write -> Run -> Fix", "Compile -> Test -> Ship"], c: 0, exp: "TDD Cycle: Red (Test gagal) -> Green (Test lulus) -> Refactor (Pembersihan kode)." },
  { cat: "SDLC & Manajemen Agile", q: "Proses merapikan dan merestrukturisasi kode internal tanpa mengubah perilaku eksternal aplikasi dinamakan...", o: ["Refactoring", "Debugging", "Re-engineering", "Re-compiling", "Deobfuscation"], c: 0, exp: "Refactoring meningkatkan keterbacaan & struktur kode tanpa mengubah fungsionalitasnya." },
  { cat: "SDLC & Manajemen Agile", q: "Biaya implisit jangka panjang yang muncul akibat memilih solusi koding yang cepat & kotor (*quick and dirty*) daripada solusi rapi terstruktur dinamakan...", o: ["Technical Debt (Hutang Teknis)", "Financial Loss", "Code Smells", "Software Rot", "Bug Liability"], c: 0, exp: "Technical Debt adalah dampak akumulasi koding asal-asalan yang membebankan pemeliharaan di masa depan." },
  { cat: "SDLC & Manajemen Agile", q: "Istilah untuk gejala-gejala pada source code yang mengindikasikan adanya masalah struktur atau keburukan desain (misal: method terlalu panjang) dinamakan...", o: ["Code Smells", "Bug", "Syntax Error", "Exception", "Technical Debt"], c: 0, exp: "Code Smells adalah penanda keburukan desain yang membutuhkan refactoring." },
  { cat: "SDLC & Manajemen Agile", q: "Estimasi relatif yang digunakan oleh tim Agile untuk mengukur tingkat kesulitan dan kompleksitas sebuah User Story dinamakan...", o: ["Story Points", "Man-Hours", "Function Points", "Lines of Code (LOC)", "Task Duration"], c: 0, exp: "Story Points mengukur kompleksitas relatif (biasanya berbasis deret Fibonacci: 1, 2, 3, 5, 8...)." },
  { cat: "SDLC & Manajemen Agile", q: "Teknik estimasi tim Agile menggunakan kartu bernomor deret Fibonacci untuk menyepakati bobot Story Points secara jujur dinamakan...", o: ["Planning Poker", "Delphi Technique", "PERT Estimasi", "Gantt Planning", "Scrum Cards"], c: 0, exp: "Planning Poker menghindari bias pengaruh pendapat senior saat estimasi tim." },
  { cat: "SDLC & Manajemen Agile", q: "Dalam standar kualitas perangkat lunak ISO/IEC 25010, kemampuan aplikasi untuk pulih dan berfungsi kembali saat terjadi kesalahan dinamakan...", o: ["Reliability (Keandalan)", "Maintainability", "Usability", "Portability", "Efficiency"], c: 0, exp: "Reliability mengukur keandalan dan tingkat resiliensi aplikasi terhadap kesalahan." },
  { cat: "SDLC & Manajemen Agile", q: "Kemampuan kode perangkat lunak untuk mudah dimodifikasi, diperbaiki, dan ditingkatkan di masa mendatang dinamakan...", o: ["Maintainability (Keterpeliharaan)", "Usability", "Portability", "Reusability", "Compatibility"], c: 0, exp: "Maintainability adalah kemudahan kode untuk dirawat dan diperbaiki." },
  { cat: "SDLC & Manajemen Agile", q: "Kemampuan aplikasi untuk dijalankan pada berbagai lingkungan sistem operasi dan perangkat keras yang berbeda dinamakan...", o: ["Portability (Portabilitas)", "Usability", "Efficiency", "Security", "Reliability"], c: 0, exp: "Portability mengukur kemudahan aplikasi dipindahkan ke platform lain." },
  { cat: "SDLC & Manajemen Agile", q: "Batas waktu kerja yang kaku dan tidak boleh diperpanjang pada siklus Sprint dalam Scrum dinamakan...", o: ["Timeboxing", "Deadline", "Milestone", "Sprint Freeze", "Grace Period"], c: 0, exp: "Timeboxing menetapkan batas durasi maksimal yang tidak boleh molor." },
  { cat: "SDLC & Manajemen Agile", q: "Model SDLC V-Model adalah variasi dari Waterfall di mana...", o: ["Setiap fase pengembangan di sisi kiri dipasangkan secara sejajar dengan fase pengujian (testing) yang sesuai di sisi kanan", "Pengembangan tanpa testing", "Semua fase dilakukan acak", "Khusus aplikasi AI", "Sama persis Scrum"], c: 0, exp: "V-Model menghubungkan setiap tahap verifikasi (kiri) dengan tahap validasi testing (kanan)." },
  { cat: "SDLC & Manajemen Agile", q: "Model SDLC Spiral sangat direkomendasikan untuk proyek perangkat lunak skala raksasa yang membutuhkan...", o: ["Analisis & Manajemen Risiko (Risk Management) secara berulang di setiap iterasi spiral", "Biaya paling murah", "Waktu 1 hari tuntas", "Tanpa dokumentasi", "Hanya 1 pengembang"], c: 0, exp: "Spiral Model sangat berfokus pada analisis dan mitigasi risiko berulang." }
];

let finalOutput = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  finalOutput += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) finalOutput += ',\n';
});
finalOutput += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-10-tryout-final.json', finalOutput);
console.log('Done generating 60 Pertemuan 10 (SDLC & Manajemen Proyek Agile) questions with 5 options');
