const fs = require('fs');

const questions = [
  // LOTS (1-15) - Konsep RDBMS, DDL/DML/DCL/TCL, Primary/Foreign Key, Normalisasi dasar
  { cat: "Basis Data & SQL", q: "Sistem perangkat lunak yang digunakan untuk mengelola dan memanipulasi basis data relasional dinamakan...", o: ["DBMS / RDBMS", "Operating System", "IDE Pemrograman", "Web Server", "Compiler"], c: 0, exp: "RDBMS (Relational Database Management System) adalah software pengelola basis data relasional." },
  { cat: "Basis Data & SQL", q: "Atribut atau kolom dalam tabel yang unik dan digunakan untuk mengidentifikasi setiap baris (record) secara spesifik dinamakan...", o: ["Foreign Key", "Primary Key", "Super Key", "Candidate Key", "Alternate Key"], c: 1, exp: "Primary Key identik sebagai pengenal unik yang tidak boleh bernilai NULL dan tidak boleh ganda." },
  { cat: "Basis Data & SQL", q: "Atribut pada sebuah tabel yang merujuk pada Primary Key tabel lain untuk membentuk hubungan/relasi antar tabel dinamakan...", o: ["Primary Key", "Foreign Key", "Unique Key", "Composite Key", "Surrogate Key"], c: 1, exp: "Foreign Key (Kunci Tamu) menciptakan relasi antar tabel dengan merujuk ke Primary Key tabel induk." },
  { cat: "Basis Data & SQL", q: "Kelompok perintah SQL yang digunakan untuk mendefinisikan struktur database seperti membuat, mengubah, dan menghapus tabel adalah...", o: ["DML (Data Manipulation Language)", "DDL (Data Definition Language)", "DCL (Data Control Language)", "TCL (Transaction Control Language)", "DQL (Data Query Language)"], c: 1, exp: "DDL mencakup perintah struktur database seperti CREATE, ALTER, DROP, TRUNCATE." },
  { cat: "Basis Data & SQL", q: "Manakah yang merupakan contoh perintah SQL kategori DML (Data Manipulation Language)?", o: ["CREATE TABLE", "ALTER TABLE", "INSERT INTO", "DROP DATABASE", "GRANT ALL"], c: 2, exp: "DML digunakan untuk manipulasi isi baris data: INSERT, UPDATE, DELETE, SELECT." },
  { cat: "Basis Data & SQL", q: "Perintah SQL yang digunakan untuk mengambil data dari satu atau beberapa tabel adalah...", o: ["GET", "FETCH", "SELECT", "READ", "EXTRACT"], c: 2, exp: "Perintah SELECT adalah standar SQL untuk melakukan query pengambilan data." },
  { cat: "Basis Data & SQL", q: "Perintah DDL yang digunakan untuk MENULIS/MEMBUAT struktur tabel baru adalah...", o: ["ADD TABLE", "NEW TABLE", "CREATE TABLE", "MAKE TABLE", "INSERT TABLE"], c: 2, exp: "CREATE TABLE adalah sintaks baku DDL untuk pembuatan tabel baru." },
  { cat: "Basis Data & SQL", q: "Perintah SQL yang digunakan untuk memperbarui isi data baris yang sudah ada pada tabel adalah...", o: ["CHANGE", "MODIFY", "UPDATE", "EDIT", "REPLACE"], c: 2, exp: "UPDATE digunakan untuk mengubah isi record data yang ada di tabel." },
  { cat: "Basis Data & SQL", q: "Perintah SQL yang digunakan untuk menghapus baris data tertentu dari sebuah tabel adalah...", o: ["REMOVE", "DROP", "DELETE", "TRUNCATE", "CLEAR"], c: 2, exp: "DELETE digunakan untuk menghapus baris data (record). DROP untuk menghapus tabel/database." },
  { cat: "Basis Data & SQL", q: "Perintah DDL yang menghapus SELURUH ISI BARIS data pada tabel seketika sekaligus me-reset auto-increment tanpa menghapus struktur tabelnya adalah...", o: ["DELETE FROM", "DROP TABLE", "TRUNCATE TABLE", "CLEAR TABLE", "REMOVE TABLE"], c: 2, exp: "TRUNCATE menghapus seluruh baris data secara cepat dan me-reset struktur urutan id." },
  { cat: "Basis Data & SQL", q: "Proses pengorganisasian data dalam database untuk mengurangi redundansi (penumpukan data) dan ketergantungan data yang anomali dinamakan...", o: ["Denormalisasi", "Normalisasi", "Indexing", "Migrasi", "Backup"], c: 1, exp: "Normalisasi adalah teknik perancangan database untuk menghilangkan redundansi data." },
  { cat: "Basis Data & SQL", q: "Syarat utama sebuah tabel memenuhi Bentuk Normal Pertama (1NF) adalah...", o: ["Tidak ada ketergantungan transitif", "Setiap kolom bernilai atomik (tidak ada multivalue/repeating group)", "Sudah memiliki Foreign Key", "Harus di-join dengan tabel lain", "Menggunakan tipe data integer"], c: 1, exp: "1NF mengharuskan setiap sel data bersifat atomik (tunggal, tidak bernilai ganda dalam 1 kolom)." },
  { cat: "Basis Data & SQL", q: "Perintah DCL yang digunakan untuk memberikan hak akses database kepada pengguna tertentu adalah...", o: ["REVOKE", "GRANT", "ALLOW", "PERMIT", "GIVE"], c: 1, exp: "GRANT memberikan izin hak akses (privileges) pengguna." },
  { cat: "Basis Data & SQL", q: "Klausul SQL yang digunakan untuk mengurutkan hasil query SELECT berdasarkan kolom tertentu adalah...", o: ["GROUP BY", "SORT BY", "ORDER BY", "ARRANGE BY", "ALIGN BY"], c: 2, exp: "ORDER BY digunakan untuk mengurutkan data (ASC / DESC)." },
  { cat: "Basis Data & SQL", q: "Nilai penanda pada database yang berarti 'data tidak ada' atau 'belum diisi' dinamakan...", o: ["0", "EMPTY", "BLANK", "NULL", "UNDEFINED"], c: 3, exp: "NULL menandakan ketiadaan nilai (absence of value), berbeda dari angka 0 atau string kosong." },

  // MOTS (16-30) - Sintaks SQL JOIN, GROUP BY, HAVING, Aggregate Functions, WHERE vs HAVING
  { cat: "Basis Data & SQL", q: "Fungsi agregat SQL yang digunakan untuk menghitung jumlah total baris data yang memenuhi kriteria adalah...", o: ["SUM()", "COUNT()", "TOTAL()", "MAX()", "AVG()"], c: 1, exp: "COUNT() menghitung banyaknya record/baris data." },
  { cat: "Basis Data & SQL", q: "Fungsi agregat SQL untuk menghitung rata-rata nilai numerik dalam sebuah kolom adalah...", o: ["MEAN()", "AVERAGE()", "AVG()", "SUM()", "MEDIAN()"], c: 2, exp: "AVG() mengembalikan nilai rata-rata aritmatika dari atribut numerik." },
  { cat: "Basis Data & SQL", q: "Jenis JOIN yang mengembalikan SELURUH baris dari tabel kiri dan baris yang cocok dari tabel kanan adalah...", o: ["INNER JOIN", "LEFT (OUTER) JOIN", "RIGHT (OUTER) JOIN", "FULL OUTER JOIN", "CROSS JOIN"], c: 1, exp: "LEFT JOIN mempertahankan seluruh baris dari tabel kiri (left table)." },
  { cat: "Basis Data & SQL", q: "Perbedaan utama klausul WHERE dan HAVING pada SQL adalah...", o: ["WHERE untuk agregat, HAVING untuk filter biasa", "WHERE memfilter baris SEBELUM pengelompokan (grouping), HAVING memfilter SETELAH pengelompokan (GROUP BY)", "WHERE hanya untuk teks, HAVING untuk angka", "WHERE digunakan di DDL, HAVING di DML", "Keduanya identik"], c: 1, exp: "WHERE menyaring record individual sebelum agregasi, HAVING menyaring hasil dari GROUP BY." },
  { cat: "Basis Data & SQL", q: "Manakah query SQL yang benar untuk mengambil data siswa yang namanya diawali huruf 'A'?", o: ["SELECT * FROM siswa WHERE nama = 'A*';", "SELECT * FROM siswa WHERE nama LIKE 'A%';", "SELECT * FROM siswa WHERE nama LIKE '%A';", "SELECT * FROM siswa WHERE nama CONTAINS 'A';", "SELECT * FROM siswa WHERE nama STARTWITH 'A';"], c: 1, exp: "Wildcard `LIKE 'A%'` mencocokkan string yang diawali huruf A." },
  { cat: "Basis Data & SQL", q: "Klausul SQL yang digunakan untuk mengelompokkan baris data yang memiliki nilai sama ke dalam baris ringkasan adalah...", o: ["ORDER BY", "CLUSTER BY", "GROUP BY", "COLLECT BY", "UNION BY"], c: 2, exp: "GROUP BY sering dipadukan dengan fungsi agregat (COUNT, SUM, AVG) untuk merangkum data." },
  { cat: "Basis Data & SQL", q: "Operator SQL yang digunakan untuk mengecek apakah suatu nilai berada di dalam rentang nilai tertentu (misal 10 sampai 50) adalah...", o: ["IN", "BETWEEN", "LIKE", "RANGE", "INSIDE"], c: 1, exp: "BETWEEN min AND max menyaring nilai dalam rentang inklusif." },
  { cat: "Basis Data & SQL", q: "Operator SQL `IN` digunakan untuk...", o: ["Mengecek apakah nilai ada di dalam daftar pilihan (list of values)", "Mencari string substring", "Menghitung total data", "Menggabungkan dua tabel", "Membuat relasi foreign key"], c: 0, exp: "Contoh: `WHERE kelas IN ('XRPL1', 'XRPL2')` mencocokkan nilai dari daftar yang ditentukan." },
  { cat: "Basis Data & SQL", q: "Jika kita ingin menghapus seluruh baris data dari tabel `log_aktivitas` yang berumur lebih dari 30 hari, query yang benar adalah...", o: ["DROP TABLE log_aktivitas WHERE tanggal < 30;", "DELETE FROM log_aktivitas WHERE tanggal < NOW() - INTERVAL 30 DAY;", "TRUNCATE log_aktivitas WHERE tanggal < 30;", "REMOVE FROM log_aktivitas WHERE tanggal < 30;", "ALTER TABLE log_aktivitas DELETE WHERE 30;"], c: 1, exp: "DELETE FROM digunakan dengan klausul WHERE untuk menghapus data spesifik." },
  { cat: "Basis Data & SQL", q: "Manakah sintaks yang BENAR untuk mengubah nama siswa menjadi 'Budi' pada ID 5 di tabel `siswa`?", o: ["UPDATE siswa SET nama = 'Budi' WHERE id = 5;", "CHANGE siswa SET nama = 'Budi' WHERE id = 5;", "MODIFY siswa WHERE id = 5 SET nama = 'Budi';", "UPDATE nama = 'Budi' IN siswa WHERE id = 5;", "REPLACE siswa NAMA = 'Budi' WHERE id = 5;"], c: 0, exp: "Sintaks baku: `UPDATE nama_tabel SET nama_kolom = nilai WHERE kondisi;`." },
  { cat: "Basis Data & SQL", q: "Jenis JOIN yang HANYA mengembalikan baris yang memiliki pasangan nilai cocok di KEDUA tabel dinamakan...", o: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN", "CROSS JOIN"], c: 2, exp: "INNER JOIN hanya mengambil perpotongan (intersection) data yang presisi di kedua tabel." },
  { cat: "Basis Data & SQL", q: "Apa dampak tidak menyertakan klausul `WHERE` pada perintah `UPDATE` atau `DELETE`?", o: ["Error sintaks", "Seluruh baris data pada tabel akan ter-update atau terhapus!", "Perintah dibatalkan sistem", "Hanya baris pertama yang berubah", "Database terunci otomatis"], c: 1, exp: "Tanpa WHERE, perintah UPDATE/DELETE dieksekusi secara masal pada 100% baris di tabel!" },
  { cat: "Basis Data & SQL", q: "Constraint SQL yang memastikan bahwa tidak boleh ada dua baris data yang memiliki nilai sama pada kolom tertentu dinamakan...", o: ["NOT NULL", "CHECK", "UNIQUE", "DEFAULT", "INDEX"], c: 2, exp: "UNIQUE constraint menjamin seluruh nilai dalam kolom berbeda satu sama lain." },
  { cat: "Basis Data & SQL", q: "Syarat sebuah tabel memenuhi Bentuk Normal Kedua (2NF) adalah...", o: ["Sudah memenuhi 1NF dan tidak ada ketergantungan parsial (sebagian) terhadap Primary Key", "Harus memiliki 10 kolom", "Sudah tidak memiliki Foreign Key", "Semua kolom bertipe varchar", "Menggunakan INNER JOIN"], c: 0, exp: "2NF mewajibkan 1NF + setiap atribut non-key bergantung penuh pada seluruh Primary Key." },
  { cat: "Basis Data & SQL", q: "Syarat Bentuk Normal Ketiga (3NF) adalah...", o: ["Memenuhi 2NF dan tidak ada ketergantungan transitif (non-key field menentukan non-key field lain)", "Harus dipisah menjadi 100 tabel", "Memiliki JSON column", "Memakai auto increment", "Dibuat dengan PostgreSQL"], c: 0, exp: "3NF menghilangkan ketergantungan transitif (A -> B -> C)." },

  // MOTS+ (31-45) - Query Kompleks, Subquery, Indexing, Transactions (ACID)
  { cat: "Basis Data & SQL", q: "Empat sifat utama transaksi database yang dikenal dengan istilah ACID adalah singkatan dari...", o: ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Control, Integrity, Data", "Access, Code, Index, Database", "Action, Commit, Insert, Delete", "Authentication, Crypto, Identity, Protection"], c: 0, exp: "ACID: Atomicity (Semua atau Tidak Sama Sekali), Consistency, Isolation, Durability." },
  { cat: "Basis Data & SQL", q: "Sifat 'Atomicity' dalam transaksi database berarti...", o: ["Transaksi dilakukan dalam hitungan nanodetik", "Seluruh rangkaian perintah transaksi berhasil sepenuhnya, atau dibatalkan total jika 1 gagal", "Data disimpan di atomic RAM", "Query hanya boleh 1 baris", "Database terlindung dari peretasan"], c: 1, exp: "Atomicity menganut prinsip All-or-Nothing (Semua tuntas atau Rollback total)." },
  { cat: "Basis Data & SQL", q: "Perintah TCL yang digunakan untuk membatalkan seluruh perubahan transaksi yang belum disimpan permanent adalah...", o: ["COMMIT", "ROLLBACK", "SAVEPOINT", "REVERT", "UNDO"], c: 1, exp: "ROLLBACK membatalkan transaksi dan mengembalikan kondisi data ke Savepoint/State awal." },
  { cat: "Basis Data & SQL", q: "Perintah TCL yang digunakan untuk menyimpan secara permanen perubahan transaksi ke disk database adalah...", o: ["SAVE", "COMMIT", "STORE", "CHECKPOINT", "WRITE"], c: 1, exp: "COMMIT mengunci dan menyimpan permanen seluruh perubahan transaksi." },
  { cat: "Basis Data & SQL", q: "Struktur data indeks (Indexing) pada database digunakan dengan tujuan utama untuk...", o: ["Menghemat kapasitas harddisk", "Mempercepat proses pencarian/query SELECT data", "Mencegah data terhapus", "Membuat tabel rapi", "Menyembunyikan kolom privat"], c: 1, exp: "Database Index (seperti B-Tree) meningkatkan kecepatan query pembacaan SELECT." },
  { cat: "Basis Data & SQL", q: "Apa potensi kerugian dari membuat terlalu banyak Index pada sebuah tabel?", o: ["Ukuran file database membengkak dan memperlambat proses INSERT/UPDATE/DELETE", "Query SELECT menjadi lambat", "Primary key menjadi terhapus", "Database mengalami deadlock", "Data terenkripsi"], c: 0, exp: "Setiap ada INSERT/UPDATE, indeks harus diperbarui ulang, membebankan performa penulisan data." },
  { cat: "Basis Data & SQL", q: "Subquery (Nested Query) adalah...", o: ["Query SELECT yang berada di dalam query SQL lain", "Dua tabel yang digabung tanpa JOIN", "Query yang gagal dieksekusi", "Fungsi JS di dalam SQL", "Database di dalam database"], c: 0, exp: "Subquery adalah query bersarang yang hasilnya digunakan oleh query luar." },
  { cat: "Basis Data & SQL", q: "Klausul `HAVING COUNT(*) > 5` biasanya diletakkan...", o: ["Sebelum WHERE", "Setelah GROUP BY", "Sebelum SELECT", "Di dalam INSERT", "Di akhir DDL"], c: 1, exp: "HAVING menyaring hasil grup, sehingga posisinya setelah `GROUP BY`." },
  { cat: "Basis Data & SQL", q: "Tracing Query: `SELECT kelas, COUNT(*) FROM siswa GROUP BY kelas;`. Hasil dari query ini adalah...", o: ["Daftar nama seluruh siswa", "Jumlah total siswa per kelas", "Nilai rata-rata siswa", "Nama siswa paling pintar", "Daftar kelas yang kosong"], c: 1, exp: "Query mengelompokkan data berdasarkan kelas dan menghitung banyaknya siswa di tiap grup kelas." },
  { cat: "Basis Data & SQL", q: "Apa hasil dari query: `SELECT * FROM produk WHERE harga > 10000 AND (kategori = 'Baju' OR kategori = 'Celana');`?", o: ["Produk harga > 10000 kategori Baju, ATAU semua Celana", "Produk kategori Baju atau Celana yang harganya DI ATAS 10000", "Semua produk baju dan celana", "Produk harga di bawah 10000", "Error sintaks tanda kurung"], c: 1, exp: "Tanda kurung mengelompokkan syarat kategori dulu, lalu di-AND-kan dengan harga > 10000." },
  { cat: "Basis Data & SQL", q: "Jenis relasi antar tabel 'Satu Guru mengajar Banyak Kelas, dan Satu Kelas diajar Banyak Guru' dinamakan...", o: ["One to One (1:1)", "One to Many (1:N)", "Many to Many (N:M)", "Parent to Child", "Self Referencing"], c: 2, exp: "Relasi Banyak ke Banyak (Many to Many) memerlukan tabel pivot / junction table." },
  { cat: "Basis Data & SQL", q: "Untuk merelasikan dua tabel yang memiliki hubungan Many-to-Many (N:M), solusi terbaik adalah...", o: ["Menaruh 10 Foreign Key di tabel pertama", "Membuat Tabel Perantara (Pivot / Junction Table) yang berisi 2 Foreign Key", "Menyimpan data sebagai string dipisah koma", "Menggabungkan dua tabel jadi satu", "Menghapus salah satu tabel"], c: 1, exp: "Junction table memecah relasi N:M menjadi dua relasi 1:N." },
  { cat: "Basis Data & SQL", q: "Klausul `LIMIT 5 OFFSET 10` pada PostgreSQL/MySQL berfungsi untuk...", o: ["Mengambil 5 data pertama", "Mengambil 5 baris data, dengan melompati (skip) 10 baris pertama", "Mengambil data dari id 5 sampai 10", "Membatasi kolom jadi 5", "Menampilkan 15 data"], c: 1, exp: "LIMIT menentukan jumlah baris yang diambil, OFFSET menentukan jumlah baris awal yang dilewati (pagination)." },
  { cat: "Basis Data & SQL", q: "Objek database berupa tabel maya (virtual table) yang hasil datanya berasal dari query SELECT tersimpan dinamakan...", o: ["Stored Procedure", "Trigger", "View", "Index", "Sequence"], c: 2, exp: "View adalah tabel virtual yang menyimpan definisi query SQL untuk menyederhanakan akses data." },
  { cat: "Basis Data & SQL", q: "Blok kode SQL yang otomatis dieksekusi saat terjadi event tertentu (INSERT/UPDATE/DELETE) pada tabel dinamakan...", o: ["Trigger", "Stored Procedure", "Function", "View", "Transaction"], c: 0, exp: "Trigger berjalan otomatis dipicu oleh event DML pada tabel." },

  // HOTS (46-60) - Query Optimization, SQL Injection Defense, Complex Tracing & Normalization Cases
  { cat: "Basis Data & SQL", q: "Teknik peretasan keamanan database di mana penyerang menyisipkan perintah SQL berbahaya lewat form input dinamakan...", o: ["Cross-Site Scripting (XSS)", "SQL Injection (SQLi)", "CSRF", "DDoS", "Buffer Overflow"], c: 1, exp: "SQL Injection mengeksploitasi input user yang tidak di-sanitize untuk memanipulasi query DB." },
  { cat: "Basis Data & SQL", q: "Cara utama paling ampuh bagi pengembang software untuk MENCEGAH SQL Injection adalah...", o: ["Menggunakan Prepared Statement / Parameterized Queries", "Menghapus database", "Menggunakan method GET saja", "Mematikan koneksi internet", "Mengubah nama tabel"], c: 0, exp: "Prepared Statement memisahkan struktur query dengan data parameter sehingga kode SQL tidak bisa disisipi." },
  { cat: "Basis Data & SQL", q: "Tracing Query: `SELECT p.nama, k.nama_kategori FROM produk p LEFT JOIN kategori k ON p.kategori_id = k.id;` Jika ada produk tanpa kategori_id (NULL), apa yang tampil di kolom nama_kategori?", o: ["Baris produk tidak akan muncul sama sekali", "Kolom nama_kategori bernilai NULL", "Error query gagal", "Muncul string 'Kosong'", "Program crash"], c: 1, exp: "LEFT JOIN mempertahankan record tabel kiri (produk); jika tak berpasangan, kolom kanan bernilai NULL." },
  { cat: "Basis Data & SQL", q: "Perhatikan tabel `transaksi` dengan 1 juta baris. Query `SELECT * FROM transaksi WHERE YEAR(tanggal) = 2026;` berjalan lambat padahal kolom `tanggal` sudah di-index. Mengapa?", o: ["Indeks rusak", "Menggunakan fungsi `YEAR()` pada kolom indeks menyebabkan 'Index Scan / Loss' (sargable query terlanggar)", "Tabel terlalu kecil", "WHERE tidak mendukung angka", "Harus pakai DDL"], c: 1, exp: "Membungkus kolom terindeks dengan fungsi mencegah database memanfaatkan indeks (Un-sargable query)." },
  { cat: "Basis Data & SQL", q: "Bagaimana cara memperbaiki query `WHERE YEAR(tanggal) = 2026` agar bisa memanfaatkan indeks tanggal secara maksimal?", o: ["`WHERE tanggal BETWEEN '2026-01-01' AND '2026-12-31'`", "`WHERE tanggal LIKE '%2026%'`", "`WHERE tanggal = 2026`", "`WHERE MONTH(tanggal) = 12`", "`WHERE tanggal IN (2026)`"], c: 0, exp: "Menggunakan perbandingan rentang nilai murni (`BETWEEN`) membuat query bersifat sargable dan cepat." },
  { cat: "Basis Data & SQL", q: "Kondisi persaingan di mana dua transaksi saling menunggu kunci resource milik satu sama lain sehingga keduanya berhenti selamanya disebut...", o: ["Race Condition", "Deadlock", "Livelock", "Starvation", "Dirty Read"], c: 1, exp: "Deadlock terjadi saat Transaksi A kunci X butuh Y, sementara Transaksi B kunci Y butuh X." },
  { cat: "Basis Data & SQL", q: "Dalam isolasi transaksi, membaca data yang sedang diubah oleh transaksi lain yang BELUM di-commit dinamakan...", o: ["Non-Repeatable Read", "Phantom Read", "Dirty Read", "Consistent Read", "Serial Read"], c: 2, exp: "Dirty Read terjadi saat data uncommitted dibaca dan ternyata transaksi asal di-rollback." },
  { cat: "Basis Data & SQL", q: "Kasus Normalisasi: Tabel `Pesanan` memiliki kolom `(NoNota, Tanggal, KodeBarang, NamaBarang, HargaBarang)`. Kolom `NamaBarang` dan `HargaBarang` hanya bergantung pada `KodeBarang`, bukan `NoNota`. Tabel ini melanggar...", o: ["1NF", "2NF (Partial Dependency)", "3NF", "BCNF", "4NF"], c: 1, exp: "Ketergantungan parsial (non-key bergantung pada sebagian composite primary key) melanggar 2NF." },
  { cat: "Basis Data & SQL", q: "Bagaimana solusi normalisasi untuk memecah tabel melanggar 2NF pada kasus pesanan di atas?", o: ["Menggabungkan semua kolom jadi satu", "Memecah menjadi 2 tabel: Tabel `Barang (KodeBarang, NamaBarang, HargaBarang)` dan Tabel `DetailPesanan (NoNota, KodeBarang)`", "Menghapus kolom NoNota", "Mengubah NoNota jadi VARCHAR", "Membuat View saja"], c: 1, exp: "Memisahkan master barang membuang ketergantungan parsial dan memenuhi 2NF." },
  { cat: "Basis Data & SQL", q: "Tracing query agregasi bersarang:\n`SELECT id_pelanggan, SUM(total) FROM pesanan GROUP BY id_pelanggan HAVING SUM(total) > (SELECT AVG(total) FROM pesanan);` Query ini bertujuan untuk...", o: ["Mencari pelanggan dengan belanja rata-rata", "Mencari pelanggan yang total akumulasi belanjaannya melebihi nilai rata-rata per transaksi pesanan", "Mencari pesanan termahal", "Mencari total seluruh pesanan", "Query error karena ada subquery di HAVING"], c: 1, exp: "Query menyaring grup pelanggan yang total belanjanya melampaui rata-rata transaksi umum." },
  { cat: "Basis Data & SQL", q: "Klausul `ON DELETE CASCADE` pada penentuan Foreign Key berarti...", o: ["Jika baris di tabel induk dihapus, baris terkait di tabel anak akan OTOMATIS IKUT TERHAPUS", "Dilarang menghapus data induk", "Baris di tabel anak di-set NULL", "Database akan dikunci", "Indeks terhapus"], c: 0, exp: "CASCADE meneruskan aksi hapus dari parent record ke seluruh child records." },
  { cat: "Basis Data & SQL", q: "Perbedaan `UNION` dan `UNION ALL` saat mengabungkan hasil dua query SELECT adalah...", o: ["UNION menghapus baris duplikat, UNION ALL mempertahankan semua baris (termasuk duplikat)", "UNION ALL lebih lambat", "UNION khusus angka", "UNION ALL untuk tabel terpisah", "Tidak ada bedanya"], c: 0, exp: "UNION melakukan deduplikasi hasil (lebih lambat), sedangkan UNION ALL menggabungkan murni (lebih cepat)." },
  { cat: "Basis Data & SQL", q: "Tracing Window Function: `SELECT nama, gaji, RANK() OVER (ORDER BY gaji DESC) as rangking FROM pegawai;`. Fungsi query ini adalah...", o: ["Mengurutkan nama pegawai secara alfabet", "Memberikan peringkat (rank) gaji pegawai dari tertinggi ke terendah tanpa meng-group baris data", "Menghapus gaji terendah", "Menghitung total gaji", "Query error karena RANK tidak valid"], c: 1, exp: "Window function `RANK() OVER` memberikan peringkat analitis tanpa merusak baris individual." },
  { cat: "Basis Data & SQL", q: "Dalam perancangan NoSQL vs RDBMS, RDBMS lebih direkomendasikan untuk aplikasi yang membutuhkan...", o: ["Skalabilitas horizontal tanpa skema", "Integritas transaksi finansial yang ketat (ACID compliance)", "Penyimpanan dokumen JSON mentah tanpa relasi", "Streaming log suhu IoT per milidetik", "Tidak ada jawaban benar"], c: 1, exp: "RDBMS sangat unggul untuk transaksi finansial/perbankan yang menuntut konsistensi ACID 100%." },
  { cat: "Basis Data & SQL", q: "Tracing Query: `SELECT COUNT(DISTINCT kota) FROM pelanggan;` Jika data kota berisi ['Bandung', 'Jakarta', 'Bandung', NULL, 'Jakarta'], hasilnya adalah...", o: ["5", "3", "2", "4", "Error"], c: 2, exp: "DISTINCT mengambil nilai unik ('Bandung', 'Jakarta') dan mengabaikan NULL. COUNT hasilnya 2." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-03-basis-data-sql.json', output);
console.log('Done generating 60 Pertemuan 3 (Basis Data & SQL) questions with 5 options');
