const fs = require('fs');

const questions = [
  // LOTS (1-15) - Konsep Dasar OOP, Class, Object, Encapsulation, Abstraction, Inheritance, Polymorphism
  { cat: "PBO / OOP", q: "Rancangan atau cetak biru (blueprint) yang mendefinisikan karakteristik dan perilaku dari suatu objek dinamakan...", o: ["Object", "Class", "Method", "Variable", "Interface"], c: 1, exp: "Class adalah cetak biru (blueprint) yang memuat definisi atribut dan method untuk membuat objek." },
  { cat: "PBO / OOP", q: "Hasil instansiasi nyata dari sebuah Class yang memiliki state dan behavior dinamakan...", o: ["Object", "Class", "Function", "Module", "Attribute"], c: 0, exp: "Object adalah wujud nyata (instance) yang dibuat dari sebuah Class." },
  { cat: "PBO / OOP", q: "Pilar OOP yang berfungsi menyembunyikan detail penyimpan data dan hanya menyediakan akses melalui method/getter-setter adalah...", o: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction", "Overloading"], c: 2, exp: "Encapsulation membungkus data (private) dan melindunginya dari akses langsung luar class." },
  { cat: "PBO / OOP", q: "Modifier akses yang membuat variabel atau method HANYA dapat diakses oleh class itu sendiri adalah...", o: ["public", "protected", "private", "default", "static"], c: 2, exp: "Private membatasi akses variabel/method hanya di dalam lingkup class deklarasinya." },
  { cat: "PBO / OOP", q: "Kemampuan suatu kelas untuk menurunkan atribut dan method kepada kelas anaknya (subclass) disebut...", o: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction", "Overriding"], c: 0, exp: "Inheritance (Pewarisan) memungkinkan class anak mewarisi sifat dari class induk (superclass)." },
  { cat: "PBO / OOP", q: "Keyword yang digunakan di Java atau PHP untuk menerapkan Inheritance (pewarisan class) adalah...", o: ["implements", "extends", "inherits", "using", "import"], c: 1, exp: "Keyword `extends` digunakan untuk mewarisi superclass (misal: `class Mobil extends Kendaraan`)." },
  { cat: "PBO / OOP", q: "Pilar OOP yang memungkinkan sebuah method memiliki nama sama namun perilaku/implementasi yang berbeda dinamakan...", o: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction", "Instantiation"], c: 1, exp: "Polymorphism (Banyak Bentuk) memungkinkan method yang sama berprilaku beda pada objek beda." },
  { cat: "PBO / OOP", q: "Method khusus yang otomatis dipanggil saat sebuah Objek pertama kali diinstansiasi dengan keyword `new` adalah...", o: ["Destructor", "Constructor", "Getter", "Setter", "Main Method"], c: 1, exp: "Constructor dipanggil secara otomatis saat pembuatan objek baru untuk inisialisasi state awal." },
  { cat: "PBO / OOP", q: "Dalam bahasa Java atau C#, nama method Constructor HARUS...", o: ["Diawali kata construct", "Sama persis dengan nama Class", "Memiliki return type String", "Bersifat private", "Diakhiri kata Init"], c: 1, exp: "Pada Java/C#, nama constructor wajib sama persis dengan nama Class dan tidak punya tipe kembalian (return type)." },
  { cat: "PBO / OOP", q: "Variabel yang dideklarasikan di dalam lingkup Class tetapi di luar method dinamakan...", o: ["Local Variable", "Instance Variable / Field", "Global Variable", "Parameter Variable", "Static Constant"], c: 1, exp: "Instance variable dideklarasikan di tingkat Class untuk menampung atribut objek." },
  { cat: "PBO / OOP", q: "Keyword yang merujuk pada objek saat ini (current instance) di dalam sebuah method dinamakan...", o: ["super", "this", "parent", "self", "base"], c: 1, exp: "Keyword `this` merujuk pada instance objek yang sedang berjalan." },
  { cat: "PBO / OOP", q: "Modifier akses yang mengizinkan atribut diakses oleh class itu sendiri, subclass (anaknya), dan package yang sama adalah...", o: ["public", "private", "protected", "internal", "final"], c: 2, exp: "Protected mengizinkan akses untuk class itu sendiri, keturunannya (subclass), dan satu package." },
  { cat: "PBO / OOP", q: "Konsep menyembunyikan detail kompleksitas sistem dan hanya menampilkan fungsi pentingnya saja dinamakan...", o: ["Abstraction", "Encapsulation", "Polymorphism", "Inheritance", "Aggregation"], c: 0, exp: "Abstraction memfokuskan pada 'apa yang dilakukan' tanpa membebani pengguna dengan 'bagaimana cara kerjanya'." },
  { cat: "PBO / OOP", q: "Keyword di Java untuk membuat class tidak dapat diwarisi (dijadikan induk) lagi adalah...", o: ["static", "final", "abstract", "const", "void"], c: 1, exp: "Class dengan keyword `final` tidak dapat di-extend oleh class manapun." },
  { cat: "PBO / OOP", q: "Method yang tidak memiliki isi (body) dan HARUS di-override oleh kelas anak non-abstrak dinamakan...", o: ["Static Method", "Abstract Method", "Final Method", "Private Method", "Default Method"], c: 1, exp: "Abstract Method hanya berupa deklarasi tanpa body yang wajib diimplementasikan di subclass." },

  // MOTS (16-30) - Konstruktor, Overloading vs Overriding, Access Modifier, Static vs Instance
  { cat: "PBO / OOP", q: "Membuat dua atau lebih method dalam SATU CLASS yang sama dengan nama persis tetapi beda parameter dinamakan...", o: ["Method Overriding", "Method Overloading", "Method Hiding", "Method Shadowing", "Method Casting"], c: 1, exp: "Overloading terjadi di satu class dengan nama method sama namun beda jumlah/tipe parameternya." },
  { cat: "PBO / OOP", q: "Menuliskan kembali method yang sudah ada di Superclass pada Subclass dengan nama dan parameter persis dinamakan...", o: ["Method Overloading", "Method Overriding", "Method Duplication", "Method Casting", "Method Hiding"], c: 1, exp: "Overriding menimpa implementasi method milik kelas induk pada kelas anak." },
  { cat: "PBO / OOP", q: "Keyword di Java yang digunakan untuk memanggil constructor atau method milik Superclass (kelas induk) adalah...", o: ["this", "super", "parent", "base", "root"], c: 1, exp: "Keyword `super()` memanggil constructor atau method superclass." },
  { cat: "PBO / OOP", q: "Anggota class (variable/method) yang menggunakan modifier `static` berarti...", o: ["Milik objek individu", "Milik Class secara keseluruhan dan tidak perlu instansiasi objek", "Hanya bisa diakses sekali", "Nilainya tidak bisa diubah", "Otomatis terhapus saat app ditutup"], c: 1, exp: "Static member bersifat class-level dan dapat diakses langsung melalui nama Class (contoh: `Math.sqrt()`)." },
  { cat: "PBO / OOP", q: "Perhatikan kode: `Siswa s1 = new Siswa();`. Manakah yang merupakan objek (instance)?", o: ["Siswa", "s1", "new", "Siswa()", "pilihan B dan D"], c: 1, exp: "s1 adalah variabel reference yang menampung instance objek Siswa." },
  { cat: "PBO / OOP", q: "Manakah struktur penulisan Getter method yang paling tepat dalam Java?", o: ["public void getName() { return name; }", "public String getName() { return name; }", "public String setName(String n) { name = n; }", "private String getName() { return name; }", "public static void getName() { return name; }"], c: 1, exp: "Getter bertugas mengembalikan nilai atribut, sehingga tipe kembaliannya harus sesuai tipe data variabel (bukan void)." },
  { cat: "PBO / OOP", q: "Manakah struktur penulisan Setter method yang benar untuk variabel `private int umur;`?", o: ["public int setUmur(int u) { return u; }", "public void setUmur(int u) { this.umur = u; }", "public int getUmur() { return umur; }", "private void setUmur() { umur = 10; }", "public static void setUmur(int u) { umur = u; }"], c: 1, exp: "Setter tidak mengembalikan nilai (return void) dan bertugas mengisi atribut `this.umur = u`." },
  { cat: "PBO / OOP", q: "Sebuah Interface di pemrograman berorientasi objek memuat...", o: ["Hanya atribut konstan dan method abstrak tanpa body", "Method ber-body lengkap", "Hanya private variable", "Hanya constructor default", "Method static saja"], c: 0, exp: "Interface berisi kontrak berupa method-method abstrak tanpa body yang wajib di-implements." },
  { cat: "PBO / OOP", q: "Keyword yang digunakan oleh sebuah Class di Java untuk menerapkan Interface adalah...", o: ["extends", "implements", "uses", "includes", "inherits"], c: 1, exp: "Keyword `implements` digunakan untuk merealisasikan Interface." },
  { cat: "PBO / OOP", q: "Dua buah kelas berhubungan dengan prinsip 'Kucing ADALAH KORBAN/JENIS DARI Hewan'. Hubungan ini menggambarkan...", o: ["Association", "Aggregation", "Inheritance (Is-A relationship)", "Composition (Has-A relationship)", "Dependency"], c: 2, exp: "Inheritance mencerminkan hubungan IS-A (Adalah Jenis Dari)." },
  { cat: "PBO / OOP", q: "Hubungan antara 'Mobil MEMILIKI Mesin' di mana Mesin tidak bisa berdiri sendiri tanpa Mobil dinamakan...", o: ["Inheritance", "Polymorphism", "Composition (Has-A)", "Generalization", "Realization"], c: 2, exp: "Composition adalah bentuk asosiasi kuat (HAS-A) di mana bagian tidak bisa eksis tanpa induknya." },
  { cat: "PBO / OOP", q: "Apa fungsi penanda anotasi `@Override` pada Java?", o: ["Membuka akses private", "Memastikan kompiler mengecek bahwa method benar-benar meng-override method induk", "Mengubah method menjadi static", "Menghapus method induk", "Menghentikan perulangan"], c: 1, exp: "Anotasi `@Override` memberi arahan kompilator untuk memvalidasi kesesuaian signature method turunan." },
  { cat: "PBO / OOP", q: "Jika sebuah Class bersifat `abstract`, maka pernyataan yang BENAR adalah...", o: ["Class tersebut dapat diinstansiasi langsung dengan `new`", "Class tersebut TIDAK DAPAT diinstansiasi secara langsung", "Class tersebut wajib memiliki minimal 10 method", "Class tersebut tidak bisa diturunkan lagi", "Class tersebut bernilai null"], c: 1, exp: "Abstract Class tidak bisa dibuat objeknya secara langsung, melainkan harus diturunkan dulu." },
  { cat: "PBO / OOP", q: "Satu Class dapat me-implements berapa banyak Interface di bahasa Java?", o: ["Hanya 1 Interface", "Maksimal 2 Interface", "Tidak terbatas (multiple interface implementation)", "Harus sama dengan jumlah variabel", "Tidak bisa di-implements"], c: 2, exp: "Java tidak mendukung multiple inheritance pada Class, tetapi mendukung multiple implements pada Interface." },
  { cat: "PBO / OOP", q: "Apa dampak dari penerapan Encapsulation terhadap integritas data sistem?", o: ["Data menjadi lebih lambat dibaca", "Mencegah modifikasi data sembarangan dari pihak luar", "Menghapus semua bug pada kode", "Membuat program berukuran lebih kecil", "Mencegah pembuatan objek baru"], c: 1, exp: "Encapsulation menjaga integritas data dengan membatasi akses ilegal dan memvalidasi setter." },

  // MOTS+ (31-45) - Analisis Snippet Code Java/C++/PHP & Destruktur
  { cat: "PBO / OOP", q: "Perhatikan kode: `class A { static int count = 0; A(){ count++; } }`. Jika kita membuat 3 objek `new A()`, berapa nilai `A.count`?", o: ["0", "1", "2", "3", "Error"], c: 3, exp: "Karena `count` bersifat static (shared), setiap constructor berjalan ia bertambah 1. 3 kali instansiasi = 3." },
  { cat: "PBO / OOP", q: "Perhatikan kode: `class Buku { private String judul; public void setJudul(String j){ judul=j; } }`. Mengapa atribut `judul` dibuat private?", o: ["Agar kode lebih panjang", "Sesuai prinsip Encapsulation agar tidak diakses bebas dari luar", "Agar variabel tidak bisa diubah nilainya", "Wajib menurut aturan kompiler Java", "Agar judul bernilai null"], c: 1, exp: "Private pada atribut adalah penerapan Encapsulation untuk melindungi akses langsung." },
  { cat: "PBO / OOP", q: "Tracing kode Java:\n`class P { void show(){ System.print(\"P\"); } }\nclass Q extends P { void show(){ System.print(\"Q\"); } }\nP obj = new Q(); obj.show();`\nOutputnya adalah...", o: ["P", "Q", "PQ", "Error Kompilasi", "Null"], c: 1, exp: "Karena overriding dan dynamic method dispatch, method milik objek nyata (`new Q()`) yang dieksekusi, cetak 'Q'." },
  { cat: "PBO / OOP", q: "Apa yang terjadi jika variabel `final int MAX = 100;` coba diubah nilainya menjadi `MAX = 200;`?", o: ["Nilainya berubah jadi 200", "Nilainya berubah jadi 150", "Terjadi Compile Error (cannot assign value to final variable)", "Program bluescreen", "Nilainya otomatis di-reset ke 0"], c: 2, exp: "Variabel `final` bernilai konstan dan tidak bisa di-reassign setelah inisialisasi." },
  { cat: "PBO / OOP", q: "Di PHP, sintaks penulisan constructor di dalam Class menggunakan nama fungsi...", o: ["function Constructor()", "function __construct()", "function init()", "function ClassName()", "function _init()"], c: 1, exp: "PHP menggunakan magic method `function __construct()` sebagai konstruktor." },
  { cat: "PBO / OOP", q: "Di C++, destruktor (method pembersih memori) ditandai dengan simbol khusus sebelum nama class, yaitu...", o: ["#ClassName()", "~ClassName()", "*ClassName()", "&ClassName()", "!ClassName()"], c: 1, exp: "C++ menggunakan tilde (`~`) untuk penanda Destructor." },
  { cat: "PBO / OOP", q: "Manakah perbedaan utama antara Abstract Class dan Interface di Java modern?", o: ["Abstract Class bisa memiliki state/field biasa dan constructor, Interface fokus pada kontrak tanpa state", "Interface bisa diinstansiasi dengan new", "Abstract class tidak bisa memiliki method ber-body", "Interface hanya bisa dipakai di C++", "Keduanya tidak ada perbedaan"], c: 0, exp: "Abstract class bisa menyimpan atribut biasa dan constructor, sedangkan Interface berupa murni kontrak behavior." },
  { cat: "PBO / OOP", q: "Perhatikan snippet: `class Kucing { String nama; Kucing(String nama){ this.nama = nama; } }`. Penggunaan `this.nama` bertujuan untuk...", o: ["Memanggil method nama", "Membedakan instance variable `nama` dengan parameter `nama`", "Mengubah nama menjadi static", "Menghapus nilai nama", "Membuat variabel baru"], c: 1, exp: "`this.nama` merujuk ke instance variable untuk menghindari hambatan *shadowing* nama parameter." },
  { cat: "PBO / OOP", q: "Tracing kode Java:\n`class Test { int x = 5; void run(int x) { x = x + 10; } }\nTest t = new Test(); t.run(20); System.print(t.x);`\nHasilnya adalah...", o: ["5", "15", "20", "30", "0"], c: 0, exp: "Di dalam method `run()`, variabel `x` yang ditambah adalah parameter lokal. Instance variable `t.x` tetap 5." },
  { cat: "PBO / OOP", q: "Apa yang dimaksud dengan Upcasting dalam PBO?", o: ["Mengubah objek kelas anak menjadi tipe kelas induknya", "Mengubah variabel int ke String", "Mengubah method private ke public", "Menghapus kelas anak", "Menggandakan instansiasi objek"], c: 0, exp: "Upcasting mengacu pada konversi tipe reference dari subclass ke superclass (contoh: `Animal a = new Dog();`)." },
  { cat: "PBO / OOP", q: "Manakah contoh penerapan Overloading yang valid pada method `hitung`?", o: ["int hitung(int a) dan int hitung(int b)", "int hitung(int a) dan double hitung(int a)", "int hitung(int a) dan int hitung(int a, int b)", "void hitung(int a) dan int hitung(int a)", "private int hitung(int a) dan public int hitung(int a)"], c: 2, exp: "Overloading mensyaratkan perbedaan parameter (jumlah/tipe). Menambah parameter (int a, int b) adalah valid." },
  { cat: "PBO / OOP", q: "Di Java, jika sebuah Class tidak menuliskan constructor secara manual, apa yang dilakukan compiler?", o: ["Error kompilasi", "Membuatkan default no-argument constructor secara otomatis", "Objek tidak bisa dibuat", "Menghentikan program", "Menjadikan kelas bersifat abstract"], c: 1, exp: "Compiler Java otomatis menyediakan default constructor kosong tanpa argumen." },
  { cat: "PBO / OOP", q: "Apa fungsi dari keyword `instanceof` di Java?", o: ["Membuat instance baru", "Mengecek apakah suatu objek merupakan instance dari Class tertentu", "Menghapus instance", "Mengganti tipe data instance", "Menghitung jumlah instance"], c: 1, exp: "Operator `instanceof` digunakan untuk menguji relasi tipe objek (misal: `obj instanceof Dog`)." },
  { cat: "PBO / OOP", q: "Sebuah class memiliki method `public static void main(String[] args)`. Mengapa method ini dibuat static?", o: ["Agar bisa di-override", "Agar runtime (JVM) dapat memanggilnya tanpa harus membuat instance objek class lebih dulu", "Agar nilainya tidak bisa diubah", "Agar menghemat memori RAM", "Agar bersifat private"], c: 1, exp: "JVM harus memanggil `main()` sebagai entry-point sebelum objek apapun dibuat di memori." },
  { cat: "PBO / OOP", q: "Apa akibatnya jika sebuah subclass TIDAK me-override abstract method yang ada pada superclass-nya?", o: ["Program tetap sukses", "Subclass tersebut juga HARUS dideklarasikan sebagai `abstract`", "Abstract method otomatis terhapus", "Method induk otomatis hilang", "Menjadi static method"], c: 1, exp: "Jika tak mengimplementasikan seluruh abstract method induk, subclass tersebut wajib ditandai `abstract`." },

  // HOTS (46-60) - Design Pattern dasar, Refactoring PBO, Tracing & Tricky Scenarios
  { cat: "PBO / OOP", q: "Design Pattern creational yang menjamin sebuah Class HANYA memiliki SATU INSTANCE saja di seluruh siklus aplikasi dinamakan...", o: ["Factory Pattern", "Singleton Pattern", "Observer Pattern", "Strategy Pattern", "MVC Pattern"], c: 1, exp: "Singleton menjamin hanya ada satu instance (misal Database Connection Pool)." },
  { cat: "PBO / OOP", q: "Bagaimana cara mengimplementasikan Singleton Pattern secara dasar di Java?", o: ["Public constructor dan public variable", "Private constructor dan static method yang mengembalikan instance tunggal", "Abstract class tanpa method", "Interface dengan 10 method", "Public constructor dan final variable"], c: 1, exp: "Singleton menyembunyikan constructor (private) dan menyediakan static accessor method." },
  { cat: "PBO / OOP", q: "Prinsip SOLID: 'S' singkatan dari Single Responsibility Principle yang berarti...", o: ["Satu class harus memiliki 1000 baris kode", "Satu class hanya boleh memiliki SATU alasan untuk berubah (satu fokus tanggung jawab)", "Satu method hanya boleh dipanggil satu kali", "Satu proyek hanya boleh ada satu class", "Semua variabel harus static"], c: 1, exp: "Single Responsibility Principle menyatakan bahwa satu modul/class fokus pada satu tugas spesifik." },
  { cat: "PBO / OOP", q: "Tracing kode Polymorphism:\n`class A { void test() { System.print(\"A\"); } }\nclass B extends A { void test() { System.print(\"B\"); } }\nclass C extends B { void test() { super.test(); System.print(\"C\"); } }\nC obj = new C(); obj.test();`\nOutputnya adalah...", o: ["BC", "ABC", "AC", "C", "Error"], c: 0, exp: "C memanggil `super.test()` (milik B) yang mencetak 'B', lalu C mencetak 'C'. Output: BC." },
  { cat: "PBO / OOP", q: "Dalam refactoring kode procedural menjadi PBO, jika kita menemukan sekumpulan data dan fungsi yang selalu bekerja bersama, tindakan terbaik adalah...", o: ["Membuat 10 fungsi global baru", "Membungkus data dan fungsi tersebut ke dalam sebuah Class baru (Encapsulation)", "Menghapus fungsi tersebut", "Menggunakan array multi-dimensi saja", "Menyimpan data di file txt"], c: 1, exp: "Mengelompokkan data (state) dan fungsi (behavior) berdekatan adalah inti refactoring PBO." },
  { cat: "PBO / OOP", q: "Tracing kode Java:\n`class Base { Base() { System.print(\"1\"); } }\nclass Derived extends Base { Derived() { System.print(\"2\"); } }\nDerived d = new Derived();`\nOutputnya adalah...", o: ["2", "12", "21", "1", "Error"], c: 1, exp: "Saat instansiasi `Derived`, constructor `Base` (super) dipanggil lebih dulu (mencetak 1), baru `Derived` (mencetak 2). Output: 12." },
  { cat: "PBO / OOP", q: "Apa yang terjadi jika terdapat kode: `class Parent {} class Child1 extends Parent {} class Child2 extends Parent {}` lalu kita lakukan Downcasting `Parent p = new Child1(); Child2 c2 = (Child2) p;`?", o: ["Sukses running", "Compile Error", "ClassCastException saat Runtime", "c2 bernilai null", "Terjadi infinite loop"], c: 2, exp: "Secara sintaks lolos kompiler, tapi saat runtime terjadi ClassCastException karena `p` sejatinya objek `Child1`, bukan `Child2`." },
  { cat: "PBO / OOP", q: "Prinsip Open/Closed Principle (O dalam SOLID) menyatakan bahwa komponen software harus...", o: ["Terbuka untuk modifikasi langsung, tertutup untuk ekstensi", "Terbuka untuk ekstensi (extension), tertutup untuk modifikasi kode asal (modification)", "Terbuka untuk publik, tertutup untuk private", "Terbuka di Windows, tertutup di Linux", "Terbuka untuk pembacaan, tertutup untuk penulisan"], c: 1, exp: "Open/Closed Principle mendorong penambahan fitur via ekstensi (misal inheritance/polymorphism) tanpa mengubah kode lama yang teruji." },
  { cat: "PBO / OOP", q: "Tracing kode Overloading:\n`class Calc { void add(int a, double b){ System.print(\"1\"); } void add(double a, int b){ System.print(\"2\"); } }\nCalc c = new Calc(); c.add(5, 5.0);`\nOutputnya adalah...", o: ["1", "2", "12", "Compile Error (Ambiguous call)", "Null"], c: 0, exp: "Parameter (int, double) pas cocok dengan `add(5, 5.0)` sehingga mencetak '1'." },
  { cat: "PBO / OOP", q: "Desain kode buruk di mana sebuah Class mengetahui terlalu banyak detail privat dan mengatur Class lain secara berlebihan disebut anti-pattern...", o: ["God Object / Feature Envy", "Singleton", "Factory", "Encapsulation", "Polymorphism"], c: 0, exp: "God Object / Feature Envy terjadi saat Encapsulation dilanggar dan 1 class mengontrol segalanya." },
  { cat: "PBO / OOP", q: "Bagaimana cara menangani kondisi race-condition pada method PBO yang diakses multi-thread di Java?", o: ["Menggunakan keyword `synchronized` pada method", "Mengubah variabel menjadi private", "Menggunakan loop while(true)", "Menghapus constructor", "Menggunakan abstract class"], c: 0, exp: "Keyword `synchronized` memastikan hanya 1 thread yang mengeksekusi method tersebut dalam satu waktu." },
  { cat: "PBO / OOP", q: "Tracing static block Java:\n`class X { static { System.print(\"A\"); } X(){ System.print(\"B\"); } }\nX obj1 = new X(); X obj2 = new X();`\nOutputnya adalah...", o: ["AB", "ABAB", "AB B", "ABB", "AAB"], c: 3, exp: "Static initializer block (`static {}`) berjalan SATU KALI saat class dimuat (mencetak A). Constructor berjalan setiap instansiasi (mencetak B 2 kali). Output: ABB." },
  { cat: "PBO / OOP", q: "Mengapa Composition lebih disarankan dibanding Deep Inheritance Tree (hirarki pewarisan yang terlalu dalam)?", o: ["Composition lebih cepat diketik", "Deep Inheritance menimbulkan masalah tight coupling dan kaku terhadap perubahan (fragile base class)", "Inheritance tidak mendukung polymorphism", "Composition tidak butuh class", "Inheritance memakan memori SSD"], c: 1, exp: "Prinsip 'Favor Composition over Inheritance' mencegah tight coupling dan masalah fragile base class." },
  { cat: "PBO / OOP", q: "Apa dampak dari me-return referensi objek Mutable langsung dari dalam Getter method?", o: ["Enkapsulasi rusak karena pihak luar bisa mengubah isi objek internal tanpa melalui Setter", "Kode lebih aman", "Kompiler otomatis me-reject", "Objek menjadi immutable", "Memori RAM langsung bersih"], c: 0, exp: "Returning mutable reference membocorkan data privat. Seharusnya dikembalikan defensive copy." },
  { cat: "PBO / OOP", q: "Tracing Polymorphism & Field Hiding:\n`class Parent { int x = 10; } class Child extends Parent { int x = 20; }\nParent p = new Child(); System.print(p.x);`\nOutputnya adalah...", o: ["10", "20", "30", "Compile Error", "Runtime Error"], c: 0, exp: "Method bersifat polymorphic (dynamic dispatch), tetapi FIELD/VARIABEL TIDAK polymorphic. Karena tipe variabel reference adalah `Parent`, maka `p.x` mencetak 10." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-02-pbo-dasar.json', output);
console.log('Done generating 60 Pertemuan 2 (PBO / OOP) questions with 5 options');
