const fs = require('fs');

const questions = [
  // LOTS (1-15) - CIA Triad, Kerentanan Web (OWASP Top 10), Hashing vs Encryption, HTTPS/TLS
  { cat: "Keamanan Software", q: "Tiga pilar utama dalam prinsip dasar Keamanan Perangkat Lunak (CIA Triad) adalah...", o: ["Confidentiality, Integrity, Availability", "Control, Identity, Authentication", "Code, Infrastructure, Application", "Crypto, Inspection, Authorization", "Certificates, Isolasinya, Access"], c: 0, exp: "CIA Triad: Kerahasiaan (Confidentiality), Integritas (Integrity), Ketersediaan (Availability)." },
  { cat: "Keamanan Software", q: "Prinsip CIA Triad yang menjamin bahwa data sensitif HANYA dapat diakses oleh pihak yang memiliki hak otorisasi dinamakan...", o: ["Confidentiality (Kerahasiaan)", "Integrity (Integritas)", "Availability (Ketersediaan)", "Authentication", "Non-Repudiation"], c: 0, exp: "Confidentiality menjaga data agar tidak bocor ke pihak yang tidak berhak." },
  { cat: "Keamanan Software", q: "Prinsip CIA Triad yang menjamin bahwa data tetap akurat, konsisten, dan TIDAK DIUBAH secara ilegal saat disimpan atau dikirim dinamakan...", o: ["Integrity (Integritas)", "Confidentiality", "Availability", "Authorization", "Auditability"], c: 0, exp: "Integrity menjamin data tidak mengalami modifikasi ilegal." },
  { cat: "Keamanan Software", q: "Prinsip CIA Triad yang menjamin bahwa sistem dan data dapat diakses oleh pengguna sah kapanpun dibutuhkan tanpa gangguan dinamakan...", o: ["Availability (Ketersediaan)", "Integrity", "Confidentiality", "Encryption", "Hashing"], c: 0, exp: "Availability memastikan sistem selalu siap melayani pengguna (bebas serangan DoS)." },
  { cat: "Keamanan Software", q: "Proses memverifikasi identitas seorang pengguna (misal mengecek username dan password saat login) dinamakan...", o: ["Authentication (Autentikasi)", "Authorization (Otorisasi)", "Accounting", "Encryption", "Auditing"], c: 0, exp: "Autentikasi adalah pembuktian 'Siapa Anda' (Who you are)." },
  { cat: "Keamanan Software", q: "Proses memverifikasi hak akses pengguna yang terautentikasi terhadap suatu resource/fitur tertentu dinamakan...", o: ["Authorization (Otorisasi)", "Authentication", "Identification", "Encryption", "Hashing"], c: 0, exp: "Otorisasi adalah penentuan 'Apa yang boleh Anda lakukan' (What you can do)." },
  { cat: "Keamanan Software", q: "Fungsi matematika 1-arah (one-way function) yang mengubah data arbitrer menjadi string berukuran tetap (fixed length) dan TIDAK DAPAT DIDEKRIPSI kembali dinamakan...", o: ["Hash Function", "Encryption Algorithm", "Encoding", "Compression", "Obfuscation"], c: 0, exp: "Hashing adalah operasi 1-arah (irreversible); data ter-hash tidak bisa di-decode balik." },
  { cat: "Keamanan Software", q: "Proses mengubah teks biasa (plaintext) menjadi teks terenkripsi (ciphertext) menggunakan kunci rahasia yang DAPAT DIDEKRIPSI kembali dinamakan...", o: ["Encryption (Enkripsi)", "Hashing", "Encoding", "Obfuscation", "Salting"], c: 0, exp: "Enkripsi adalah operasi 2-arah (reversible) menggunakan kunci dekripsi." },
  { cat: "Keamanan Software", q: "Organisasi nirlaba internasional yang merilis daftar 10 kerentanan keamanan aplikasi web paling kritis secara berkala adalah...", o: ["OWASP (Open Web Application Security Project)", "ISO/IEC", "IEEE", "W3C", "ANSI"], c: 0, exp: "OWASP merilis OWASP Top 10 sebagai acuan kerentanan keamanan web." },
  { cat: "Keamanan Software", q: "Protokol komunikasi web aman yang menggabungkan HTTP dengan enkripsi TLS/SSL dinamakan...", o: ["HTTPS", "HTTP/2", "SSH", "SFTP", "FTPS"], c: 0, exp: "HTTPS menggunakan sertifikat TLS/SSL untuk mengenkripsi lalu lintas data HTTP." },
  { cat: "Keamanan Software", q: "Nomor port default yang digunakan untuk lalu lintas komunikasi aman HTTPS adalah...", o: ["443", "80", "8080", "22", "3306"], c: 0, exp: "Port 443 adalah port standar protokol HTTPS (Port 80 untuk HTTP biasa)." },
  { cat: "Keamanan Software", q: "Serangan cyber yang bertujuan membuat layanan web tidak dapat diakses pengguna sah dengan cara membanjiri trafik dari banyak komputer peretas dinamakan...", o: ["DDoS (Distributed Denial of Service)", "SQL Injection", "XSS", "Phishing", "Man-in-the-Middle"], c: 0, exp: "DDoS membanjiri server dengan paket sampah hingga server crash/unreachable." },
  { cat: "Keamanan Software", q: "Teknik penipuan dengan menyamar sebagai institusi terpercaya lewat email/situs palsu untuk mencuri kredensial pengguna dinamakan...", o: ["Phishing", "Malware", "Ransomware", "Buffer Overflow", "Brute Force"], c: 0, exp: "Phishing adalah serangan sosial (Social Engineering) memancing data sensitif korban." },
  { cat: "Keamanan Software", q: "String acak tambahan yang digabungkan ke password sebelum dilakukan proses hashing untuk mencegah serangan Rainbow Table dinamakan...", o: ["Salt", "Pepper", "Key", "Nonce", "IV (Initialization Vector)"], c: 0, exp: "Salting menambahkan string acak unik pada setiap hash password." },
  { cat: "Keamanan Software", q: "Serangan cyber di mana peretas menyadap komunikasi antara dua pihak tanpa sepengetahuan mereka dinamakan...", o: ["Man-in-the-Middle (MitM)", "SQL Injection", "Cross-Site Scripting", "CSRF", "Directory Traversal"], c: 0, exp: "MitM menyadap atau memanipulasi data di tengah jalur komunikasi." },

  // MOTS (16-30) - Symmetric vs Asymmetric Encryption, OWASP Details, CORS, Security Headers, JWT Attacks
  { cat: "Keamanan Software", q: "Perbedaan utama Enkripsi Simetris (contoh: AES) dan Enkripsi Asimetris (contoh: RSA) adalah...", o: ["Enkripsi Simetris menggunakan 1 kunci rahasia yang sama untuk enkripsi dan dekripsi, sedangkan Enkripsi Asimetris menggunakan sepasang kunci (Public Key & Private Key)", "Simetris tidak butuh kunci", "Asimetris lebih cepat", "Simetris hanya untuk angka", "Keduanya persis sama"], c: 0, exp: "Symmetric = 1 Shared Key. Asymmetric = Public Key (Enkripsi) & Private Key (Dekripsi)." },
  { cat: "Keamanan Software", q: "Dalam Enkripsi Asimetris (Public-Private Key), kunci yang boleh disebarkan secara bebas kepada publik adalah...", o: ["Public Key", "Private Key", "Secret Key", "Master Key", "Root Key"], c: 0, exp: "Public Key disebar bebas untuk enkripsi; Private Key disimpan rahasia untuk dekripsi." },
  { cat: "Keamanan Software", q: "Serangan web OWASP di mana peretas menyisipkan kode script JavaScript jahat yang dieksekusi di browser korban dinamakan...", o: ["Cross-Site Scripting (XSS)", "SQL Injection", "CSRF", "Broken Authentication", "SSRF"], c: 0, exp: "XSS menyuntikkan script berbahaya di DOM browser korban." },
  { cat: "Keamanan Software", q: "Serangan web OWASP di mana peretas memaksa browser korban yang sedang terautentikasi untuk mengeksekusi aksi tak diinginkan di aplikasi web target dinamakan...", o: ["CSRF (Cross-Site Request Forgery)", "XSS", "SQL Injection", "Clickjacking", "Path Traversal"], c: 0, exp: "CSRF mengelabui browser agar mengirimkan request berbahaya berbekal cookie session otomatis." },
  { cat: "Keamanan Software", q: "Header HTTP Security yang memerintahkan browser untuk HANYA berkomunikasi lewat koneksi terenkripsi HTTPS (mencegah downgrade attack) dinamakan...", o: ["HSTS (HTTP Strict Transport Security)", "CORS", "Content-Security-Policy", "X-Frame-Options", "X-XSS-Protection"], c: 0, exp: "HSTS memaksa browser selalu menggunakan HTTPS." },
  { cat: "Keamanan Software", q: "Header HTTP Security yang digunakan untuk MENCEGAH situs web ditampilkan di dalam tag `<iframe>` (menangkal serangan Clickjacking) dinamakan...", o: ["X-Frame-Options (atau CSP frame-ancestors)", "Access-Control-Allow-Origin", "Strict-Transport-Security", "X-Content-Type-Options", "Referrer-Policy"], c: 0, exp: "X-Frame-Options: DENY/SAMEORIGIN mencegah framing clickjacking." },
  { cat: "Keamanan Software", q: "Header HTTP Security yang membatasi sumber-sumber (domain) script, gambar, dan stylesheet yang boleh dimuat oleh browser dinamakan...", o: ["Content-Security-Policy (CSP)", "CORS", "Authorization", "X-XSS-Protection", "Cookie"], c: 0, exp: "CSP adalah pertahanan ampuh pembatasan eksekusi resource penyelesai XSS." },
  { cat: "Keamanan Software", q: "Serangan OWASP di mana pengguna dapat mengakses file internal server dengan memanipulasi path URL (misal `../../etc/passwd`) dinamakan...", o: ["Path Traversal / Directory Traversal", "SQL Injection", "Command Injection", "CSRF", "XSS"], c: 0, exp: "Path Traversal mengeksploitasi sanitasi path file yang lemah." },
  { cat: "Keamanan Software", q: "Serangan di mana penyerang mencoba seluruh kombinasi password secara terus menerus hingga menemukan yang cocok dinamakan...", o: ["Brute Force Attack", "Dictionary Attack", "Rainbow Table Attack", "Phishing", "Man-in-the-Middle"], c: 0, exp: "Brute Force mencoba seluruh kombinasi string karakter sampai berhasil." },
  { cat: "Keamanan Software", q: "Serangan Brute Force yang lebih efisien dengan menggunakan daftar kata-kata kosa kata umum yang sering dipakai pengguna dinamakan...", o: ["Dictionary Attack", "Brute Force Murni", "Rainbow Table", "Phishing", "Zero-day"], c: 0, exp: "Dictionary Attack menguji daftar kata kata kunci populer (wordlists)." },
  { cat: "Keamanan Software", q: "Metode hashing modern yang dilengkapi faktor kerja (work factor) yang sengaja dibuat lambat untuk menahan serangan GPU cracking adalah...", o: ["Bcrypt / Argon2", "MD5", "SHA1", "CRC32", "Base64"], c: 0, exp: "Bcrypt dan Argon2 adalah algoritma slow-hashing berbasis kustomisasi biaya CPU/RAM." },
  { cat: "Keamanan Software", q: "Mengapa algoritma hashing MD5 dan SHA1 DILARANG digunakan lagi untuk pengamanan password modern?", o: ["Sudah rentan terhadap serangan Collision Attack dan sangat cepat dicrack menggunakan GPU / Rainbow Table modern", "MD5 terlalu panjang", "SHA1 tidak bisa disimpan di database", "MD5 hanya untuk Windows", "Keduanya berbayar"], c: 0, exp: "MD5/SHA1 cepat dan cacat kriptografi, mudah ditembus oleh Rainbow Table modern." },
  { cat: "Keamanan Software", q: "Prinsip keamanan 'Least Privilege' menyatakan bahwa...", o: ["Setiap komponen/pengguna HANYA boleh diberi hak akses minimal yang benar-benar dibutuhkan untuk melakukan tugasnya", "Semua user diberi akses admin", "Password harus 100 karakter", "Database tidak boleh dikunci", "Semua port dibuka"], c: 0, exp: "Least Privilege membatasi hak izin sekecil mungkin demi meminimalisasi dampak kebocoran." },
  { cat: "Keamanan Software", q: "Kerentanan OWASP 'Broken Object Level Authorization' (BOLA / IDOR) terjadi ketika...", o: ["Aplikasi tidak mengecek apakah pengguna yang terautentikasi berhak mengakses ID objek milik pengguna lain (misal mengubah URL `/api/orders/101` ke `/api/orders/102`)", "Password tidak di-hash", "Server down", "Website tidak pakai HTTPS", "HTML tidak semantik"], c: 0, exp: "IDOR/BOLA terjadi saat otorisasi level objek tidak divalidasi di backend." },
  { cat: "Keamanan Software", q: "Serangan di mana penyerang memasukkan input yang melebihi kapasitas alokasi buffer memori di bahasa C/C++ sehingga merusak area stack dinamakan...", o: ["Buffer Overflow", "SQL Injection", "CSRF", "XSS", "Race Condition"], c: 0, exp: "Buffer Overflow menimpa alokasi memori berdekatan di stack C/C++." },

  // MOTS+ (31-45) - Tracing Kode Rentan, JWT Attacks, Zero-Trust, Rate Limiting, Input Validation
  { cat: "Keamanan Software", q: "Tracing Kode Rentan Node.js:\n`app.get('/user', (req, res) => {\n  db.query(\"SELECT * FROM users WHERE id = \" + req.query.id);\n});` \nKode ini sangat rentan terhadap serangan...", o: ["SQL Injection (SQLi)", "Cross-Site Scripting (XSS)", "CSRF", "Buffer Overflow", "Path Traversal"], c: 0, exp: "Penggabungan string langsung (`+ req.query.id`) tanpa sanitasi memicu SQL Injection." },
  { cat: "Keamanan Software", q: "Bagaimana cara memperbaiki kode rentan SQLi di atas?", o: ["Menggunakan Parameterized Query: `db.query(\"SELECT * FROM users WHERE id = ?\", [req.query.id])`", "Mengubah metode ke POST", "Menggunakan eval()", "Menghapus klausul WHERE", "Mengubah ke SQLite"], c: 0, exp: "Parameterized Query (`?` placeholder) memisahkan koding SQL dan data parameter." },
  { cat: "Keamanan Software", q: "Kerentanan pada JWT di mana penyerang mengubah header menjadi `\"alg\": \"none\"` dan menghapus signature dinamakan...", o: ["JWT Signature Bypass (None Algorithm Attack)", "JWT Injection", "XSS Token", "CSRF Token", "Replay Attack"], c: 0, exp: "Algoritma `none` pada JWT memaksa server yang ceroboh mengabaikan verifikasi signature." },
  { cat: "Keamanan Software", q: "Bagaimana cara server memverifikasi bahwa Payload JWT belum pernah dimodifikasi oleh peretas?", o: ["Server me-recalculate Signature menggunakan Header + Payload + Secret Key internal, lalu mencocokkannya dengan Signature pada token", "Server mengecek database", "Server mengirim SMS", "Server menanyakan ke browser", "Payload terenkripsi otomatis"], c: 0, exp: "Kesesuaian Signature menjamin keutuhan data (Integrity) pada JWT." },
  { cat: "Keamanan Software", q: "Arsitektur Keamanan Perangkat Lunak 'Zero Trust Architecture' berpegang pada prinsip dasar...", o: ["'Never Trust, Always Verify' (Jangan pernah percaya siapapun, selalu verifikasi setiap request baik dari dalam maupun luar jaringan)", "Percaya penuh jaringan internal", "Matikan semua firewall", "Hapus semua password", "Semua user dianggap admin"], c: 0, exp: "Zero-Trust mengasumsikan ancaman ada di dalam dan luar jaringan, memvalidasi tiap request." },
  { cat: "Keamanan Software", q: "Serangan di mana penyerang mencuri atau mencegat data paket sensitif pada jaringan Wi-Fi Publik yang tidak terenkripsi diatasi dengan...", o: ["Menggunakan HTTPS / VPN untuk mengenkripsi seluruh lalu lintas jaringan", "Menggunakan browser baru", "Menghapus cookie", "Menggunakan CSS Flexbox", "Mengganti nama PC"], c: 0, exp: "Enkripsi Https/VPN mengubah paket jaringan menjadi ciphertext yang tak bisa diintip." },
  { cat: "Keamanan Software", q: "Teknik 'Input Sanitization' adalah...", o: ["Proses membersihkan dan membuang karakter berbahaya dari input pengguna sebelum diproses sistem", "Menghapus data di database", "Membuat form menjadi readonly", "Mengacak isi file", "Mematikan fitur input"], c: 0, exp: "Sanitisasi membuang/mengalihkan tag script atau sintaks SQL liar dari masukan pengguna." },
  { cat: "Keamanan Software", q: "Teknik 'Input Validation' adalah...", o: ["Proses mengecek apakah input pengguna memenuhi kriteria tipe, format, dan panjang yang diizinkan (misal: mengecek format email valid)", "Menghapus database", "Mengenkripsi form", "Menyimpan data di cookie", "Membuat alert"], c: 0, exp: "Validasi memastikan masukan sesuai skema aturan bisnis (whitelist validation)." },
  { cat: "Keamanan Software", q: "Di aplikasi web, pengamanan terhadap serangan Replay Attack pada transaksi keuangan dilakukan dengan menambahkan...", o: ["Nonce (Number Used Once) atau Timestamp unik pada setiap request transaksi", "Atribut required", "Metode GET", "CSS Animation", "Header Authorization"], c: 0, exp: "Nonce menjamin request transaksi lama yang di-replay oleh peretas akan ditolak." },
  { cat: "Keamanan Software", q: "Kerentanan 'Server-Side Request Forgery' (SSRF) terjadi ketika...", o: ["Server web dipaksa oleh penyerang untuk membuat request HTTP ke sistem internal yang tidak dapat diakses langsung dari publik", "Client kena virus", "Database terhapus", "CSS rusak", "HTML tidak valid"], c: 0, exp: "SSRF mengeksploitasi server backend sebagai proxy untuk menyerang jaringan intranet internal." },
  { cat: "Keamanan Software", q: "Teknik pertahanan 'Content Security Policy' (CSP) me-restrict eksekusi inline script dengan menyertakan atribut...", o: ["Nonce berbasis kriptografi atau Hash sha256 pada tag `<script nonce=\"...\">`", "Attribute style", "Method POST", "Tipe data String", "CORS header"], c: 0, exp: "CSP Nonce memastikan hanya inline script dengan nonce cocok dari server yang boleh dieksekusi." },
  { cat: "Keamanan Software", q: "Apa kegunaan dari fitur Subresource Integrity (SRI) pada tag HTML `<script src=\"...\" integrity=\"sha384-...\">`?", o: ["Memastikan file library JavaScript CDN eksternal yang diunduh TIDAK PERNAH dimodifikasi/dihack oleh pihak ketiga", "Mempercepat pengunduhan script", "Menghapus iklan", "Membuat file JS terkompresi", "Mencegah CORS"], c: 0, exp: "SRI memverifikasi hash file CDN eksternal agar aman dari pasokan pembajakan (Supply Chain Attack)." },
  { cat: "Keamanan Software", q: "Jenis kerentanan di mana peretas dapat menebak Session ID pengguna karena algoritmanya tidak acak dinamakan...", o: ["Predictable Session ID / Weak Session Fixation", "SQL Injection", "CSRF", "XSS", "DoS"], c: 0, exp: "Session ID wajib dibuat acak dengan generator pseudo-random aman (Cryptographically Secure PRNG)." },
  { cat: "Keamanan Software", q: "Penggunaan 'Rate Limiting' pada endpoint API Login berguna untuk mencegah...", o: ["Serangan Brute Force menebak password secara masal", "Serangan XSS", "Serangan SQLi", "Kerusakan database", "Memory leak JS"], c: 0, exp: "Rate Limiting memblokir IP yang melakukan 10x percobaan login gagal dalam 1 menit." },
  { cat: "Keamanan Software", q: "Dalam penilaian risikonya, kerentanan 'Zero-Day Vulnerability' berarti...", o: ["Kerentanan keamanan perangkat lunak yang BARU DITEMUKAN dan BELUM MEMILIKI tambalan (patch) keamanan resmi dari pembuatnya", "Kerentanan berusia 0 hari yang tidak berbahaya", "Kerentanan yang sudah diperbaiki", "Kerentanan khusus Windows 95", "Kerentanan pada database kosong"], c: 0, exp: "Zero-day adalah cela keamanan yang belum ada obat/patch fisiknya dari vendor." },

  // HOTS (46-60) - Security Architecture, Pen-testing concepts, Code Auditing & Cryptographic Pitfalls
  { cat: "Keamanan Software", q: "Tracing Kode Rentan XSS:\n`const name = new URLSearchParams(window.location.search).get('name');\ndocument.getElementById('welcome').innerHTML = 'Halo ' + name;` \nJika URL dibuka `site.com?name=<img src=x onerror=alert(1)>`, apa yang terjadi?", o: ["Skrip `alert(1)` akan dieksekusi oleh browser (Reflected XSS!)", "Tampil teks polos", "Halaman error 404", "Server down", "Teks name diabaikan"], c: 0, exp: "Menggunakan `innerHTML` memasukkan tag img liar yang memicu event handler `onerror` JS." },
  { cat: "Keamanan Software", q: "Bagaimana perbaikan kode DOM XSS di atas agar 100% aman?", o: ["Ganti `innerHTML` dengan `textContent`: `document.getElementById('welcome').textContent = 'Halo ' + name;`", "Ganti `get` dengan `post`", "Gunakan `eval()`", "Gunakan CSS grid", "Simpan di LocalStorage"], c: 0, exp: "`textContent` mengisolasi input sebagai teks murni tanpa mengurai tag HTML." },
  { cat: "Keamanan Software", q: "Dalam kriptografi, kesalahan fatal me-re-use 'Initialization Vector' (IV) atau Nonce pada mode enkripsi AES-CTR / AES-GCM menyebabkan...", o: ["Kerahasiaan ciphertext rusak (memungkinkan penyerang mendekripsi plaintext tanpa kunci rahasia!)", "Enkripsi makin kuat", "File terhapus", "Program lebih cepat", "Key otomatis berganti"], c: 0, exp: "Reusing Nonce/IV pada Stream Cipher merusak jaminan kerahasiaan kriptografi." },
  { cat: "Keamanan Software", q: "Serangan 'Side-Channel Timing Attack' pada verifikasi token/password terjadi ketika...", o: ["Penyerang mengukur WAKTU EKSEKUSI perbandingan string di server untuk menebak karakter per karakter token secara bertahap!", "Penyerang mematikan server", "Penyerang mencuri Wi-Fi", "Penyerang mengubah CSS", "Penyerang memakai GPU"], c: 0, exp: "Perbandingan string standar (`==`) berhenti saat 1 karakter beda, memberi bocoran waktu pada peretas." },
  { cat: "Keamanan Software", q: "Bagaimana cara MENCEGAH Timing Attack saat membandingkan dua string sensitif (seperti Token Hmac) di Node.js?", o: ["Menggunakan fungsi perbandingan waktu konstan: `crypto.timingSafeEqual(buf1, buf2)`", "Menggunakan operator `===`", "Menggunakan `==`", "Mengubah string ke uppercase", "Menggunakan for loop biasa"], c: 0, exp: "`crypto.timingSafeEqual()` selalu mengeksekusi durasi perbandingan yang konstan tanpa peduli titik perbedaan string." },
  { cat: "Keamanan Software", q: "Proses pengujian keamanan perangkat lunak dengan cara mensimulasikan serangan siber nyata secara legal dinamakan...", o: ["Penetration Testing (Pen-Test)", "Unit Testing", "Integration Testing", "A/B Testing", "Stress Testing"], c: 0, exp: "Penetration Testing mensimulasikan serangan nyata untuk mengidentifikasi celah keamanan." },
  { cat: "Keamanan Software", q: "Metode Pen-test di mana penguji TIDAK MEMILIKI INFORMASI SAMA SEKALI mengenai arsitektur internal atau source code sistem dinamakan...", o: ["Black Box Testing", "White Box Testing", "Gray Box Testing", "Unit Testing", "Glass Box Testing"], c: 0, exp: "Black Box Testing mensimulasikan peretas luar tanpa akses informasi internal." },
  { cat: "Keamanan Software", q: "Metode Pen-test di mana penguji DIBERI AKSES PENUH ke source code dan dokumentasi arsitektur sistem dinamakan...", o: ["White Box Testing", "Black Box Testing", "Gray Box Testing", "Smoke Testing", "Blind Testing"], c: 0, exp: "White Box Testing memeriksa kodingan langsung secara transparan." },
  { cat: "Keamanan Software", q: "Dalam analisis static code security (SAST), istilah 'False Positive' berarti...", o: ["Tool keamanan melaporkan adanya kerentanan berbahaya, padahal sebenarnya kode tersebut AMAN", "Kerentanan berbahaya tidak terdeteksi", "Kode mengalami crash", "Database terhapus", "Tool mati"], c: 0, exp: "False Positive adalah peringatan palsu di mana kodingan sebenarnya aman." },
  { cat: "Keamanan Software", q: "Istilah 'False Negative' dalam audit keamanan berarti...", o: ["Terdapat kerentanan berbahaya di kodingan, namun TOOL GAGAL MENDETEKSI kerentanan tersebut!", "Tool mendeteksi bug palsu", "Sistem aman 100%", "Kodingan berjalan lancar", "Aplikasi lulus audit"], c: 0, exp: "False Negative sangat berbahaya karena celah keamanan nyata lolos dari pemantauan." },
  { cat: "Keamanan Software", q: "Prinsip 'Defense in Depth' dalam arsitektur keamanan perangkat lunak berarti...", o: ["Menerapkan BEBERAPA LAPISAN pertahanan keamanan yang saling melengkapi (misal Firewall + WAF + HTTPS + Auth + Input Validation + DB Encryption)", "Hanya mengandalkan 1 password rumit", "Mengunci server di kamar rapat", "Menghapus koneksi internet", "Membuat 10 admin"], c: 0, exp: "Defense in Depth menjamin jika 1 pertahanan jebol, masih ada lapisan keamanan berikutnya." },
  { cat: "Keamanan Software", q: "Mengapa menyimpan kunci rahasia (Secret Key / API Key) langsung di dalam repository Git public (Hardcoded Secret) dianggap kesalahan fatal?", o: ["Bot peretas otomatis memindai commit Git public dalam hitungan detik untuk mencuri kunci tersebut!", "Git tidak bisa di-commit", "File git membengkak", "Sintaks JS error", "Vercel memblokir git"], c: 0, exp: "Automated bots di GitHub memindai hardcoded secrets secara real-time untuk mengeksploitasi API key." },
  { cat: "Keamanan Software", q: "Solusi standar pengoperasian software untuk mengelola Secret Key tanpa menaruhnya di source code adalah...", o: ["Menggunakan Environment Variables (`.env`) yang ditambahkan ke `.gitignore`", "Menulisnya di README.md", "Menyimpannya di file CSS", "Menuliskannya di komentar JS", "Mengirimnya via email"], c: 0, exp: "Environment Variables (`.env`) memisahkan rahasia konfigurasi dari repositori koding." },
  { cat: "Keamanan Software", q: "Dalam pembuatan sistem autentikasi, teknik 'Account Lockout' bertugas untuk...", o: ["Mengunci sementara akun pengguna setelah beberapa kali percobaan password salah berturut-turut (menangkal Brute Force)", "Menghapus akun permanen", "Mengubah password pengguna", "Mengirim email spam", "Menutup browser"], c: 0, exp: "Account Lockout memblokir akses sementara setelah N kali kegagalan login." },
  { cat: "Keamanan Software", q: "Apa yang dimaksud dengan serangan 'Dependency Confusion / Supply Chain Attack' pada ekosistem npm/pip?", o: ["Peretas mempublikasikan paket pustaka (library) berbahaya ke registry publik dengan nama yang sama seperti paket privat internal perusahaan!", "Server npm down", "Node.js terhapus", "Database crash", "Git melarang commit"], c: 0, exp: "Supply chain attack menyuntikkan kode berbahaya via dependency pustaka pihak ketiga." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-08-pengujian-jaringan.json', output);
console.log('Done generating 60 Pertemuan 8 (Keamanan Perangkat Lunak / Software Security) questions with 5 options');
