const fs = require('fs');

const questions = [
  // LOTS (1-15) - Elemen HTML5, Sintaks CSS3, JS Fundamentals, DOM Elements
  { cat: "Web Dev Dasar", q: "Elemen semantik HTML5 yang digunakan untuk mendefinisikan bagian navigasi utama aplikasi web adalah...", o: ["<nav>", "<header>", "<section>", "<aside>", "<navigation>"], c: 0, exp: "Tag `<nav>` adalah elemen semantik resmi HTML5 khusus blok navigasi." },
  { cat: "Web Dev Dasar", q: "Elemen HTML5 yang digunakan untuk menampilkan gambar secara dinamis via JavaScript menggunakan grafis bitmap 2D/3D dinamakan...", o: ["<picture>", "<svg>", "<canvas>", "<img>", "<figure>"], c: 2, exp: "<canvas> menyediakan area render grafis berbasis script JavaScript." },
  { cat: "Web Dev Dasar", q: "Atribut HTML yang digunakan untuk memberikan kunci id unik pada sebuah elemen HTML dinamakan...", o: ["class", "id", "name", "key", "data-id"], c: 1, exp: "Atribut `id` bersifat unik di seluruh dokumen (hanya 1 elemen per id)." },
  { cat: "Web Dev Dasar", q: "Properti CSS yang digunakan untuk mengubah warna latar belakang sebuah elemen adalah...", o: ["color", "background-color", "text-color", "bg", "border-color"], c: 1, exp: "`background-color` menentukan warna Latar Belakang elemen." },
  { cat: "Web Dev Dasar", q: "Properti CSS yang digunakan untuk mengubah jarak ruang di DALAM elemen (antara konten dan border) dinamakan...", o: ["margin", "padding", "border", "spacing", "gap"], c: 1, exp: "Padding adalah ruang interior di dalam border elemen." },
  { cat: "Web Dev Dasar", q: "Properti CSS yang digunakan untuk mengatur jarak luar di SEKITAR elemen (di luar border) dinamakan...", o: ["padding", "margin", "outline", "gap", "border-spacing"], c: 1, exp: "Margin adalah ruang eksterior di luar border elemen." },
  { cat: "Web Dev Dasar", q: "Metode JavaScript modern yang digunakan untuk mendeklarasikan variabel ber-scope blok yang nilainya BISA diubah dinamakan...", o: ["var", "let", "const", "static", "val"], c: 1, exp: "`let` mendeklarasikan variabel block-scoped yang nilainya mutable (dapat diubah)." },
  { cat: "Web Dev Dasar", q: "Metode JavaScript yang digunakan untuk memilih elemen HTML pertama berdasarkan selektor CSS dinamakan...", o: ["document.getElementById()", "document.querySelector()", "document.getElementsByClassName()", "document.findAll()", "document.getElement()"], c: 1, exp: "`querySelector()` menerima string selektor CSS (seperti `.card` atau `#app`)." },
  { cat: "Web Dev Dasar", q: "Objek standar browser yang merepresentasikan struktur dokumen HTML sebagai pohon pohon objek hirarki dinamakan...", o: ["BOM (Browser Object Model)", "DOM (Document Object Model)", "JSON", "CSSOM", "API"], c: 1, exp: "DOM (Document Object Model) adalah antarmuka representasi dokumen HTML." },
  { cat: "Web Dev Dasar", q: "Model tata letak CSS3 1-dimensi yang sangat efisien untuk merapikan dan meratakan elemen dalam sebuah baris/kolom dinamakan...", o: ["Grid", "Flexbox (Flexible Box)", "Float", "Position Fixed", "Table Layout"], c: 1, exp: "Flexbox dirancang khusus untuk layout 1-dimensi (baris ATAU kolom)." },
  { cat: "Web Dev Dasar", q: "Model tata letak CSS3 2-dimensi yang memungkinkan pengaturan baris DAN kolom secara bersamaan dinamakan...", o: ["Flexbox", "CSS Grid", "Float", "Inline-Block", "Absolute Position"], c: 1, exp: "CSS Grid dirancang khusus untuk layout 2-dimensi (baris DAN kolom sekaligus)." },
  { cat: "Web Dev Dasar", q: "Manakah cara menyambungkan file JavaScript eksternal `script.js` ke dokumen HTML secara tepat?", o: ["<script src=\"script.js\"></script>", "<script href=\"script.js\"></script>", "<link rel=\"script\" href=\"script.js\">", "<js file=\"script.js\">", "<import src=\"script.js\">"], c: 0, exp: "Sintaks baku menyambung file JS eksternal adalah `<script src=\"...\"></script>`." },
  { cat: "Web Dev Dasar", q: "Manakah cara menyambungkan file CSS eksternal `style.css` di bagian `<head>` HTML?", o: ["<style src=\"style.css\">", "<link rel=\"stylesheet\" href=\"style.css\">", "<css href=\"style.css\">", "<script src=\"style.css\">", "<import css=\"style.css\">"], c: 1, exp: "Sintaks baku menyambung stylesheet eksternal adalah `<link rel=\"stylesheet\" href=\"...\">`." },
  { cat: "Web Dev Dasar", q: "Event listener JavaScript yang dipicu saat seorang pengguna menekan tombol tetikus (mouse click) pada sebuah elemen adalah...", o: ["onhover", "onclick", "onchange", "onkeydown", "onload"], c: 1, exp: "Event `click` / `onclick` merespon klik mouse pengguna." },
  { cat: "Web Dev Dasar", q: "Dalam CSS Box Model, urutan lapisan dari TERDALAM hingga TERLUAR adalah...", o: ["Content -> Padding -> Border -> Margin", "Content -> Margin -> Border -> Padding", "Margin -> Border -> Padding -> Content", "Border -> Padding -> Content -> Margin", "Padding -> Content -> Border -> Margin"], c: 0, exp: "Box Model: Content (isi) -> Padding -> Border (bingkai) -> Margin (jarak luar)." },

  // MOTS (16-30) - CSS Selectors Specificity, Event Bubbling/Capturing, Async JS Basics, Semantic Web
  { cat: "Web Dev Dasar", q: "Berapakah urutan prioritas (specificity) selektor CSS dari yang TERTINGGI hingga TERENDAH?", o: ["Inline Style > ID Selector > Class/Attribute Selector > Element Selector", "Element Selector > Class Selector > ID Selector > Inline Style", "ID Selector > Inline Style > Class Selector > Element Selector", "Class Selector > ID Selector > Inline Style > Element Selector", "Semua selektor berbobot sama"], c: 0, exp: "Specificity: Inline style (1000) > ID (100) > Class/Attribute/Pseudo (10) > Element/Pseudo-element (1)." },
  { cat: "Web Dev Dasar", q: "Apa kegunaan properti CSS `box-sizing: border-box;`?", o: ["Membuat border menjadi tebal", "Memastikan ukuran width dan height elemen sudah MEMASUKKAN padding dan border di dalamnya", "Menambahkan efek bayangan", "Mengubah elemen jadi melingkar", "Menghapus margin"], c: 1, exp: "`border-box` membuat lebar/tinggi elemen mencakup padding dan border sehingga ukuran layout tidak membesar terluar." },
  { cat: "Web Dev Dasar", q: "Fenomena di JavaScript di mana sebuah event pada elemen anak akan merambat naik ke atas menuju elemen-elemen induknya dinamakan...", o: ["Event Capturing", "Event Bubbling", "Event Delegation", "Event Throttling", "Event Hoisting"], c: 1, exp: "Event Bubbling adalah mekanisme perambatan event dari target terkecil ke atas hirarki DOM." },
  { cat: "Web Dev Dasar", q: "Metode event JavaScript `event.preventDefault()` berfungsi untuk...", o: ["Menghentikan event bubbling", "Membatalkan aksi bawaan (default behavior) dari browser (seperti submit form reload atau klik link)", "Menghapus elemen DOM", "Menghentikan perulangan JS", "Mematikan koneksi internet"], c: 1, exp: "`preventDefault()` mencegah perilaku standar browser (misal mencegah form reload halaman)." },
  { cat: "Web Dev Dasar", q: "Metode event JavaScript `event.stopPropagation()` berfungsi untuk...", o: ["Mencegah aksi default link", "Mengeksplisitkan bubbling event agar tidak merambat ke elemen parent di atasnya", "Menghapus event listener", "Me-reload halaman", "Mengubah CSS elemen"], c: 1, exp: "`stopPropagation()` menghentikan perambatan (bubbling/capturing) event ke parent DOM di atasnya." },
  { cat: "Web Dev Dasar", q: "Apa perbedaan variabel `const` dan `let` pada JavaScript modern?", o: ["`const` bersifat block-scoped tetapi nilainya TIDAK BISA di-reassign (konstan), sedangkan `let` nilainya BISA diubah", "`let` bersifat global, `const` bersifat lokal", "`const` khusus angka, `let` khusus string", "`let` tidak bisa diubah", "`const` bisa di-hoisting, `let` tidak"], c: 0, exp: "`const` mencegah pembaruan referensi (re-assignment) variabel." },
  { cat: "Web Dev Dasar", q: "Perhatikan atribut `data-*` pada HTML5 (misal `<button data-id=\"101\">`). Bagaimana cara membaca nilai `data-id` via JavaScript DOM?", o: ["element.getAttribute('data-id') atau element.dataset.id", "element.dataId", "element.value.id", "element.readData('id')", "element.id"], c: 0, exp: "HTML5 dataset API mengakses atribut `data-*` lewat `element.dataset.namaAtribut` atau `getAttribute()`." },
  { cat: "Web Dev Dasar", q: "Properti CSS Flexbox yang digunakan untuk mengatur perataan elemen di sepanjang SUMBU UTAMA (Main Axis) adalah...", o: ["align-items", "justify-content", "flex-direction", "align-content", "flex-wrap"], c: 1, exp: "`justify-content` meratakan item pada Main Axis flex (horizontal secara default)." },
  { cat: "Web Dev Dasar", q: "Properti CSS Flexbox yang digunakan untuk mengatur perataan elemen di sepanjang SUMBU SILANG (Cross Axis) adalah...", o: ["justify-content", "align-items", "flex-grow", "flex-shrink", "place-content"], c: 1, exp: "`align-items` meratakan item pada Cross Axis flex (vertikal secara default)." },
  { cat: "Web Dev Dasar", q: "Di JavaScript, tipe data dari ekspresi `typeof null` mengembalikan hasil unik yaitu...", o: ["\"null\"", "\"undefined\"", "\"object\"", "\"boolean\"", "\"number\""], c: 2, exp: "Secara sejarah di JavaScript, `typeof null` mengembalikan string `\"object\"` (quirk khas JS)." },
  { cat: "Web Dev Dasar", q: "Hasil dari ekspresi JavaScript `[] == false` adalah...", o: ["true", "false", "TypeError", "undefined", "NaN"], c: 0, exp: "Karena perbandingan longgar (==) melakukan type coercion, array kosong diubah ke string \"\" lalu ke angka 0, 0 == false bernilai true." },
  { cat: "Web Dev Dasar", q: "Perilaku JavaScript memindahkan deklarasi variabel `var` dan fungsi ke bagian atas lingkupnya sebelum eksekusi dinamakan...", o: ["Closure", "Hoisting", "Currying", "Debouncing", "Memoization"], c: 1, exp: "Hoisting memindahkan deklarasi `var` dan `function` ke bagian atas (top of scope)." },
  { cat: "Web Dev Dasar", q: "Kemampuan sebuah fungsi di JavaScript untuk 'mengingat' dan mengakses variabel dari lingkup luarnya (outer scope) meskipun fungsi luar tersebut sudah selesai dieksekusi dinamakan...", o: ["Hoisting", "Closure", "Callback", "Promise", "Async/Await"], c: 1, exp: "Closure adalah gabungan fungsi dan lingkungan leksikal tempat fungsi tersebut dideklarasikan." },
  { cat: "Web Dev Dasar", q: "Fungsi JavaScript `Array.prototype.map()` berguna untuk...", o: ["Memfilter elemen array", "Membuat array BARU yang berisi hasil transformasi dari setiap elemen array asal", "Menghitung total penjumlahan array", "Mengurutkan array", "Mencari 1 elemen pertama"], c: 1, exp: "`map()` me-return array baru berukuran sama dengan nilai yang sudah ditransformasi." },
  { cat: "Web Dev Dasar", q: "Fungsi JavaScript `Array.prototype.filter()` berguna untuk...", o: ["Membuat array BARU yang HANYA berisi elemen-elemen yang lolos pengujian kondisi (true)", "Mengubah semua isi array", "Menghapus array", "Menggabungkan 2 array", "Mencetak isi array"], c: 0, exp: "`filter()` menyaring elemen array berdasarkan pengujian fungsi predikat." },

  // MOTS+ (31-45) - Tracing DOM Manipulasi, CSS Grid/Flexbox Layout, Arrow Functions, LocalStorage
  { cat: "Web Dev Dasar", q: "Perbedaan utama `localStorage` dan `sessionStorage` pada Web Storage API Browser adalah...", o: ["Data `localStorage` tetap tersimpan permanen meskipun browser ditutup, sedangkan `sessionStorage` terhapus saat tab/browser ditutup", "`localStorage` hanya muat 1KB", "`sessionStorage` disimpan di server", "`localStorage` khusus angka", "Keduanya terhapus saat reload"], c: 0, exp: "`localStorage` bertahan tanpa waktu kedaluwarsa, `sessionStorage` hilang saat tab ditutup." },
  { cat: "Web Dev Dasar", q: "Berapa kapasitas penyimpanan maksimum rata-rata `localStorage` per domain pada browser modern?", o: ["4 KB", "100 KB", "5 MB", "1 GB", "Tidak terbatas"], c: 2, exp: "Standard Web Storage API menyediakan kuota simpan sekitar ~5MB per origin." },
  { cat: "Web Dev Dasar", q: "Manakah sintaks yang BENAR untuk menyimpan data objek JavaScript `user = {name: 'Budi'}` ke `localStorage`?", o: ["localStorage.setItem('user', user)", "localStorage.setItem('user', JSON.stringify(user))", "localStorage.save('user', user)", "localStorage.push('user', user)", "localStorage.write('user', JSON.toCSV(user))"], c: 1, exp: "`localStorage` hanya menerima string. Objek harus diubah ke string JSON dengan `JSON.stringify()`." },
  { cat: "Web Dev Dasar", q: "Bagaimana cara mengambil kembali objek JSON dari `localStorage` dan mengubahnya kembali menjadi Objek JavaScript?", o: ["JSON.parse(localStorage.getItem('user'))", "JSON.stringify(localStorage.getItem('user'))", "localStorage.getItem('user').toObject()", "localStorage.read('user')", "JSON.decode(localStorage.user)"], c: 0, exp: "`localStorage.getItem()` mengambil string JSON, lalu `JSON.parse()` mengurainya kembali jadi Objek." },
  { cat: "Web Dev Dasar", q: "Tracing CSS: Sebuah elemen `<div class=\"box\">` memiliki CSS `width: 200px; padding: 20px; border: 5px solid black; box-sizing: content-box;`. Berapakah LEBAR TOTAL elemen tersebut di layar?", o: ["200px", "225px", "250px", "240px", "205px"], c: 2, exp: "Pada `content-box`, total width = width (200) + padding kiri-kanan (40) + border kiri-kanan (10) = 250px." },
  { cat: "Web Dev Dasar", q: "Sebaliknya, jika elemen di atas menggunakan `box-sizing: border-box;`, berapakah LEBAR TOTAL elemen di layar?", o: ["250px", "200px", "225px", "175px", "240px"], c: 1, exp: "Pada `border-box`, total width diatur pas 200px (padding dan border memakan ruang dari dalam 200px)." },
  { cat: "Web Dev Dasar", q: "Tracing JS DOM:\n`const btn = document.createElement('button'); btn.textContent = 'Klik'; document.body.appendChild(btn);` Apa yang terjadi di halaman HTML?", o: ["Elemen button baru tercetak di paling bawah tag <body>", "Button terhapus", "Halaman reload", "Muncul alert", "Error DOM tidak ditemukan"], c: 0, exp: "`createElement` membuat node DOM baru, `appendChild` menyisipkannya ke dalam elemen body." },
  { cat: "Web Dev Dasar", q: "Apa keluaran dari ekspresi: `const numbers = [1, 2, 3]; const res = numbers.reduce((acc, curr) => acc + curr, 0);`?", o: ["6", "[1, 2, 3]", "0", "undefined", "[6]"], c: 0, exp: "`reduce` mengakumulasi nilai elemen array: 0 + 1 + 2 + 3 = 6." },
  { cat: "Web Dev Dasar", q: "Sintaks Arrow Function JavaScript `const add = (a, b) => a + b;` merupakan bentuk ringkas dari...", o: ["function add(a, b) { return a + b; }", "function add(a, b) { a + b; }", "const add = function(a, b) { a + b; }", "class add { constructor(a, b){ return a+b; } }", "void add(a, b) { return a+b; }"], c: 0, exp: "Arrow function dengan ekspresi tunggal tanpa kurung kurawal memiliki implicit return `return a + b`." },
  { cat: "Web Dev Dasar", q: "Manakah perbedaan penting perilaku keyword `this` di Arrow Function dibanding fungsi biasa?", o: ["Arrow Function TIDAK memiliki konteks `this` sendiri (mengikat `this` secara lexical dari outer scope)", "Arrow Function selalu membuat `this` bernilai null", "Arrow Function khusus method static", "Arrow Function membuat `this` jadi global", "Tidak ada bedanya"], c: 0, exp: "Arrow functions memperlakuan `this` secara lexical scope (tidak me-bind `this` baru)." },
  { cat: "Web Dev Dasar", q: "Properti CSS Media Query yang digunakan untuk menerapkan gaya khusus pada perangkat layar HP (Responsive Web Design) adalah...", o: ["@media screen and (max-width: 768px)", "@responsive (phone)", "@device-width: 768px", "@screen-mobile", "@viewport (mobile)"], c: 0, exp: "`@media screen and (max-width: 768px)` adalah sintaks baku Responsive Web Design untuk layar seluler." },
  { cat: "Web Dev Dasar", q: "Atribut HTML5 pada elemen `<input>` yang digunakan untuk memastikan form tidak bisa dikirim jika kolom masih kosong adalah...", o: ["validate", "required", "not-null", "mandatory", "check"], c: 1, exp: "Atribut `required` mengaktifkan validasi HTML bawaan browser agar kolom wajib diisi." },
  { cat: "Web Dev Dasar", q: "Sintaks CSS Grid `grid-template-columns: repeat(3, 1fr);` berfungsi untuk...", o: ["Membuat 3 kolom dengan lebar fraksi yang sama besar", "Membuat 1 kolom berukuran 3fr", "Membuat 3 baris", "Mengulang grid 3 kali", "Membuat margin 3px"], c: 0, exp: "`repeat(3, 1fr)` membagi container menjadi 3 kolom fleksibel sama rata (equal 1 fraction each)." },
  { cat: "Web Dev Dasar", q: "Teknik Event Delegation pada JavaScript DOM adalah...", o: ["Memasang 100 event listener pada setiap tombol anak", "Memasang 1 event listener tunggal pada elemen Parent untuk menangani event dari anak-anaknya menggunakan `event.target`", "Menghapus event listener", "Menggunakan setTimeout", "Menyimpan event di LocalStorage"], c: 1, exp: "Event Delegation memanfaatkan Event Bubbling dengan memasang handler di parent tunggal demi efisiensi memori." },
  { cat: "Web Dev Dasar", q: "Metode JavaScript `document.cookie` memiliki keterbatasan dibanding `localStorage` yaitu...", o: ["Kapasitas sangat kecil (~4KB) dan otomatis terikut dikirim pada setiap HTTP request header ke server", "Tidak bisa dibaca via JS", "Khusus browser Internet Explorer", "Tidak didukung HTML5", "Menghapus LocalStorage"], c: 0, exp: "Cookie berkapasitas ~4KB dan dikirim ke server pada setiap request header, membebankan lalu lintas jaringan jika terlalu banyak." },

  // HOTS (46-60) - Performance Optimization, Critical Rendering Path, Memory Leaks, Asynchronous Event Loop
  { cat: "Web Dev Dasar", q: "Konsep Event Loop pada JavaScript bertanggung jawab untuk...", o: ["Mengatur jalannya kode asynchronous (Callback/Promise) dengan memindahkan tugas dari Callback Queue ke Call Stack saat stack kosong", "Membuat loop FOR lebih cepat", "Menghitung fps animasi", "Mengubah CSS otomatis", "Mencegah peretasan XSS"], c: 0, exp: "Event Loop memantau Call Stack dan Task Queue untuk mengeksekusi callback async secara non-blocking." },
  { cat: "Web Dev Dasar", q: "Tracing Event Loop JS:\n`console.log('1'); setTimeout(() => console.log('2'), 0); console.log('3');`\nUrutan keluaran di konsol adalah...", o: ["1, 2, 3", "1, 3, 2", "2, 1, 3", "3, 1, 2", "1, 2"], c: 1, exp: "Synchronous `1` dan `3` langsung di-stack. `setTimeout` masuk Web API & Task Queue, baru dieksekusi Event Loop setelah stack bersih. Output: 1, 3, 2." },
  { cat: "Web Dev Dasar", q: "Atribut `defer` pada tag `<script src=\"app.js\" defer></script>` berfungsi untuk...", o: ["Mengunduh script secara asynchronous paralel dan mengeksekusinya SETELAH seluruh dokumen HTML selesai di-parse", "Menghentikan parsing HTML", "Menjalankan script paling awal", "Mencegah script dieksekusi", "Menyimpan script di cache"], c: 0, exp: "`defer` mengunduh script di background dan menjamin eksekusi setelah DOM parsing selesai (DOMReady)." },
  { cat: "Web Dev Dasar", q: "Sebaliknya, atribut `async` pada tag `<script src=\"analytics.js\" async></script>` berfungsi untuk...", o: ["Mengunduh script paralel dan LANGSUNG mengeksekusinya seketika saat selesai diunduh (bisa menyela parsing HTML)", "Menunggu DOMReady", "Menghentikan pengunduhan", "Membuat script private", "Menjadikan script synchronous"], c: 0, exp: "`async` mengeksekusi script sesegera mungkin saat file selesai diunduh tanpa menjamin urutan eksekusi." },
  { cat: "Web Dev Dasar", q: "Teknik optimasi performa JS `Debouncing` biasanya diterapkan pada event seperti `oninput` pencarian bertujuan untuk...", o: ["Menunda eksekusi fungsi hingga pengguna berhenti mengetik selama jeda waktu tertentu (mencegah spam request API)", "Membuat animasi lebih halus", "Mengacak string", "Membuat form otomatis terisi", "Menghapus event listener"], c: 0, exp: "Debouncing menahan pemicuan panggilan fungsi sampai ada jeda hening tertentu dari aktivitas pengguna." },
  { cat: "Web Dev Dasar", q: "Penyebab utama Memory Leak (kebocoran memori) pada aplikasi Single Page Application (SPA) JavaScript adalah...", o: ["Lupa menghapus Event Listener global (`window.addEventListener`) atau setInterval yang tidak di-clear saat komponen dihancurkan", "Menggunakan CSS Flexbox", "Menggunakan tag HTML5 semantik", "Variabel const yang terlalu banyak", "Menggunakan gambar PNG"], c: 0, exp: "Event listener / timer tak tertutup mempertahankan referensi DOM di memori, mencegah Garbage Collection." },
  { cat: "Web Dev Dasar", q: "Manakah teknik pengisian CSS yang paling buruk untuk performa halaman web skala besar?", o: ["External Stylesheet (`<link rel=\"stylesheet\">`)", "Inline CSS (`style=\"...\"`) langsung pada setiap elemen HTML", "CSS Modules", "Tailwind Utility Classes", "SASS SCSS Compiled"], c: 1, exp: "Inline CSS menggelembungkan ukuran HTML, membatasi caching browser, dan menghancurkan prinsip pemisahan konsentrasi." },
  { cat: "Web Dev Dasar", q: "Apa dampak dari memicu 'Reflow' (Layout Thrashing) secara berlebihan di JavaScript DOM?", o: ["Browser dipaksa menghitung ulang posisi & geometris seluruh elemen halaman secara mendadak, menyebabkan tampilan patah-patah (lag)", "File HTML terhapus", "Server mengalami crash", "Database terkunci", "Warna elemen hilang"], c: 0, exp: "Reflow membebankan CPU browser karena harus mengalkulasi ulang layout geometris DOM secara berulang." },
  { cat: "Web Dev Dasar", q: "Properti CSS yang memanfaatkan Akselerasi Perangkat Keras GPU (GPU Acceleration) untuk animasi halus (60fps) tanpa memicu Reflow adalah...", o: ["top / left", "margin-left", "transform (translate3d / scale) dan opacity", "width / height", "padding"], c: 2, exp: "`transform` dan `opacity` ditangani oleh compositor layer di GPU tanpa memicu layout reflow." },
  { cat: "Web Dev Dasar", q: "Tracing Promise JS:\n`Promise.resolve(1).then(x => x + 1).then(x => { throw new Error('Err'); }).catch(() => 5).then(x => console.log(x));`\nOutputnya adalah...", o: ["1", "2", "5", "Error", "undefined"], c: 2, exp: "Keluaran `x+1` (2) melempar Error, ditangkap oleh `.catch()` yang me-return `5`. Chain `.then()` berikutnya menerima 5. Output: 5." },
  { cat: "Web Dev Dasar", q: "Pernyataan yang BENAR mengenai perbedaan Microtask Queue (Promise / queueMicrotask) dan Macrotask Queue (setTimeout / setInterval) pada Event Loop JS adalah...", o: ["Microtask Queue memiliki prioritas LEBIH TINGGI dan dieksekusi SELURUHNYA sampai kosong sebelum Event Loop beralih ke Macrotask Queue", "Macrotask selalu lebih dulu", "Keduanya memiliki prioritas sama", "Microtask khusus CSS", "Macrotask khusus DOM"], c: 0, exp: "Microtasks (Promise) selalu dihabiskan dulu oleh Event Loop di setiap akhir tick sebelum memproses Macrotask (setTimeout)." },
  { cat: "Web Dev Dasar", q: "Dalam isu keamanan web frontend, serangan Cross-Site Scripting (XSS) terjadi ketika...", o: ["Penyerang menyisipkan kode script JavaScript jahat ke dalam halaman web yang dieksekusi oleh browser pengguna lain", "Penyerang mematikan database server", "Penyerang menebak password admin", "Penyerang mengunduh file CSS", "Form dikirim tanpa HTTPS"], c: 0, exp: "XSS menyuntikkan script liar di DOM untuk mencuri cookie session pengguna." },
  { cat: "Web Dev Dasar", q: "Bagaimana cara MENCEGAH serangan XSS saat menampilkan teks masukan pengguna di halaman HTML?", o: ["Menggunakan `element.innerHTML = userInput`", "Melakukan Sanitasi & Encoding HTML karakter khusus (seperti memetakan `<` menjadi `&lt;`) atau menggunakan `element.textContent`", "Menyimpan data di LocalStorage", "Menggunakan CSS Grid", "Mengubah variabel jadi const"], c: 1, exp: "`textContent` secara otomatis meng-encode karakter HTML sehingga menghalangi eksekusi script jahat." },
  { cat: "Web Dev Dasar", q: "Metode JavaScript `Object.freeze(obj)` berfungsi untuk...", o: ["Membuat objek menjadi immutable (properti tidak bisa ditambah, dihapus, atau diubah nilainya)", "Menyimpan objek ke harddisk", "Mengubah objek ke JSON", "Membuat objek berukuran 0", "Menghapus objek dari RAM"], c: 0, exp: "`Object.freeze()` membekukan objek secara dangkal (shallow freeze) dari segala bentuk mutasi." },
  { cat: "Web Dev Dasar", q: "Sintaks Destructuring Assignment JavaScript `const { name, age } = user;` berfungsi untuk...", o: ["Mengekstrak properti `name` dan `age` dari objek `user` secara langsung ke dalam variabel independen", "Menghapus properti name dan age dari user", "Menggabungkan dua objek", "Mengubah objek jadi array", "Mengecek apakah properti ada"], c: 0, exp: "Destructuring mengekstrak nilai objek/array ke dalam variabel lokal berformat ringkas." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-05-web-frontend.json', output);
console.log('Done generating 60 Pertemuan 5 (Web Development Dasar / HTML, CSS, JS) questions with 5 options');
