const fs = require('fs');

const questions = [
  // LOTS (1-15) - Konsep Pemodelan Perangkat Lunak, UML Diagram types, ERD dasar, Kardinalitas
  { cat: "Pemodelan Sistem", q: "Bahasa standar pemodelan visual yang digunakan untuk menspesifikasikan, mevisualisasikan, dan mendokumentasikan artefak sistem perangkat lunak dinamakan...", o: ["UML (Unified Modeling Language)", "ERD (Entity Relationship Diagram)", "DFD (Data Flow Diagram)", "Flowchart", "BPMN"], c: 0, exp: "UML adalah bahasa standar internasional untuk pemodelan analisis dan desain berorientasi objek." },
  { cat: "Pemodelan Sistem", q: "Diagram UML yang digunakan untuk menggambarkan interaksi antara fungsionalitas sistem dengan aktor luar dinamakan...", o: ["Class Diagram", "Use Case Diagram", "Sequence Diagram", "Activity Diagram", "Deployment Diagram"], c: 1, exp: "Use Case Diagram memodelkan persyaratan fungsionalitas sistem dari sudut pandang Aktor." },
  { cat: "Pemodelan Sistem", q: "Simbol manusia pada Use Case Diagram merepresentasikan...", o: ["User Interface", "Aktor (Actor)", "Database", "Server", "System Boundary"], c: 1, exp: "Aktor merepresentasikan peran manusia atau sistem eksternal yang berinteraksi dengan Use Case." },
  { cat: "Pemodelan Sistem", q: "Relasi pada Use Case yang menandakan bahwa suatu Use Case WAJIB memanggil/menjalankan Use Case lain secara mutlak adalah...", o: ["<<extend>>", "<<include>>", "Generalization", "Association", "Dependency"], c: 1, exp: "<<include>> menandakan bahwa Use Case target wajib (mandatory) dieksekusi oleh Use Case sumber." },
  { cat: "Pemodelan Sistem", q: "Relasi pada Use Case yang menandakan bahwa suatu Use Case OPSIONAL (tambahan/kondisional) dapat memperluas perilaku Use Case utama dinamakan...", o: ["<<include>>", "<<extend>>", "Realization", "Aggregation", "Composition"], c: 1, exp: "<<extend>> menandakan perilaku tambahan yang opsional jika kondisi tertentu terpenuhi." },
  { cat: "Pemodelan Sistem", q: "Diagram UML struktur statis yang menggambarkan kelas-kelas dalam sistem, atribut, method, dan hubungannya dinamakan...", o: ["Sequence Diagram", "Class Diagram", "State Machine Diagram", "Component Diagram", "Package Diagram"], c: 1, exp: "Class Diagram adalah diagram struktur statis utama dalam PBO." },
  { cat: "Pemodelan Sistem", q: "Diagram UML perilaku yang menggambarkan alur kerja (workflow) atau aktivitas bisnis langkah demi langkah dinamakan...", o: ["Activity Diagram", "Use Case Diagram", "Deployment Diagram", "Class Diagram", "Object Diagram"], c: 0, exp: "Activity Diagram mirip flowchart yang menggambarkan alur aktivitas sistem/bisnis." },
  { cat: "Pemodelan Sistem", q: "Diagram UML yang menekankan pada urutan pesan (message sequence) berdasarkan WAKTU interaksi antar objek dinamakan...", o: ["Sequence Diagram", "Activity Diagram", "Use Case Diagram", "Component Diagram", "Deployment Diagram"], c: 0, exp: "Sequence Diagram menggambarkan interaksi objek sepanjang garis waktu (lifeline) secara kronologis." },
  { cat: "Pemodelan Sistem", q: "Pemodelan data konseptual yang digunakan untuk menggambarkan entitas, atribut, dan relasinya di database dinamakan...", o: ["UML", "ERD (Entity Relationship Diagram)", "DFD", "Wireframe", "Mockup"], c: 1, exp: "ERD digunakan khusus untuk merancang struktur data dan relasi basis data." },
  { cat: "Pemodelan Sistem", q: "Simbol Persegi Panjang pada ERD standar Chen merepresentasikan...", o: ["Entitas (Entity)", "Atribut", "Relasi", "Kardinalitas", "Weak Attribute"], c: 0, exp: "Persegi panjang merepresentasikan Entitas (objek data utama seperti Siswa, Guru)." },
  { cat: "Pemodelan Sistem", q: "Simbol Elips / Oval pada ERD merepresentasikan...", o: ["Entitas", "Atribut", "Relasi", "Aktor", "Proses"], c: 1, exp: "Oval merepresentasikan Atribut (karakteristik dari entitas seperti nama, nis)." },
  { cat: "Pemodelan Sistem", q: "Simbol Belah Ketupat (Diamond) pada ERD merepresentasikan...", o: ["Entitas", "Atribut", "Relasi (Relationship)", "Primary Key", "Foreign Key"], c: 2, exp: "Belah Ketupat merepresentasikan Relasi (hubungan antar entitas seperti 'Mengajar')." },
  { cat: "Pemodelan Sistem", q: "Simbol Oval dengan garis bawah (underline) pada ERD menandakan atribut tersebut sebagai...", o: ["Multivalue Attribute", "Derived Attribute", "Primary Key (Key Attribute)", "Foreign Key", "Composite Attribute"], c: 2, exp: "Garis bawah pada nama atribut ERD menandakan Key Attribute (Primary Key)." },
  { cat: "Pemodelan Sistem", q: "Derajat jumlah hubungan entitas (misal 1:1, 1:N, N:M) dalam ERD dinamakan...", o: ["Kardinalitas / Modalitas", "Normalisasi", "Enkapsulasi", "Polimorfisme", "Inheritansi"], c: 0, exp: "Kardinalitas menentukan jumlah maksimum instansiasi entitas yang dapat terhubung ke entitas lain." },
  { cat: "Pemodelan Sistem", q: "Diagram UML yang menggambarkan arsitektur fisik perangkat keras (hardware) dan penyebaran komponen software pada node dinamakan...", o: ["Component Diagram", "Deployment Diagram", "Package Diagram", "Composite Structure", "Activity Diagram"], c: 1, exp: "Deployment Diagram menggambarkan infrastruktur fisik tempat aplikasi dideploy." },

  // MOTS (16-30) - Notasi UML, Lifeline, Swimlane, Relasi Class (Aggregation vs Composition), ERD Crow's Foot
  { cat: "Pemodelan Sistem", q: "Pada Activity Diagram, pembagian area visual yang memisahkan tanggung jawab aktivitas berdasarkan Aktor atau Komponen sistem dinamakan...", o: ["Lifeline", "Swimlane", "Join Node", "Fork Node", "Decision Node"], c: 1, exp: "Swimlane membagi diagram menjadi jalur-jalur vertikal/horizontal berdasarkan aktor penanggung jawab." },
  { cat: "Pemodelan Sistem", q: "Pada Sequence Diagram, garis putus-putus vertikal di bawah objek yang menggambarkan keberadaan objek seiring waktu dinamakan...", o: ["Lifeline", "Activation Bar", "Message Line", "Swimlane", "Self Call"], c: 0, exp: "Lifeline adalah garis vertikal tempat durasi hidup dan pesan objek ditelusuri." },
  { cat: "Pemodelan Sistem", q: "Perbedaan notasi relasi Aggregation (Belah Ketupat Kosong ◊) dan Composition (Belah Ketupat Isi ♦) pada Class Diagram adalah...", o: ["Aggregation adalah hubungan kuat, Composition hubungan lemah", "Composition adalah hubungan kepemilikan kuat (jika induk dihapus anak ikut hancur), Aggregation adalah hubungan lemah", "Aggregation khusus interface", "Composition hanya untuk database", "Keduanya tidak ada perbedaan"], c: 1, exp: "Composition (♦) menandakan bahwa bagian tidak dapat eksis tanpa keberadaan induknya." },
  { cat: "Pemodelan Sistem", q: "Simbol panah segitiga kosong (▷) yang menghubungkan Subclass ke Superclass pada Class Diagram menggambarkan relasi...", o: ["Association", "Generalization / Inheritance", "Dependency", "Realization", "Aggregation"], c: 1, exp: "Generalization (Pewarisan/Inheritance) disimbolkan panah segitiga kosong mengarah ke kelas induk." },
  { cat: "Pemodelan Sistem", q: "Simbol panah putus-putus dengan segitiga kosong (---▷) yang menghubungkan Class ke Interface menggambarkan relasi...", o: ["Generalization", "Realization / Implementation", "Dependency", "Association", "Composition"], c: 1, exp: "Realization menandakan kelas mengimplementasikan kontrak interface." },
  { cat: "Pemodelan Sistem", q: "Atribut turunan pada ERD yang nilainya dihitung dari atribut lain (misal `Umur` dari `TanggalLahir`) digambarkan dengan simbol...", o: ["Oval titik-titik (Dashed Ellipse)", "Oval ganda", "Oval garis bawah", "Persegi titik-titik", "Belah ketupat ganda"], c: 0, exp: "Derived Attribute (Atribut Turunan) disimbolkan dengan oval garis putus-putus." },
  { cat: "Pemodelan Sistem", q: "Atribut yang dapat memiliki lebih dari satu nilai untuk satu entitas (misal `Hobi` atau `NoHP`) pada ERD Chen disimbolkan dengan...", o: ["Oval Ganda (Double Ellipse)", "Oval Garis Bawah", "Persegi Panjang Ganda", "Belah Ketupat Ganda", "Oval Putus-putus"], c: 0, exp: "Multivalued Attribute disimbolkan dengan dua garis bundar (Oval Ganda)." },
  { cat: "Pemodelan Sistem", q: "Dalam notasi ERD Crow's Foot, garis cabang tiga kaki burung gagak menandakan kardinalitas...", o: ["Zero (0)", "One (1)", "Many (N)", "Optional", "Mandatory"], c: 2, exp: "Kaki burung (Crow's foot) merepresentasikan sisi 'Many' (Banyak)." },
  { cat: "Pemodelan Sistem", q: "Pada Activity Diagram, simbol batang tebal horizontal/vertikal yang MEMBAGI satu alur menjadi beberapa alur paralel bersamaan dinamakan...", o: ["Decision Node", "Merge Node", "Fork Node", "Join Node", "Initial Node"], c: 2, exp: "Fork Node memecah satu aliran aktivitas menjadi beberapa aliran mengeksekusi secara paralel." },
  { cat: "Pemodelan Sistem", q: "Sebaliknya, simbol yang MENGGABUNGKAN kembali beberapa alur eksekusi paralel menjadi satu alur tunggal dinamakan...", o: ["Fork Node", "Join Node", "Decision Node", "Merge Node", "Final Node"], c: 1, exp: "Join Node menunggu seluruh cabang paralel tuntas sebelum melanjutkan aliran tunggal." },
  { cat: "Pemodelan Sistem", q: "Notasi panah putus-putus sederhana (--->) pada Class Diagram yang menandakan satu kelas menggunakan kelas lain secara sementara sebagai parameter dinamakan...", o: ["Dependency", "Association", "Aggregation", "Composition", "Generalization"], c: 0, exp: "Dependency menandakan perubahan pada satu kelas dapat mempengaruhi kelas lain yang bergantung." },
  { cat: "Pemodelan Sistem", q: "Manakah pernyataan yang BENAR mengenai Use Case Diagram?", o: ["Memuat detail algoritma program", "Hanya menggambarkan APA yang dilakukan sistem, bukan BAGAIMANA sistem melakukannya", "Wajib dibuat setelah coding selesai", "Digunakan untuk merancang tabel database", "Hanya boleh memiliki 1 Aktor"], c: 1, exp: "Use Case berfokus pada kebutuhan fungsional (WHAT), bukan implementasi internal (HOW)." },
  { cat: "Pemodelan Sistem", q: "Jika Aktor 'Siswa' dan Aktor 'Guru' memiliki akses login yang sama ke sistem, dalam Use Case Diagram kedua Aktor tersebut dapat dihubungkan dengan relasi...", o: ["Include", "Extend", "Generalization Aktor", "Dependency", "Association"], c: 2, exp: "Aktor dapat memiliki relasi Generalization (misal Siswa dan Guru mewarisi Use Case Aktor Pengguna)." },
  { cat: "Pemodelan Sistem", q: "Simbol lingkaran hitam padat pada Activity Diagram menandakan...", o: ["Initial Node (Mulai)", "Final Node (Selesai)", "Decision Node", "Action State", "Fork Node"], c: 0, exp: "Initial Node (titik awal) disimbolkan lingkaran hitam padat." },
  { cat: "Pemodelan Sistem", q: "Simbol lingkaran hitam di dalam lingkaran luar (bullseye) pada Activity Diagram menandakan...", o: ["Initial Node", "Activity Final Node (Selesai)", "Fork Node", "Join Node", "Decision Node"], c: 1, exp: "Activity Final Node disimbolkan lingkaran berbingkai (bullseye)." },

  // MOTS+ (31-45) - Analisis Diagram & Transformasi ERD ke Schema Relasional
  { cat: "Pemodelan Sistem", q: "Jika relasi ERD berkardinalitas 1:N (Satu Kelas memiliki Banyak Siswa), lokasi Foreign Key yang BENAR saat ditransformasikan ke tabel relasional adalah...", o: ["Primary Key Kelas ditaruh di Tabel Siswa sebagai Foreign Key", "Primary Key Siswa ditaruh di Tabel Kelas", "Foreign Key dibuat di tabel baru ketiga", "Tidak perlu Foreign Key", "FK ditaruh acak"], c: 0, exp: "Pada relasi 1:N, Primary Key dari sisi '1' (Kelas) selalu dipindahkan menjadi Foreign Key di sisi 'N' (Siswa)." },
  { cat: "Pemodelan Sistem", q: "Jika relasi ERD berkardinalitas N:M (Banyak Siswa mengambil Banyak Ekstrakurikuler), bagaimana aturan transformasinya ke basis data relasional?", o: ["Cukup tambahkan Foreign Key di salah satu tabel", "Harus membuat TABEL TRANSITIF / PIVOT BARU yang berisi Primary Key kedua tabel sebagai Foreign Key", "Relasi N:M dilarang di database", "Foreign Key diganti angka 0", "Dibuat menjadi 10 kolom tambahan"], c: 1, exp: "Relasi N:M wajib diurai menjadi tabel junction baru bertumpukan dua Foreign Key." },
  { cat: "Pemodelan Sistem", q: "Tracing Sequence Diagram: Sebuah objek `LoginForm` mengirim pesan `login(user, pass)` ke objek `AuthService`. `AuthService` lalu mengirim query ke `UserTable`. Garis pesan balasan (reply message) dari `UserTable` ke `AuthService` digambarkan dengan...", o: ["Garis lurus panah padat (——►)", "Garis putus-putus panah terbuka (- - -►)", "Garis ganda", "Garis melengkung", "Garis merah"], c: 1, exp: "Return/Reply Message pada Sequence Diagram disimbolkan garis putus-putus berpuncak panah terbuka." },
  { cat: "Pemodelan Sistem", q: "Manakah urutan tahapan perancangan sistem yang paling terstruktur sesuai metodologi Berorientasi Objek?", o: ["Coding -> Class Diagram -> Use Case Diagram -> Deployment", "Use Case Diagram -> Activity Diagram -> Class Diagram -> Coding", "Class Diagram -> ERD -> Use Case Diagram -> Testing", "Deployment Diagram -> Use Case -> Coding", "Testing -> Coding -> Design"], c: 1, exp: "Perancangan berawal dari pengumpulan kebutuhan (Use Case), alur kerja (Activity), struktur (Class), lalu coding." },
  { cat: "Pemodelan Sistem", q: "Pada Use Case `Transfer Uang`, terdapat Use Case `Verifikasi PIN`. Karena setiap transfer uang SELALU butuh verifikasi PIN, maka relasinya adalah...", o: ["Transfer Uang <<extend>> Verifikasi PIN", "Transfer Uang <<include>> Verifikasi PIN", "Verifikasi PIN <<include>> Transfer Uang", "Generalization", "Association"], c: 1, exp: "Karena Verifikasi PIN mutlak wajib dijalankan saat Transfer Uang, maka `Transfer Uang <<include>> Verifikasi PIN`." },
  { cat: "Pemodelan Sistem", q: "Pada Use Case `Belanja Online`, terdapat Use Case `Masukan Kode Promo`. Kode promo HANYA diproses jika pengguna memiliki kupon. Relasi yang tepat adalah...", o: ["Masukan Kode Promo <<extend>> Belanja Online", "Belanja Online <<include>> Masukan Kode Promo", "Masukan Kode Promo <<include>> Belanja Online", "Generalization", "Association"], c: 0, exp: "Karena masukan promo bersifat opsional/kondisional, Use Case pembantu meng-extend Use Case utama." },
  { cat: "Pemodelan Sistem", q: "Jika sebuah Class Diagram memiliki kelas `Mobil` yang tersusun atas kelas `Roda`, `Mesin`, dan `Pintu`, jenis relasi yang paling presisi adalah...", o: ["Generalization", "Composition", "Dependency", "Realization", "Association Biasa"], c: 1, exp: "Relasi part-of yang tidak dapat berdiri sendiri jika mobil dihancurkan adalah Composition." },
  { cat: "Pemodelan Sistem", q: "Manakah notasi visibilitas atribut di Class Diagram UML yang BENAR?", o: ["+ untuk private, - untuk public, # untuk protected", "+ untuk public, - untuk private, # untuk protected", "* untuk public, & untuk private", "public untuk +, private untuk #", "tidak ada notasi visibilitas"], c: 1, exp: "Notasi UML: `+` Public, `-` Private, `#` Protected, `~` Package/Default." },
  { cat: "Pemodelan Sistem", q: "Atribut `+ count: int` pada Class Diagram menandakan bahwa atribut `count` bersifat...", o: ["Private bertipe int", "Public bertipe int", "Protected bertipe int", "Static bertipe int", "Constant bertipe int"], c: 1, exp: "Tanda `+` adalah visual penyimbolan modifier Public." },
  { cat: "Pemodelan Sistem", q: "Jika sebuah method pada Class Diagram digarisbawahi (underlined) contoh: `+ getCount(): int`, hal ini berarti method tersebut bersifat...", o: ["Abstract", "Static", "Private", "Final", "Virtual"], c: 1, exp: "Garis bawah pada nama atribut/method di Class Diagram UML menandakan variabel/method `static`." },
  { cat: "Pemodelan Sistem", q: "Jika nama Class pada Class Diagram ditulis miring (*Italic*), berarti Class tersebut bersifat...", o: ["Abstract Class", "Final Class", "Public Class", "Interface", "Deprecated Class"], c: 0, exp: "Cetak miring (*Italic*) pada nama Class atau Method di UML menandakan komponen Abstract." },
  { cat: "Pemodelan Sistem", q: "Dalam DFD (Data Flow Diagram) klasik, simbol dua garis sejajar horizontal merepresentasikan...", o: ["Data Store (Penyimpanan Data)", "External Entity", "Process", "Data Flow", "Boundary"], c: 0, exp: "Dua garis sejajar (atau persegi tanpa tutup kanan) merepresentasikan Data Store di DFD." },
  { cat: "Pemodelan Sistem", q: "Perbedaan mendasar DFD dan UML adalah...", o: ["DFD berorientasi Aliran Data (prosedural), UML berorientasi Objek (OOP)", "DFD khusus gambar fisik server", "UML hanya untuk database", "DFD menggunakan bahasa Java", "Keduanya persis sama"], c: 0, exp: "DFD berfokus pada aliran transformasi data sistem terstruktur, UML berfokus pada analisis PBO." },
  { cat: "Pemodelan Sistem", q: "Pada Sequence Diagram, pesan yang dikirimkan tanpa menunggu balasan (Asynchronous Message) disimbolkan panah...", o: ["Panah padat hitam (——►)", "Panah terbuka (——>", "Garis putus-putus", "Panah ganda", "Garis melingkar"], c: 1, exp: "Asynchronous Message menggunakan garis lurus berpuncak panah terbuka (——>)." },
  { cat: "Pemodelan Sistem", q: "Entitas Lemah (Weak Entity) pada ERD adalah...", o: ["Entitas yang tidak memiliki Primary Key sendiri dan keberadaannya bergantung entitas lain", "Entitas tanpa atribut", "Entitas yang terhapus", "Entitas berukuran kecil", "Entitas bertipe varchar"], c: 0, exp: "Weak Entity disimbolkan persegi panjang ganda dan keberadaannya bergantung pada Identifying Entity." },

  // HOTS (46-60) - Consistency Checks antar Diagram, Anti-patterns Pemodelan, Case Study Analysis
  { cat: "Pemodelan Sistem", q: "Sebuah sistem memiliki Use Case `Kelola Data Siswa`. Namun pada Class Diagram tidak ada Class `Siswa` maupun `SiswaController`. Kesalahan desain ini melanggar...", o: ["Konsistensi & Traceability antar Diagram UML", "Sintaks Java", "Aturan Normalisasi", "Kardinalitas ERD", "Aturan DDL"], c: 0, exp: "Setiap Use Case (persyaratan fungsional) harus dapat ditelusuri (traceable) ke Class pengendali di Class Diagram." },
  { cat: "Pemodelan Sistem", q: "Analisis Studi Kasus: Dalam sistem e-commerce, seorang Pembeli melakukan Checkout. Pembeli DAPAT memilih metode pembayaran Transfer Bank, E-Wallet, atau Kartu Kredit. Bagaimana model Use Case yang paling efisien?", o: ["Membuat 10 Aktor baru", "Use Case `Checkout` di-extend oleh Use Case spesifik `Bayar Transfer`, `Bayar E-Wallet`, dan `Bayar Kartu Kredit` (atau Generalization Use Case Pembayaran)", "Membuat 3 Use Case tanpa relasi", "Menghapus Use Case Checkout", "Menggabungkannya ke DFD"], c: 1, exp: "Variasi metode pembayaran bersifat opsional/spesifik dan dihubungkan via <<extend>> atau Generalization ke Use Case Pembayaran." },
  { cat: "Pemodelan Sistem", q: "Kesalahan Pemodelan: Menghubungkan Aktor langsung ke Aktor lain dengan garis asosiasi pada Use Case Diagram. Mengapa hal ini SALAH?", o: ["Aktor tidak boleh saling berkomunikasi langsung di Use Case Diagram (Asosiasi hanya antara Aktor dan Use Case)", "Warna aktor harus beda", "Aktor harus di dalam boundary", "Aktor tidak boleh punya nama", "Aktor wajib berbentuk persegi"], c: 0, exp: "Use Case Diagram memodelkan interaksi Aktor dengan Sistem (Use Case), bukan interaksi antar Aktor di luar sistem." },
  { cat: "Pemodelan Sistem", q: "Perhatikan diagram Activity: Terdapat Decision Node tetapi hanya ada 1 panah keluar. Apa akibat dari kesalahan pemodelan ini?", o: ["Alur aktivitas valid", "Dead-end / Invalid Flow karena Decision Node wajib memiliki minimal 2 jalur cabang bercabang (misal TRUE dan FALSE)", "Activity otomatis jalan 2 kali", "Sistem menjadi cepat", "Menjadi loop"], c: 1, exp: "Decision Node mengevaluasi kondisi sehingga wajib menyediakan minimal 2 cabang keluaran yang diberi guard condition." },
  { cat: "Pemodelan Sistem", q: "Jika sebuah Class Diagram memiliki hubungan melingkar tanpa henti (Circular Dependency) antar 5 Class, tindakan refactoring pemodelan terbaik adalah...", o: ["Menerapkan Inversion of Control / Interface Abstraction untuk memutus ketergantungan langsung", "Menghapus kelima class", "Mengubah semua atribut jadi public", "Membuat 5 Use Case baru", "Mengabaikannya"], c: 0, exp: "Circular dependency menyebabkan tight-coupling parah; diatasi dengan mengekstrak Interface/Abstraksi." },
  { cat: "Pemodelan Sistem", q: "Tracing ERD to Schema: Entitas `Mahasiswa` (PK: NIM) bertransaksi dengan Entitas `MataKuliah` (PK: KodeMK) dalam relasi `KRS` N:M dengan atribut `NilaiAkhir`. Bagaimana skema tabel `KRS` hasil transformasinya?", o: ["KRS (NIM, KodeMK, NilaiAkhir) dengan Composite Primary Key (NIM, KodeMK)", "KRS (NilaiAkhir)", "Mahasiswa (NIM, KodeMK, NilaiAkhir)", "MataKuliah (KodeMK, NIM)", "Tidak butuh tabel KRS"], c: 0, exp: "Tabel perantara KRS menampung PK dari kedua belah pihak sebagai Composite PK sekaligus menampung atribut relasi `NilaiAkhir`." },
  { cat: "Pemodelan Sistem", q: "Mengapa menyimpan Atribut Multivalue (misal no_hp_1, no_hp_2, no_hp_3) dalam 1 tabel yang sama melanggar prinsip perancangan ERD ke Relasional yang baik?", o: ["Membatasi jumlah nomor HP yang bisa disimpan dan menciptakan kolom-kolom NULL yang terbuang (melanggar 1NF)", "Membuat query SELECT cepat", "Diperbolehkan dalam SQL", "Menghapus Primary Key", "Tidak melanggar apapun"], c: 0, exp: "Kolom berulang membatasi fleksibilitas dan membuang memori dengan nilai NULL (harus dipisah jadi tabel anak 1:N)." },
  { cat: "Pemodelan Sistem", q: "Pada Sequence Diagram, jika sebuah objek memanggil method milik dirinya sendiri (Self Call / Recursive Call), gambaran panahnya adalah...", o: ["Panah melingkar kembali ke Activation Bar objek itu sendiri", "Panah ke objek lain", "Garis putus-putus ke luar layar", "Panah ganda ke Aktor", "Tidak disimbolkan"], c: 0, exp: "Self-message digambarkan dengan garis panah melengkung yang kembali ke Activation Bar objek asal." },
  { cat: "Pemodelan Sistem", q: "Dalam perancangan perangkat lunak modern (Agile), tujuan utama pembuatan diagram UML adalah...", o: ["Sebagai dokumentasi mati yang harus setebal 500 halaman", "Sebagai alat komunikasi dan pemahaman bersama arsitektur sistem bagi tim pengembang", "Persyaratan wajib dari kompiler Java", "Menghanti tugas coding", "Menghasilkan file exe otomatis"], c: 1, exp: "UML berfungsi sebagai cetak biru komunikasi arsitektur agar seluruh tim memiliki persepsi teknis yang seragam." },
  { cat: "Pemodelan Sistem", q: "Studi Kasus: Sistem ATM. Aktor 'Nasabah' memilih Use Case `Tarik Tunai`. Jika saldo tidak cukup, sistem menampilkan pesan error. Bagaimana model Use Case terbaik untuk kondisi saldo tidak cukup?", o: ["Use Case `Tampilkan Error Saldo` meng-<<extend>> Use Case `Tarik Tunai` dengan Extension Point 'Saldo Kurang'", "Use Case `Tarik Tunai` include `Tampilkan Error`", "Membuat Aktor Saldo baru", "Menghapus Use Case Tarik Tunai", "Menggabungkan ke Class Diagram"], c: 0, exp: "Kondisi pengecualian/error yang opsional dimodelkan dengan <<extend>> dari extension point Use Case utama." },
  { cat: "Pemodelan Sistem", q: "Apa peran 'System Boundary' (Kotak Persegi yang membungkus Use Case) pada Use Case Diagram?", o: ["Membatasi ruang lingkup mana fungsionalitas di DALAM sistem dan mana Aktor di LUAR sistem", "Hanya hiasan visual", "Menandakan server fisik", "Membatasi jumlah baris koding", "Menyimpan data user"], c: 0, exp: "System Boundary mendefinisikan batas lingkup (scope) aplikasi yang sedang dirancang." },
  { cat: "Pemodelan Sistem", q: "Dalam Class Diagram, relasi `Aggregation` disimbolkan dengan...", o: ["Garis dengan wajik/belah ketupat KOSONG di sisi kelas induk", "Garis dengan wajik HITAM PADAT", "Panah putus-putus", "Garis polos tanpa simbol", "Panah segitiga"], c: 0, exp: "Belah ketupat transparan/kosong (◊) menyimbolkan relasi Aggregation." },
  { cat: "Pemodelan Sistem", q: "Sebaliknya, relasi `Composition` disimbolkan dengan...", o: ["Garis dengan wajik KOSONG", "Garis dengan wajik HITAM PADAT di sisi kelas induk", "Panah putus-putus", "Garis lengkung", "Lingkaran hitam"], c: 1, exp: "Belah ketupat hitam padat (♦) menyimbolkan relasi Composition." },
  { cat: "Pemodelan Sistem", q: "Jika sebuah Sequence Diagram menunjukkan 50 objek saling mengirim pesan dalam satu layar secara tidak terstruktur, anti-pattern pemodelan ini menandakan...", o: ["Desain sistem sangat bagus", "Kurangnya dekomposisi modul (God Sequence / Poor Subsystem Isolation)", "Database sangat cepat", "Koding siap dideploy", "Sistem bersifat microservice"], c: 1, exp: "Sequence yang terlalu rumit menandakan kurangnya dekomposisi tanggung jawab antar komponen." },
  { cat: "Pemodelan Sistem", q: "Pada ERD, Atribut Komposit (Composite Attribute) adalah...", o: ["Atribut yang dapat dipecah lagi menjadi beberapa sub-atribut (misal `NamaLengkap` dipecah jadi `NamaDepan` dan `NamaBelakang`)", "Atribut bertipe integer", "Atribut primary key", "Atribut berulang", "Atribut buatan"], c: 0, exp: "Composite Attribute adalah atribut yang terdiri dari beberapa atribut pembentuk yang lebih kecil." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-04-pemodelan-sistem.json', output);
console.log('Done generating 60 Pertemuan 4 (Pemodelan Perangkat Lunak / UML & ERD) questions with 5 options');
