const fs = require('fs');

const questions = [
  // LOTS (1-15) - Array, Linked List, Stack, Queue, Hash Table, Tree, Graph basics
  { cat: "Struktur Data", q: "Struktur data linier di mana elemen disimpan pada lokasi memori yang berdampingan (kontigu) dan diakses lewat indeks numerik dinamakan...", o: ["Array", "Linked List", "Tree", "Graph", "Hash Table"], c: 0, exp: "Array menyimpan elemen secara linier pada lokasi blok memori kontigu." },
  { cat: "Struktur Data", q: "Struktur data linier di mana setiap elemen (node) memuat data dan pointer yang menunjuk ke alamat node berikutnya dinamakan...", o: ["Array", "Linked List", "Stack", "Queue", "Binary Tree"], c: 1, exp: "Linked List terdiri dari node-node yang saling terhubung lewat pointer referensi memori." },
  { cat: "Struktur Data", q: "Prinsip kerja struktur data Stack (Tumpukan) adalah LIFO, yang merupakan singkatan dari...", o: ["Last In First Out", "Last In Fast Out", "Lead In First Out", "Long In First Out", "Low In Fast Out"], c: 0, exp: "LIFO (Last In First Out): Elemen yang terakhir masuk akan pertama kali dikeluarkan." },
  { cat: "Struktur Data", q: "Operasi untuk MENAMBAHKAN elemen baru ke bagian paling atas (top) dari sebuah Stack dinamakan...", o: ["Pop", "Push", "Enqueue", "Dequeue", "Peek"], c: 1, exp: "Push memasukkan elemen baru ke atas tumpukan Stack." },
  { cat: "Struktur Data", q: "Operasi untuk MENGAMBIL/MENGHAPUS elemen paling atas (top) dari sebuah Stack dinamakan...", o: ["Push", "Pop", "Enqueue", "Dequeue", "Insert"], c: 1, exp: "Pop mengeluarkan elemen teratas dari Stack." },
  { cat: "Struktur Data", q: "Prinsip kerja struktur data Queue (Antrean) adalah FIFO, yang merupakan singkatan dari...", o: ["First In First Out", "First In Fast Out", "Fast In Fast Out", "Final In First Out", "First In Final Out"], c: 0, exp: "FIFO (First In First Out): Elemen yang pertama masuk akan pertama kali dikeluarkan." },
  { cat: "Struktur Data", q: "Operasi untuk MENAMBAHKAN elemen baru ke bagian belakang (rear) antrean Queue dinamakan...", o: ["Enqueue", "Dequeue", "Push", "Pop", "AddRear"], c: 0, exp: "Enqueue memasukkan elemen ke ekor (rear) antrean." },
  { cat: "Struktur Data", q: "Operasi untuk MENGAMBIL/MENGHAPUS elemen paling depan (front) dari antrean Queue dinamakan...", o: ["Enqueue", "Dequeue", "Pop", "Push", "RemoveFront"], c: 1, exp: "Dequeue mengeluarkan elemen paling depan antrean." },
  { cat: "Struktur Data", q: "Struktur data non-linier ber-hierarki yang terdiri dari Root, Node Anak, dan Leaf (daun) dinamakan...", o: ["Tree (Pohon)", "Graph", "Linked List", "Queue", "Array"], c: 0, exp: "Tree adalah struktur data hierarkis bercabang dari satu Root Node." },
  { cat: "Struktur Data", q: "Binary Tree adalah jenis Tree khusus di mana setiap Node induk (parent) dapat memiliki MAKSIMAL berapa banyak anak (children)?", o: ["1 anak", "2 anak", "3 anak", "Tidak terbatas", "0 anak"], c: 1, exp: "Binary Tree membatasi maksimal 2 child node per parent (left child & right child)." },
  { cat: "Struktur Data", q: "Struktur data non-linier yang terdiri dari kumpulan simpul (Vertex / Node) yang dihubungkan oleh sisi (Edge) dinamakan...", o: ["Graph", "Tree", "Stack", "Queue", "Array 2D"], c: 0, exp: "Graph merepresentasikan jaringan koneksi antar Vertex melalui Edge." },
  { cat: "Struktur Data", q: "Struktur data yang memetakan Kunci (Key) ke Nilai (Value) menggunakan fungsi Hash untuk pencarian pencarian konstan dinamakan...", o: ["Hash Table / Hash Map", "Linked List", "Binary Search Tree", "Stack", "Heap"], c: 0, exp: "Hash Table mengasosiasikan Key-Value via Hash Function." },
  { cat: "Struktur Data", q: "Operasi untuk MELIHAT elemen teratas Stack atau terdepan Queue TANPA menghapusnya dinamakan...", o: ["Peek / Top", "Pop", "Dequeue", "Look", "Search"], c: 0, exp: "Peek mengembalikan nilai teratas tanpa memodifikasi isi struktur data." },
  { cat: "Struktur Data", q: "Node pada Tree yang tidak memiliki anak sama sekali (berada di posisi paling bawah) dinamakan...", o: ["Root Node", "Leaf Node (Daun)", "Parent Node", "Internal Node", "Ancestor Node"], c: 1, exp: "Leaf Node adalah node terminal di bagian ujung bawah hirarki Tree." },
  { cat: "Struktur Data", q: "Node paling atas yang menjadi titik awal/sumber dari sebuah Tree dinamakan...", o: ["Root Node (Akar)", "Leaf Node", "Branch Node", "Sibling Node", "Child Node"], c: 0, exp: "Root Node adalah simpul induk tertinggi dari seluruh pohon." },

  // MOTS (16-30) - BST, Traversal (Pre/In/Post Order), Hash Collisions, Graph (DFS vs BFS), Complexity
  { cat: "Struktur Data", q: "Aturan utama pada Binary Search Tree (BST) adalah...", o: ["Nilai anak KIRI selalu LEBIH KECIL dari induk, dan nilai anak KANAN selalu LEBIH BESAR dari induk", "Nilai anak kiri selalu lebih besar", "Semua anak bernilai sama", "Node acak", "Anak kanan harus selalu genap"], c: 0, exp: "BST menjaga properti: Left Child < Parent < Right Child." },
  { cat: "Struktur Data", q: "Urutan penelusuran (Traversal) Binary Tree dengan alur: Node Induk -> Anak Kiri -> Anak Kanan dinamakan...", o: ["Pre-order Traversal", "In-order Traversal", "Post-order Traversal", "Level-order Traversal", "Breadth-First"], c: 0, exp: "Pre-order: Root -> Left -> Right." },
  { cat: "Struktur Data", q: "Urutan penelusuran Binary Tree dengan alur: Anak Kiri -> Node Induk -> Anak Kanan dinamakan...", o: ["Pre-order Traversal", "In-order Traversal", "Post-order Traversal", "Depth-First", "Out-order"], c: 1, exp: "In-order: Left -> Root -> Right. (Pada BST, In-order menghasilkan urutan data terurut terkecil ke terbesar!)." },
  { cat: "Struktur Data", q: "Urutan penelusuran Binary Tree dengan alur: Anak Kiri -> Anak Kanan -> Node Induk dinamakan...", o: ["Pre-order Traversal", "In-order Traversal", "Post-order Traversal", "Top-down Traversal", "Breadth-First"], c: 2, exp: "Post-order: Left -> Right -> Root." },
  { cat: "Struktur Data", q: "Algoritma penelusuran Graph yang menjelajahi simpul sedalam mungkin sebelum melakukan backtracking dinamakan...", o: ["Depth-First Search (DFS)", "Breadth-First Search (BFS)", "Binary Search", "Dijkstra", "Linear Search"], c: 0, exp: "DFS menelusuri satu cabang hingga ujung sebelum backtrack (menggunakan Stack/Rekursif)." },
  { cat: "Struktur Data", q: "Algoritma penelusuran Graph yang menjelajahi simpul tingkat demi tingkat (tetangga terdekat dulu) dinamakan...", o: ["Breadth-First Search (BFS)", "Depth-First Search (DFS)", "Binary Search", "A* Algorithm", "Bellman-Ford"], c: 0, exp: "BFS menjelajahi tetangga horizontal per level (menggunakan Queue)." },
  { cat: "Struktur Data", q: "Kondisi pada Hash Table di mana dua Key berbeda menghasilkan nilai indeks hash yang SAMA dinamakan...", o: ["Hash Collision", "Hash Overflow", "Hash Failure", "Hash Corruption", "Hash Leak"], c: 0, exp: "Hash Collision terjadi saat fungsi hash memetakan 2 key ke bucket yang sama." },
  { cat: "Struktur Data", q: "Metode penanganan Hash Collision yang menyimpan elemen-elemen berbenturan di dalam Linked List pada bucket yang sama dinamakan...", o: ["Separate Chaining", "Open Addressing", "Linear Probing", "Quadratic Probing", "Double Hashing"], c: 0, exp: "Separate Chaining membuat linked list di setiap slot bucket." },
  { cat: "Struktur Data", q: "Metode penanganan Hash Collision dengan mencari slot kosong berikutnya secara berurutan dinamakan...", o: ["Linear Probing", "Separate Chaining", "Binary Search", "Rehashing", "Stack Overflow"], c: 0, exp: "Linear Probing mencari slot index i+1, i+2 dst saat terjadi tabrakan." },
  { cat: "Struktur Data", q: "Kompleksitas waktu Big-O rata-rata untuk pencarian (search) dan penyisipan (insert) pada Hash Table ideal adalah...", o: ["O(1) Konstan", "O(N) Linear", "O(N^2) Kuadratik", "O(log N)", "O(N log N)"], c: 0, exp: "Hash Table menawarkan pencarian rata-rata O(1) konstan sangat cepat." },
  { cat: "Struktur Data", q: "Manakah struktur data yang paling tepat digunakan untuk fitur 'Undo / Redo' pada aplikasi editor teks?", o: ["Stack (2 buah Stack)", "Queue", "Array 1D", "Binary Tree", "Graph"], c: 0, exp: "Dua buah Stack (Undo stack & Redo stack) adalah struktur data standar fitur Undo/Redo (LIFO)." },
  { cat: "Struktur Data", q: "Manakah struktur data yang paling tepat digunakan untuk mengelola antrean cetak dokumen (Printer Spooling)?", o: ["Queue (FIFO)", "Stack (LIFO)", "Binary Search Tree", "Graph", "Array 2D"], c: 0, exp: "Printer spooler mengantrekan dokumen sesuai urutan kedatangan (First In First Out)." },
  { cat: "Struktur Data", q: "Keunggulan utama Linked List dibanding Array biasa adalah...", o: ["Ukuran Linked List bersifat dinamis (dapat membesar/menteril tanpa realokasi memori raksasa) dan penyisipan di awal efisien O(1)", "Pencarian elemen acak lebih cepat", "Memakan memori lebih sedikit", "Tidak menggunakan pointer", "Bisa diakses lewat indeks"], c: 0, exp: "Linked List dinamis dan cepat insert/delete di node head/tail O(1)." },
  { cat: "Struktur Data", q: "Kelemahan utama Linked List dibanding Array biasa adalah...", o: ["Akses acak (random access) elemen ke-N lambat O(N) karena harus ditelusuri dari node awal (head)", "Tidak bisa menyimpan data string", "Ukuran terbatas", "Proses delete tidak bisa dilakukan", "Tidak mendukung recursion"], c: 0, exp: "Linked List harus ditelusuri bertahap (Sequential Access O(N)) untuk mencapai elemen tengah." },
  { cat: "Struktur Data", q: "Pernyataan yang BENAR mengenai Graph Berarah (Directed Graph / Digraph) adalah...", o: ["Sisi (Edge) memiliki arah tertentu dari simpul asal ke simpul tujuan", "Sisi bisa dilalui dua arah bebas", "Tidak memiliki simpul", "Hanya boleh berbentuk lingkaran", "Graph pasti berbentuk pohon"], c: 0, exp: "Directed Graph memiliki panah penunjuk arah pada setiap Edge." },

  // MOTS+ (31-45) - Tracing Traversal Tree, Expression Trees, Heap, Graph Algorithms
  { cat: "Struktur Data", q: "Tracing Traversal In-Order:\nSebuah BST memiliki node: Root 10, Left Child 5, Right Child 15. Hasil Traversal In-Order-nya adalah...", o: ["5, 10, 15", "10, 5, 15", "5, 15, 10", "15, 10, 5", "10, 15, 5"], c: 0, exp: "In-Order (Left -> Root -> Right): 5, 10, 15 (Selalu terurut naik!)." },
  { cat: "Struktur Data", q: "Tracing Traversal Pre-Order pada BST yang sama (Root 10, Left 5, Right 15) adalah...", o: ["10, 5, 15", "5, 10, 15", "5, 15, 10", "15, 10, 5", "10, 15, 5"], c: 0, exp: "Pre-Order (Root -> Left -> Right): 10, 5, 15." },
  { cat: "Struktur Data", q: "Tracing Traversal Post-Order pada BST yang sama (Root 10, Left 5, Right 15) adalah...", o: ["5, 15, 10", "10, 5, 15", "5, 10, 15", "15, 5, 10", "10, 15, 5"], c: 0, exp: "Post-Order (Left -> Right -> Root): 5, 15, 10." },
  { cat: "Struktur Data", q: "Struktur data Heap khusus di mana nilai setiap Parent Node SELALU LEBIH BESAR atau sama dengan anak-anaknya dinamakan...", o: ["Max-Heap", "Min-Heap", "Binary Search Tree", "AVL Tree", "B-Tree"], c: 0, exp: "Max-Heap menjamin Root selalu memuat nilai terbesar dari seluruh pohon." },
  { cat: "Struktur Data", q: "Struktur data Max-Heap atau Min-Heap sering dimanfaatkan untuk mengimplementasikan...", o: ["Priority Queue (Antrean Berprioritas)", "Stack LIFO", "Simple Array", "Hash Table", "Doubly Linked List"], c: 0, exp: "Priority Queue menggunakan Heap agar mengambil elemen prioritas tertinggi/terrendah berjalan O(1) atau O(log N)." },
  { cat: "Struktur Data", q: "Kondisi kesalahan 'Stack Overflow' terjadi ketika...", o: ["Memory Call Stack habis akibat rekursi tanpa henti (infinite recursion)", "Ukuran array kurang", "Queue kosong", "Database crash", "Hash collision terlalu banyak"], c: 0, exp: "Stack Overflow terjadi saat alokasi memori Call Stack terlampaui." },
  { cat: "Struktur Data", q: "Perbedaan Doubly Linked List dibanding Singly Linked List adalah...", o: ["Setiap node pada Doubly Linked List memiliki DUA pointer: penunjuk ke node berikutnya (next) dan node sebelumnya (prev)", "Doubly Linked List berukuran ganda", "Singly tidak punya data", "Doubly khusus angka", "Doubly berbentuk melingkar"], c: 0, exp: "Doubly Linked List menyimpan pointer `next` dan `prev` untuk navigasi dua arah." },
  { cat: "Struktur Data", q: "Circular Linked List adalah...", o: ["Linked List di mana pointer node terakhir (tail) menunjuk kembali ke node pertama (head)", "Linked List berbentuk lingkaran di layar", "Node tanpa data", "Array yang diputar", "Queue yang penuh"], c: 0, exp: "Circular Linked List membentuk lingkaran tak terputus (tail.next = head)." },
  { cat: "Struktur Data", q: "Algoritma terpopuler untuk mencari jalur terpendek (Shortest Path) dari satu simpul ke simpul lain pada Weighted Graph berbobot positif adalah...", o: ["Algoritma Dijkstra", "Algoritma Bubble Sort", "Depth First Search", "Kruskal", "Prim"], c: 0, exp: "Dijkstra's Algorithm menemukan rute lintasan terpendek pada weighted graph." },
  { cat: "Struktur Data", q: "Algoritma Kruskal dan Prim digunakan untuk menemukan...", o: ["Minimum Spanning Tree (MST) pada Graph", "Shortest path", "Hash collision", "Binary Search", "Sorting Array"], c: 0, exp: "Kruskal dan Prim adalah algoritma greedy untuk membangun Minimum Spanning Tree." },
  { cat: "Struktur Data", q: "Tracing Stack Operasi: `Push(5); Push(3); Pop(); Push(8);`. Elemen teratas (top) Stack sekarang adalah...", o: ["8", "3", "5", "0", "Empty"], c: 0, exp: "Push(5) -> [5]. Push(3) -> [5, 3]. Pop() -> [5]. Push(8) -> [5, 8]. Top = 8." },
  { cat: "Struktur Data", q: "Tracing Queue Operasi: `Enqueue(A); Enqueue(B); Dequeue(); Enqueue(C);`. Elemen paling depan (front) Queue sekarang adalah...", o: ["B", "A", "C", "Empty", "Error"], c: 0, exp: "Enqueue(A) -> [A]. Enqueue(B) -> [A, B]. Dequeue() -> [B]. Enqueue(C) -> [B, C]. Front = B." },
  { cat: "Struktur Data", q: "Ekspresi Matematika `A + B` dinamakan notasi Infix. Bentuk notasi Postfix (Reverse Polish Notation)-nya adalah...", o: ["A B +", "+ A B", "A + B", "B A +", "+ B A"], c: 0, exp: "Postfix menaruh operator di belakang operand: `A B +`." },
  { cat: "Struktur Data", q: "Notasi Prefix dari ekspresi `A + B` adalah...", o: ["+ A B", "A B +", "A + B", "+ B A", "B A +"], c: 0, exp: "Prefix (Polish Notation) menaruh operator di depan operand: `+ A B`." },
  { cat: "Struktur Data", q: "Struktur data Tree seimbang di mana perbedaan tinggi cabang kiri dan kanan tidak boleh lebih dari 1 dinamakan...", o: ["AVL Tree (Self-balancing BST)", "Array Tree", "Heap", "Graph", "Simple Tree"], c: 0, exp: "AVL Tree secara otomatis melakukan rotasi untuk menjaga keseimbangan (balance factor <= 1)." },

  // HOTS (46-60) - Advanced Complexity, B-Trees for Databases, Memory Management, Trade-offs
  { cat: "Struktur Data", q: "Mengapa sistem basis data relasional (seperti MySQL/PostgreSQL) memilih menggunakan B-Tree / B+ Tree sebagai struktur data Indeks dibanding Binary Search Tree (BST) biasa?", o: ["B-Tree memiliki cabang banyak (self-balancing multi-way tree) yang meminimalkan jumlah pembacaan disk I/O yang lambat untuk data raksasa", "B-Tree lebih sedikit memakan memori", "BST tidak bisa disimpan di harddisk", "B-Tree khusus bahasa C", "B+ Tree tidak mendukung angka"], c: 0, exp: "B-Tree menyimpan banyak key per node, dirancang khusus meminimalkan pembacaan Disk I/O." },
  { cat: "Struktur Data", q: "Jika sebuah BST tidak seimbang dan tumbuh memanjang lurus menyerupai Linked List (Skewed Tree), kompleksitas pencarian terburuknya memburuk dari `O(log N)` menjadi...", o: ["O(N) Linear", "O(1) Konstan", "O(N^2) Kuadratik", "O(N log N)", "O(2^N)"], c: 0, exp: "Skewed BST memburuk menjadi pencarian linear O(N) karena kehilangan sifat pembagian dua area." },
  { cat: "Struktur Data", q: "Struktur data mana yang paling ideal digunakan untuk mengimplementasikan cache LRU (Least Recently Used) dengan kecepatan O(1) untuk pencarian dan pembaruan?", o: ["Gabungan Hash Map + Doubly Linked List", "Stack biasa", "Array 2D", "Binary Search Tree", "Queue murni"], c: 0, exp: "LRU Cache memadukan HashMap (O(1) lookup) dan DoublyLinkedList (O(1) node relocation)." },
  { cat: "Struktur Data", q: "Tracing Hash Table Worst-Case: Jika seluruh 1000 data dimasukkan ke Hash Table dan semuanya mengalami Hash Collision pada bucket yang sama (Separate Chaining), kompleksitas pencariannya menjadi...", o: ["O(N)", "O(1)", "O(log N)", "O(N^2)", "O(0)"], c: 0, exp: "Jika seluruh data masuk ke 1 linked list di 1 bucket, pencarian berubah menjadi Linear Search O(N)." },
  { cat: "Struktur Data", q: "Struktur data mana yang paling efisien digunakan oleh Algoritma Breadth-First Search (BFS) pada Graph?", o: ["Queue (FIFO)", "Stack (LIFO)", "Array 1D", "Max-Heap", "Binary Search Tree"], c: 0, exp: "BFS memanfaatkan Queue untuk menjelajahi simpul secara melintang per level (FIFO)." },
  { cat: "Struktur Data", q: "Struktur data mana yang paling efisien digunakan oleh Algoritma Depth-First Search (DFS) pada Graph?", o: ["Stack (LIFO) atau Rekursi", "Queue (FIFO)", "Priority Queue", "Hash Table", "Binary Heap"], c: 0, exp: "DFS memanfaatkan Stack (atau Call Stack rekursif) untuk penelusuran mendalam LIFO." },
  { cat: "Struktur Data", q: "Tracing Evaluasi Postfix: Ekspresi Postfix `5 3 2 * +`. Berapakah hasil akhirnya jika dievaluasi menggunakan Stack?", o: ["11", "16", "10", "25", "13"], c: 0, exp: "Operasi: Push 5, Push 3, Push 2. Ketemu `*`: Pop 2 & 3, hitung 3*2=6, Push 6. Ketemu `+`: Pop 6 & 5, hitung 5+6=11. Hasil = 11." },
  { cat: "Struktur Data", q: "Dalam analisis alokasi memori di bahasa C/C++, data variabel lokal fungsi disimpan di area memori ________, sedangkan alokasi memori dinamis (`malloc`/`new`) disimpan di area memori ________.", o: ["Stack, Heap", "Heap, Stack", "RAM, ROM", "Cache, Disk", "Register, Cache"], c: 0, exp: "Local variables disimpan di Stack memory, dynamic allocation disimpan di Heap memory." },
  { cat: "Struktur Data", q: "Apa risiko utama dari mengalokasikan memori dinamis di Heap (misal `int* p = new int[100];`) tanpa memanggil `delete[] p;` di C++?", o: ["Memory Leak (Memori Heap tidak terbebaskan meski fungsi selesai)", "Stack Overflow", "Compile Error", "Bluescreen otomatis", "Data terenkripsi"], c: 0, exp: "Tidak membebaskan alokasi Heap menyebabkan kebocoran memori (Memory Leak)." },
  { cat: "Struktur Data", q: "Manakah pernyataan yang BENAR mengenai perbedaan Matrix Adjasensi (Array 2D) dan List Adjasensi (Array of Linked List) untuk merepresentasikan Graph?", o: ["Matrix Adjasensi memakan memori O(V^2) cocok untuk Dense Graph, sedangkan List Adjasensi memakan memori O(V + E) efisien untuk Sparse Graph", "Matrix selalu lebih hemat memori", "List Adjasensi tidak bisa untuk graph berarah", "Matrix hanya untuk angka", "Keduanya sama persis"], c: 0, exp: "Adjacency Matrix memakan ruang V^2; Adjacency List sangat hemat O(V+E) untuk Sparse Graph." },
  { cat: "Struktur Data", q: "Dalam implementasi Trie (Prefix Tree), kegunaan utamanya dalam aplikasi nyata adalah...", o: ["Fitur Autocomplete / Auto-suggest kata pencarian dan Spell Checker", "Penyimpanan video", "Kalkulator statistik", "Enkripsi password", "Sorting angka"], c: 0, exp: "Trie sangat efisien untuk pencarian pencocokan awalan kata (Prefix Matching / Autocomplete)." },
  { cat: "Struktur Data", q: "Kompleksitas pencarian kata dengan panjang K karakter pada struktur data Trie adalah...", o: ["O(K) Konstan terhadap jumlah kata", "O(N) Berdasar total kata", "O(N^2)", "O(log N)", "O(2^K)"], c: 0, exp: "Trie mencari kata hanya berdasarkan panjang string K, terlepas dari ada jutaan kata di database." },
  { cat: "Struktur Data", q: "Tracing Recursion Call Stack:\n`void printNum(int n) { if(n==0) return; printNum(n-1); console.log(n); }`\nJika dipanggil `printNum(3)`, urutan cetakannya adalah...", o: ["1, 2, 3", "3, 2, 1", "3, 3, 3", "1, 1, 1", "0, 1, 2, 3"], c: 0, exp: "Fungsi memanggil dirinya dulu sampai n=0, lalu saat unwinding call stack mencetak dari bawah: 1, 2, 3." },
  { cat: "Struktur Data", q: "Struktur data Disjoint Set (Union-Find) digunakan secara efisien pada algoritma Graph mana?", o: ["Algoritma Kruskal (mendeteksi siklus)", "Algoritma Dijkstra", "BFS", "DFS", "Binary Search"], c: 0, exp: "Union-Find mendeteksi siklus secara ultra cepat pada Algoritma Kruskal." },
  { cat: "Struktur Data", q: "Manakah trade-off utama dari memilih struktur data Array dibanding Linked List?", o: ["Array sangat cepat untuk pembacaan acak O(1), namun mahal/lambat untuk penyisipan/penghapusan elemen di tengah O(N)", "Array lebih fleksibel ukurannya", "Array tidak butuh memori", "Array khusus angka", "Linked list tidak punya pointer"], c: 0, exp: "Array unggul di O(1) random access, tapi lemah di insertion/deletion O(N)." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-07-struktur-data.json', output);
console.log('Done generating 60 Pertemuan 7 (Struktur Data Dasar) questions with 5 options');
