const fs = require('fs');

const questions = [
  // LOTS - Dasar Tipe Data & Konsep (1-15)
  { cat: "Algoritma & Logika", q: "Langkah-langkah sistematis dan logis dalam menyelesaikan suatu masalah disebut...", o: ["Program", "Algoritma", "Flowchart", "Pseudocode", "Sintaksis"], c: 1, exp: "Algoritma adalah urutan langkah logis yang disusun secara sistematis untuk menyelesaikan masalah." },
  { cat: "Algoritma & Logika", q: "Tipe data yang digunakan untuk menyimpan nilai bilangan bulat adalah...", o: ["Float", "String", "Integer", "Boolean", "Double"], c: 2, exp: "Integer adalah tipe data khusus untuk bilangan bulat tanpa pecahan." },
  { cat: "Algoritma & Logika", q: "Di antara berikut ini, manakah yang BUKAN merupakan representasi dari algoritma?", o: ["Flowchart", "Pseudocode", "Bahasa Alami", "Database", "UML Activity Diagram"], c: 3, exp: "Database adalah tempat penyimpanan data, bukan representasi logika algoritma." },
  { cat: "Algoritma & Logika", q: "Simbol jajar genjang (parallelogram) pada flowchart berfungsi untuk menunjukkan...", o: ["Proses", "Input/Output", "Keputusan", "Mulai/Selesai", "Konektor"], c: 1, exp: "Jajar genjang digunakan untuk operasi Input dan Output data." },
  { cat: "Algoritma & Logika", q: "Simbol belah ketupat (diamond) pada flowchart berfungsi untuk...", o: ["Input", "Output", "Percabangan/Kondisi", "Konektor", "Proses Berulang"], c: 2, exp: "Belah ketupat (Decision) digunakan untuk menyeleksi kondisi benar atau salah." },
  { cat: "Algoritma & Logika", q: "Tipe data yang memiliki dua nilai saja yaitu True atau False adalah...", o: ["Boolean", "Char", "String", "Double", "Integer"], c: 0, exp: "Boolean hanya merepresentasikan nilai kebenaran: Benar (True) atau Salah (False)." },
  { cat: "Algoritma & Logika", q: "Variabel berfungsi sebagai...", o: ["Struktur pengulangan", "Alat pencetak teks", "Tempat penyimpanan data sementara di memori", "Penghubung antar flowchart", "Alat validasi logika"], c: 2, exp: "Variabel adalah lokasi di memori yang digunakan untuk menampung data yang nilainya dapat berubah." },
  { cat: "Algoritma & Logika", q: "Operator yang digunakan untuk mencari sisa pembagian adalah...", o: ["/", "*", "% (Modulus)", "div", "mod()"], c: 2, exp: "Modulus (%) mengembalikan sisa dari operasi pembagian." },
  { cat: "Algoritma & Logika", q: "Jika A = 5 dan B = 2, maka hasil dari A % B adalah...", o: ["2", "1", "2.5", "3", "0"], c: 1, exp: "5 dibagi 2 adalah 2 sisa 1. Jadi 5 % 2 = 1." },
  { cat: "Algoritma & Logika", q: "Pada penulisan pseudocode, perintah untuk menerima masukan dari pengguna biasanya ditandai dengan kata...", o: ["PRINT", "READ / INPUT", "WRITE", "DISPLAY", "ECHO"], c: 1, exp: "READ atau INPUT adalah konvensi pseudocode untuk membaca data masukan pengguna." },
  { cat: "Algoritma & Logika", q: "Konvensi penulisan nama variabel yang menggabungkan beberapa kata tanpa spasi, di mana kata pertama huruf kecil dan huruf pertama kata berikutnya besar disebut...", o: ["PascalCase", "snake_case", "camelCase", "kebab-case", "UPPER_CASE"], c: 2, exp: "Contoh camelCase: totalHargaBarang." },
  { cat: "Algoritma & Logika", q: "Kumpulan karakter (teks) dalam pemrograman disimpan menggunakan tipe data...", o: ["Integer", "Boolean", "Float", "String", "Character"], c: 3, exp: "String digunakan untuk menampung barisan karakter atau teks." },
  { cat: "Algoritma & Logika", q: "Hasil dari ekspresi logika: TRUE AND FALSE adalah...", o: ["TRUE", "FALSE", "ERROR", "NULL", "UNDEFINED"], c: 1, exp: "Operator AND hanya bernilai TRUE jika kedua sisi bernilai TRUE." },
  { cat: "Algoritma & Logika", q: "Hasil dari ekspresi logika: TRUE OR FALSE adalah...", o: ["TRUE", "FALSE", "ERROR", "NULL", "UNDEFINED"], c: 0, exp: "Operator OR akan bernilai TRUE jika setidaknya ada satu kondisi yang TRUE." },
  { cat: "Algoritma & Logika", q: "Operator logika NOT berfungsi untuk...", o: ["Membandingkan dua nilai", "Membalikkan nilai logika", "Menjumlahkan nilai Boolean", "Menghapus variabel", "Menggabungkan dua logika"], c: 1, exp: "NOT (negasi) akan mengubah TRUE menjadi FALSE dan sebaliknya." },

  // MOTS - Percabangan & Logika Menengah (16-30)
  { cat: "Algoritma & Logika", q: "Struktur kontrol yang digunakan untuk mengeksekusi blok kode HANYA JIKA kondisinya terpenuhi (benar) adalah...", o: ["FOR", "WHILE", "IF", "DO-WHILE", "SWITCH"], c: 2, exp: "Pernyataan IF digunakan untuk percabangan kondisional tunggal." },
  { cat: "Algoritma & Logika", q: "Struktur IF-ELSE IF-ELSE tepat digunakan ketika kita memiliki...", o: ["Satu kondisi saja", "Dua kondisi pasti benar", "Banyak pilihan kondisi yang saling bergantung", "Perulangan tanpa henti", "Struktur data Array"], c: 2, exp: "IF-ELSE IF cocok untuk menyeleksi banyak kondisi berurutan seperti grade A, B, C." },
  { cat: "Algoritma & Logika", q: "Untuk mengevaluasi satu variabel terhadap banyak nilai tetap secara spesifik dan efisien, sebaiknya menggunakan...", o: ["Nested IF", "SWITCH-CASE", "FOR loop", "WHILE loop", "DO-WHILE"], c: 1, exp: "SWITCH-CASE lebih rapi dan efisien dibanding banyak kondisi IF-ELSE IF pada satu variabel." },
  { cat: "Algoritma & Logika", q: "Apa yang terjadi jika kita tidak menggunakan keyword 'break' pada blok SWITCH-CASE di JavaScript/Java?", o: ["Error kompilasi", "Program berhenti", "Terjadi 'fall-through' mengeksekusi case berikutnya", "Akan me-return null", "Blok akan di-skip"], c: 2, exp: "Tanpa 'break', eksekusi akan terus meluncur (fall-through) ke blok case di bawahnya meskipun kondisinya tidak cocok." },
  { cat: "Algoritma & Logika", q: "Operator ternary ( ? : ) merupakan bentuk ringkas dari...", o: ["FOR loop", "WHILE loop", "IF-ELSE", "SWITCH-CASE", "TRY-CATCH"], c: 2, exp: "Kondisi ? nilai_jika_benar : nilai_jika_salah setara dengan blok IF-ELSE." },
  { cat: "Algoritma & Logika", q: "Perhatikan kode: if(x > 10 && x < 20). Kapan kondisi tersebut bernilai benar?", o: ["Jika x adalah 10", "Jika x adalah 20", "Jika x berada di antara 11 sampai 19", "Jika x di bawah 10", "Jika x lebih besar dari 20"], c: 2, exp: "Syaratnya x harus lebih besar dari 10 DAN lebih kecil dari 20." },
  { cat: "Algoritma & Logika", q: "Jika kita ingin sebuah blok kode dijalankan ketika variabel 'nilai' lebih dari 75 ATAU variabel 'kehadiran' lebih dari 80, operator yang digunakan adalah...", o: ["&& (AND)", "|| (OR)", "== (EQUAL)", "!= (NOT EQUAL)", "=> (ARROW)"], c: 1, exp: "OR (||) memastikan salah satu saja terpenuhi maka hasilnya benar." },
  { cat: "Algoritma & Logika", q: "Percabangan bersarang (Nested IF) berarti...", o: ["Banyak IF yang berjajar sejajar", "Ada IF di dalam blok IF lainnya", "IF yang diganti dengan SWITCH", "Menggabungkan FOR dan IF", "Sintaks IF yang salah"], c: 1, exp: "Nested IF adalah kondisi bercabang di dalam kondisi bercabang lainnya." },
  { cat: "Algoritma & Logika", q: "Pada JavaScript, operator '===' berbeda dengan '==' karena '===' juga memeriksa...", o: ["Kecepatan variabel", "Tipe data dari variabel", "Lokasi memori variabel", "Nama variabel", "Ruang lingkup (scope) variabel"], c: 1, exp: "Strict equality (===) memeriksa nilai sekaligus tipe datanya tanpa konversi tipe otomatis." },
  { cat: "Algoritma & Logika", q: "Perhatikan: let x = '5'; let y = 5; Hasil dari x === y adalah...", o: ["TRUE", "FALSE", "ERROR", "UNDEFINED", "NaN"], c: 1, exp: "FALSE karena '5' adalah string, sedangkan 5 adalah number." },
  { cat: "Algoritma & Logika", q: "Apabila variabel 'hujan' bernilai TRUE dan 'payung' bernilai FALSE, maka ekspresi (hujan AND NOT payung) bernilai...", o: ["TRUE", "FALSE", "ERROR", "NULL", "1"], c: 0, exp: "TRUE AND (NOT FALSE) -> TRUE AND TRUE -> TRUE." },
  { cat: "Algoritma & Logika", q: "Istilah untuk baris kode yang tidak pernah bisa dieksekusi karena logikanya tidak mungkin tercapai disebut...", o: ["Infinite Loop", "Dead Code / Unreachable Code", "Syntax Error", "Runtime Error", "Logical Bug"], c: 1, exp: "Unreachable code sering terjadi jika ada statement setelah 'return' atau kondisi IF yang mustahil." },
  { cat: "Algoritma & Logika", q: "Kondisi 'if (x % 2 == 0)' sering digunakan untuk mengecek apakah bilangan x adalah...", o: ["Bilangan Prima", "Bilangan Ganjil", "Bilangan Genap", "Bilangan Negatif", "Bilangan Real"], c: 2, exp: "Suatu bilangan adalah genap jika habis dibagi 2 (sisanya 0)." },
  { cat: "Algoritma & Logika", q: "Pada pseudocode, bagian ELSE akan dieksekusi apabila...", o: ["Kondisi IF di atasnya bernilai benar", "Kondisi IF di atasnya bernilai salah", "Terjadi perulangan", "Program telah selesai", "Tidak ada kondisi yang valid"], c: 1, exp: "ELSE adalah alternatif mutlak jika kondisi IF tidak terpenuhi." },
  { cat: "Algoritma & Logika", q: "Struktur percabangan paling tidak cocok digunakan untuk...", o: ["Menyeleksi login user", "Mengulang pencetakan angka 1-100", "Menentukan kelulusan siswa", "Memilih menu makanan", "Mengecek status pembayaran"], c: 1, exp: "Pencetakan berulang adalah tugas struktur perulangan (loop), bukan percabangan." },

  // MOTS+ - Perulangan (31-45)
  { cat: "Algoritma & Logika", q: "Struktur kontrol yang digunakan untuk mengulang sebuah blok instruksi selama kondisinya benar adalah...", o: ["IF-ELSE", "SWITCH", "WHILE", "RETURN", "BREAK"], c: 2, exp: "WHILE adalah loop dasar yang berjalan selama evaluasi kondisinya TRUE." },
  { cat: "Algoritma & Logika", q: "Perbedaan utama WHILE dan DO-WHILE adalah...", o: ["WHILE tidak butuh kondisi", "DO-WHILE mengeksekusi blok kode minimal 1 kali", "WHILE mengeksekusi minimal 1 kali", "DO-WHILE hanya untuk string", "Keduanya sama saja"], c: 1, exp: "Pada DO-WHILE, pengecekan kondisi dilakukan di akhir (setelah DO), jadi minimal jalan 1 kali." },
  { cat: "Algoritma & Logika", q: "Perulangan FOR sangat ideal digunakan ketika...", o: ["Jumlah perulangan tidak diketahui pasti", "Kondisi bergantung pada input user saat itu", "Jumlah iterasi sudah diketahui secara pasti (fixed)", "Ingin membuat percabangan", "Program membutuhkan input tak terbatas"], c: 2, exp: "FOR sangat efisien untuk counter (penghitung) yang batas iterasi awal dan akhirnya jelas." },
  { cat: "Algoritma & Logika", q: "Komponen utama dalam deklarasi FOR loop di bahasa C/Java adalah...", o: ["Inisialisasi, Kondisi, Terminasi", "Inisialisasi, Kondisi, Iterasi (Increment/Decrement)", "Kondisi, Eksekusi, Break", "Start, Run, Stop", "Setup, Execute, Teardown"], c: 1, exp: "Contoh: for (let i = 0; i < 10; i++). Inisialisasi, Kondisi, Iterasi." },
  { cat: "Algoritma & Logika", q: "Operator i++ pada perulangan disebut sebagai...", o: ["Decrement", "Increment", "Assignment", "Logical", "Relational"], c: 1, exp: "Increment (++) berfungsi untuk menambah nilai variabel sebesar 1." },
  { cat: "Algoritma & Logika", q: "Apa yang akan terjadi jika kondisi pada WHILE selalu bernilai TRUE tanpa ada instruksi perubahan di dalamnya?", o: ["Program akan error syntax", "Program akan berhenti perlahan", "Terjadi Infinite Loop (perulangan tanpa henti)", "Sistem akan otomatis me-restart PC", "Loop akan otomatis di-break oleh compiler"], c: 2, exp: "Infinite loop terjadi saat kondisi keluar loop tidak pernah tercapai, membuat browser/program hang." },
  { cat: "Algoritma & Logika", q: "Keyword yang digunakan untuk MELOMPATI sisa instruksi di dalam loop dan melanjutkan ke iterasi berikutnya adalah...", o: ["break", "continue", "return", "pass", "skip"], c: 1, exp: "Continue langsung melompat ke pengecekan kondisi/increment berikutnya." },
  { cat: "Algoritma & Logika", q: "Keyword yang digunakan untuk KELUAR secara paksa dari sebuah perulangan adalah...", o: ["break", "continue", "stop", "exit", "halt"], c: 0, exp: "Break menghentikan eksekusi blok loop secara total." },
  { cat: "Algoritma & Logika", q: "Struktur data variabel yang dapat menyimpan sekumpulan nilai dalam satu nama dan diakses melalui indeks adalah...", o: ["Integer", "String", "Object", "Array", "Float"], c: 3, exp: "Array (Larik) adalah kumpulan nilai berindeks." },
  { cat: "Algoritma & Logika", q: "Indeks pertama pada Array di hampir semua bahasa pemrograman dimulai dari angka...", o: ["-1", "0", "1", "Tidak berindeks", "Panjang Array"], c: 1, exp: "Array bersifat zero-indexed (indeks dimulai dari 0)." },
  { cat: "Algoritma & Logika", q: "Untuk mengakses elemen ke-5 dari array 'data', penulisannya adalah...", o: ["data[5]", "data(5)", "data[4]", "data{5}", "data<5>"], c: 2, exp: "Karena indeks mulai dari 0, elemen ke-5 berada pada indeks ke-4." },
  { cat: "Algoritma & Logika", q: "Perulangan bersarang (Nested Loop) sering digunakan untuk menangani kasus seperti...", o: ["Mengisi password", "Mencetak elemen pada matriks (Array 2 Dimensi)", "Menghitung luas lingkaran", "Mencari panjang string", "Menghapus data di database"], c: 1, exp: "Iterasi matriks butuh baris (loop luar) dan kolom (loop dalam)." },
  { cat: "Algoritma & Logika", q: "Berapa kali kata 'Halo' dicetak: for(i=1; i<=3; i++) { for(j=1; j<=3; j++) { print('Halo') } } ?", o: ["3 kali", "6 kali", "9 kali", "12 kali", "27 kali"], c: 2, exp: "Loop luar berjalan 3 kali. Setiap iterasi luar, loop dalam jalan 3 kali. 3 x 3 = 9." },
  { cat: "Algoritma & Logika", q: "Perulangan FOR EACH biasanya diperuntukkan secara khusus bagi...", o: ["Integer counting", "Array / Iterable Collection", "Boolean check", "Infinite loop", "Recursive function"], c: 1, exp: "forEach digunakan untuk menelusuri tiap elemen array secara langsung tanpa counter manual." },
  { cat: "Algoritma & Logika", q: "Pada flowchart, struktur perulangan dikenali dengan adanya arah panah yang...", o: ["Berakhir di Terminator", "Mengarah kembali (berbalik) ke proses sebelumnya", "Bercabang dua namun lurus ke bawah", "Terputus", "Menghilang dari garis utama"], c: 1, exp: "Panah balik (loopback) adalah ciri khas perulangan di diagram alir." },

  // HOTS - Tracing Code & Analisis (46-60)
  { cat: "Algoritma & Logika", q: "Tracing Code: let a=2, b=3; a = a + b; b = a - b; a = a - b; Nilai a dan b sekarang adalah...", o: ["a=5, b=2", "a=3, b=2", "a=2, b=3", "a=0, b=0", "a=5, b=3"], c: 1, exp: "Ini adalah algoritma menukar nilai variabel tanpa variabel bantuan (swap). Hasilnya a=3, b=2." },
  { cat: "Algoritma & Logika", q: "Fungsi yang memanggil dirinya sendiri secara terus-menerus hingga mencapai kondisi basis (base case) disebut...", o: ["Iterative", "Recursive", "Generative", "Responsive", "Reactive"], c: 1, exp: "Fungsi rekursif (misal faktorial) memanggil dirinya sendiri." },
  { cat: "Algoritma & Logika", q: "Tracing: function f(n) { if (n <= 1) return 1; return n * f(n-1); } Hasil dari f(4) adalah...", o: ["4", "10", "16", "24", "120"], c: 3, exp: "Ini adalah fungsi Faktorial. f(4) = 4 * f(3) = 4 * 3 * 2 * 1 = 24." },
  { cat: "Algoritma & Logika", q: "Tracing loop: let x=0; while(x < 5){ x+=2; } Berapa nilai akhir x setelah loop selesai?", o: ["4", "5", "6", "Infinite", "0"], c: 2, exp: "x=0 -> x=2 -> x=4 -> x=6. Saat x=6 kondisi (6<5) FALSE, loop berhenti. x bernilai 6." },
  { cat: "Algoritma & Logika", q: "Sebuah array memiliki elemen: [5, 2, 8, 1, 9]. Algoritma pengurutan yang membandingkan dua elemen bersebelahan secara terus-menerus dan menukarnya jika salah posisi adalah...", o: ["Selection Sort", "Bubble Sort", "Merge Sort", "Quick Sort", "Insertion Sort"], c: 1, exp: "Bubble sort beroperasi dengan mengecek pasangan bersebelahan hingga terbesar 'menggelembung' ke atas." },
  { cat: "Algoritma & Logika", q: "Algoritma pencarian yang mengharuskan data sudah terurut (sorted) sebelum dapat dilakukan pencarian dengan cara membagi dua area pencarian adalah...", o: ["Linear Search", "Binary Search", "Hash Search", "Depth First Search", "Breadth First Search"], c: 1, exp: "Binary search memerlukan kondisi data pre-sorted untuk mengeleminasi setengah area pada setiap langkah." },
  { cat: "Algoritma & Logika", q: "Tracing: let arr=[1,2,3]; arr.push(4); arr.pop(); Berapakah elemen terakhir arr sekarang?", o: ["1", "2", "3", "4", "Undefined"], c: 2, exp: "Push menambah 4. Pop membuang 4 (elemen terakhir). Sisa [1,2,3], elemen terakhir adalah 3." },
  { cat: "Algoritma & Logika", q: "Struktur data Antrean (Queue) beroperasi dengan prinsip FIFO. Artinya...", o: ["Masuk terakhir, Keluar pertama", "Masuk pertama, Keluar terakhir", "Masuk pertama, Keluar pertama", "Akses bebas", "Keluar acak"], c: 2, exp: "FIFO = First In First Out. Antrean pelanggan masuk duluan dilayani duluan." },
  { cat: "Algoritma & Logika", q: "Dalam analisis kompleksitas, Big-O Notation 'O(1)' berarti...", o: ["Waktu eksekusi meningkat linear dengan data", "Waktu eksekusi selalu konstan terlepas dari besarnya data", "Waktu eksekusi kuadratik", "Program tidak dapat dieksekusi", "Eksekusi bergantung memori CPU"], c: 1, exp: "O(1) berarti Constant Time. Operasi sangat efisien." },
  { cat: "Algoritma & Logika", q: "Sebuah program mengandung Nested Loop ganda: for(1..N){ for(1..N){ ... } }. Kompleksitas waktu Big-O dari program ini kemungkinan besar adalah...", o: ["O(1)", "O(log N)", "O(N)", "O(N^2)", "O(N!)"], c: 3, exp: "Loop di dalam loop dengan panjang N menghasilkan iterasi N * N = O(N kuadrat)." },
  { cat: "Algoritma & Logika", q: "Mencari nama 'Zaki' di buku telepon dengan membaliknya halaman per halaman dari depan adalah contoh dari algoritma...", o: ["Binary Search", "Linear / Sequential Search", "Interpolation Search", "Hashing", "Tree Traversal"], c: 1, exp: "Sequential search mencari secara urut satu per satu dari awal." },
  { cat: "Algoritma & Logika", q: "Tracing: let s = ''; for(let i=0; i<3; i++) { s += '*'; } console.log(s); Hasilnya?", o: ["*", "***", "*\n*\n*", "3*", "Error"], c: 1, exp: "Loop berjalan 3x dan menyambung string '*' tanpa pindah baris, menjadi '***'." },
  { cat: "Algoritma & Logika", q: "Kesalahan logika dalam algoritma (Logical Error) akan menyebabkan...", o: ["Program tidak bisa dikompilasi (build failed)", "Program berjalan tapi output/hasil tidak sesuai harapan", "Program crash di awal karena syntax", "Komputer mengalami hang keras", "Layar bluescreen"], c: 1, exp: "Logical error tidak melanggar aturan sintaks, sehingga program tetap jalan namun hasil salah (misal rumus salah)." },
  { cat: "Algoritma & Logika", q: "Jika sebuah algoritma membutuhkan waktu yang eksponensial O(2^N) untuk data yang sedikit bertambah, hal ini menandakan bahwa algoritma tersebut...", o: ["Sangat lambat dan tidak efisien untuk data besar", "Sangat cepat dan efisien", "Pilihan terbaik di industri", "Berjalan konstan", "Selalu O(1) di server mahal"], c: 0, exp: "O(2^N) adalah salah satu kompleksitas terburuk (Eksponensial), waktu membludak sangat cepat saat N bertambah." },
  { cat: "Algoritma & Logika", q: "Untuk menghindari Infinite Recursion (rekursif tanpa henti), setiap fungsi rekursif wajib memiliki...", o: ["Base Case (Kondisi Berhenti)", "For Loop", "Global Variable", "Tipe data Float", "Try Catch Block"], c: 0, exp: "Base case adalah kondisi if di dalam fungsi rekursif yang memerintahkannya berhenti memanggil dirinya lagi dan mulai mengembalikan nilai akhir." }
];

let output = `[\n`;
questions.forEach((q, i) => {
  const explanation = `💡 ${q.exp}`;
  output += `  {
    "id": ${i + 1},
    "category": "${q.cat}",
    "question": ${JSON.stringify(q.q)},
    "options": [${q.o.map(opt => JSON.stringify(opt)).join(', ')}],
    "correctAnswer": ${q.c},
    "explanation": ${JSON.stringify(explanation)}
  }`;
  if (i < questions.length - 1) output += ',\n';
});
output += `\n]\n`;

fs.writeFileSync('d:/DATA/PROJEK/agunggumelarsaputra.com/src/data/tka-questions/tka-01-algoritma-logika.json', output);
console.log('Done generating 60 Algoritma questions with 5 options');
